import {writeFileSync} from "node:fs";
import {execFileSync} from "node:child_process";
import {fileURLToPath} from "node:url";

/// Emits src/libraries/proof/algorand/ClprFalconDet1024Engine.sol with the NTT twiddle table
/// zetas[k] = ψ^brv10(k) mod q (ψ = 1945 = 11^6, a primitive 2048-th root of unity mod q = 12289).
///   npx tsx test/e2e/relay/algorand/codegen/falcon.ts

const q = 12289n;
const pw = (b: bigint, e: bigint) => {
    let r = 1n;
    b %= q;
    while (e) {
        if (e & 1n) r = (r * b) % q;
        b = (b * b) % q;
        e >>= 1n;
    }
    return r;
};
const psi = 1945n;
if (pw(psi, 1024n) !== q - 1n) throw new Error("psi");
const brv = (k: number) => {
    let r = 0;
    for (let i = 0; i < 10; i++) if ((k >> i) & 1) r |= 1 << (9 - i);
    return r;
};
const zetas = Array.from({length: 1024}, (_, k) => pw(psi, BigInt(brv(k))));
const table = zetas.map((z) => z.toString(16).padStart(4, "0")).join("");
const nInv = pw(1024n, q - 2n);

const src = `// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.28;

// AUTO-GENERATED by test/e2e/relay/algorand/codegen/falcon.ts — do not edit by hand.

/// @title ClprFalconDet1024Engine
/// @notice Verifier for Algorand's deterministic Falcon-1024 signatures (algorand/falcon
///         \`deterministic.c\`, used by go-algorand \`crypto.FalconVerifier\` for state-proof ephemeral keys):
///
///   salt   = version ‖ 0x0A ‖ "FALCON_DET" ‖ 0^28 (40 bytes; \`version\` is the signature's salt version)
///   c      = HashToPoint(SHAKE256(salt ‖ message)), n = 1024, q = 12289 ({ClprShake256Engine} op 2)
///   s1     = c − s2·h  mod (q, x^1024 + 1), centred to (−q/2, q/2]
///   accept ⇔ ‖s1‖² + ‖s2‖² ≤ 70,265,242
///
///         The public key is the 1,793-byte \`0x0A ‖ h\` (1,024 × 14-bit big-endian coefficients). The
///         signature is taken in Falcon's fixed-length "CT" form \`0xDA ‖ version ‖ s2\` (1,024 × 12-bit
///         two's complement) — the form go-algorand hashes into the state-proof signature commitment
///         (\`GetFixedLengthHashableRepresentation\`). A CT signature maps one-to-one to the compressed
///         signature the network verifies; −2048, which the compressed form cannot express, is rejected.
///
///         s2·h is computed with a negacyclic NTT over Z_q (Cooley–Tukey forward, Gentleman–Sande
///         inverse, twiddles ψ^brv10(k) with ψ = 1945 a primitive 2048-th root of unity) with lazy
///         reduction: forward butterflies stay below 11q, inverse ones below 2^11·q.
contract ClprFalconDet1024Engine {
    uint256 internal constant Q = 12289;
    uint256 internal constant L2_BOUND = 70265242;
    uint256 internal constant N_INV = ${nInv};
    bytes internal constant ZETAS = hex"${table}";

    /// @notice The {ClprShake256Engine}.
    address public immutable SHAKE;

    constructor(address shake) {
        SHAKE = shake;
    }

    /// @notice True iff \`sig\` (CT form) is a valid deterministic Falcon-1024 signature of \`message\`
    ///         under \`vkey\`.
    function verify(bytes calldata vkey, bytes calldata sig, bytes calldata message) external view returns (bool) {
        if (vkey.length != 1793 || vkey[0] != 0x0a || sig.length != 1538 || sig[0] != 0xda) return false;
        (bool ok, bytes memory c) =
            SHAKE.staticcall(abi.encodePacked(uint8(2), sig[1], uint8(0x0a), "FALCON_DET", bytes28(0), message));
        if (!ok || c.length != 32768) return false;
        bytes memory zetas = ZETAS;
        uint256 a; // s2 mod q, then NTT(s2)·NTT(h), then s2·h
        uint256 b; // h
        uint256 norm;
        assembly ("memory-safe") {
            a := mload(0x40)
            b := add(a, 0x8000)
            mstore(0x40, add(b, 0x8000))
        }
        // s2: 12-bit two's complement, 16 coefficients per 24 bytes
        bool bad;
        assembly ("memory-safe") {
            let sOff := add(sig.offset, 2)
            for { let g := 0 } lt(g, 64) { g := add(g, 1) } {
                let w := shr(64, calldataload(add(sOff, mul(g, 24))))
                for { let k := 0 } lt(k, 16) { k := add(k, 1) } {
                    let v := and(shr(sub(180, mul(k, 12)), w), 0xfff)
                    let dst := add(a, shl(5, add(shl(4, g), k)))
                    switch lt(v, 2048)
                    case 1 {
                        mstore(dst, v)
                        norm := add(norm, mul(v, v))
                    }
                    default {
                        if eq(v, 2048) { bad := 1 }
                        let m := sub(4096, v)
                        mstore(dst, sub(Q, m))
                        norm := add(norm, mul(m, m))
                    }
                }
            }
        }
        // h: 14-bit big-endian, 16 coefficients per 28 bytes
        assembly ("memory-safe") {
            let hOff := add(vkey.offset, 1)
            for { let g := 0 } lt(g, 64) { g := add(g, 1) } {
                let w := shr(32, calldataload(add(hOff, mul(g, 28))))
                for { let k := 0 } lt(k, 16) { k := add(k, 1) } {
                    let v := and(shr(sub(210, mul(k, 14)), w), 0x3fff)
                    if iszero(lt(v, Q)) { bad := 1 }
                    mstore(add(b, shl(5, add(shl(4, g), k))), v)
                }
            }
        }
        if (bad) return false;
        _ntt(a, zetas);
        _ntt(b, zetas);
        assembly ("memory-safe") {
            for { let i := 0 } lt(i, 0x8000) { i := add(i, 32) } {
                mstore(add(a, i), mulmod(mload(add(a, i)), mload(add(b, i)), Q))
            }
        }
        _intt(a, zetas);
        assembly ("memory-safe") {
            let cp := add(c, 0x20)
            for { let i := 0 } lt(i, 0x8000) { i := add(i, 32) } {
                let v := addmod(mload(add(cp, i)), sub(Q, mload(add(a, i))), Q)
                if gt(v, 6144) { v := sub(Q, v) }
                norm := add(norm, mul(v, v))
            }
        }
        return norm <= L2_BOUND;
    }

    /// @dev In-place forward negacyclic NTT (normal order in, bit-reversed order out); outputs < 11q.
    function _ntt(uint256 p, bytes memory zetas) private pure {
        assembly ("memory-safe") {
            let z := add(zetas, 0x20)
            let k := 0
            for { let len := 512 } len { len := shr(1, len) } {
                let lenB := shl(5, len)
                for { let start := 0 } lt(start, 1024) { start := add(start, shl(1, len)) } {
                    k := add(k, 1)
                    let zeta := shr(240, mload(add(z, shl(1, k))))
                    let lo := add(p, shl(5, start))
                    let end := add(lo, lenB)
                    for { let x := lo } lt(x, end) { x := add(x, 32) } {
                        let y := add(x, lenB)
                        let t := mulmod(zeta, mload(y), Q)
                        let u := mload(x)
                        mstore(y, sub(add(u, Q), t))
                        mstore(x, add(u, t))
                    }
                }
            }
        }
    }

    /// @dev In-place inverse NTT (bit-reversed order in, normal order out), outputs reduced mod q.
    function _intt(uint256 p, bytes memory zetas) private pure {
        assembly ("memory-safe") {
            let z := add(zetas, 0x20)
            let k := 1024
            let big := shl(11, Q)
            for { let len := 1 } lt(len, 1024) { len := shl(1, len) } {
                let lenB := shl(5, len)
                for { let start := 0 } lt(start, 1024) { start := add(start, shl(1, len)) } {
                    k := sub(k, 1)
                    let zeta := sub(Q, shr(240, mload(add(z, shl(1, k)))))
                    let lo := add(p, shl(5, start))
                    let end := add(lo, lenB)
                    for { let x := lo } lt(x, end) { x := add(x, 32) } {
                        let y := add(x, lenB)
                        let t := mload(x)
                        let v := mload(y)
                        mstore(x, add(t, v))
                        mstore(y, mulmod(zeta, sub(add(t, big), v), Q))
                    }
                }
            }
            for { let i := 0 } lt(i, 0x8000) { i := add(i, 32) } {
                mstore(add(p, i), mulmod(mload(add(p, i)), N_INV, Q))
            }
        }
    }
}
`;
const outFile = new URL("../../../../../src/libraries/proof/algorand/ClprFalconDet1024Engine.sol", import.meta.url);
writeFileSync(outFile, src);
execFileSync("forge", ["fmt", fileURLToPath(outFile)]); // keep generated code in repo format
console.log("wrote ClprFalconDet1024Engine.sol; n^-1 =", nInv);
