import {writeFileSync} from "node:fs";
import {execFileSync} from "node:child_process";
import {fileURLToPath} from "node:url";

/// Emits src/libraries/proof/algorand/ClprShake256Engine.sol: SHAKE256 on a Keccak-f[1600] permutation
/// (FIPS 202) unrolled per round over 25 little-endian 64-bit lanes held one per memory word at fixed addresses.
///   npx tsx test/e2e/relay/algorand/codegen/keccak.ts

const R = [
    [0, 36, 3, 41, 18],
    [1, 44, 10, 45, 2],
    [62, 6, 43, 15, 61],
    [28, 55, 25, 21, 56],
    [27, 20, 39, 8, 14],
]; // R[x][y]
const RC = [
    0x0000000000000001n, 0x0000000000008082n, 0x800000000000808an, 0x8000000080008000n, 0x000000000000808bn,
    0x0000000080000001n, 0x8000000080008081n, 0x8000000000008009n, 0x000000000000008an, 0x0000000000000088n,
    0x0000000080008009n, 0x000000008000000an, 0x000000008000808bn, 0x800000000000008bn, 0x8000000000008089n,
    0x8000000000008003n, 0x8000000000008002n, 0x8000000000000080n, 0x000000000000800an, 0x800000008000000an,
    0x8000000080008081n, 0x8000000000008080n, 0x0000000080000001n, 0x8000000080008008n,
];

const off = (i: number) => (i === 0 ? "pA" : `add(pA, ${i * 32})`);
const boff = (i: number) => (i === 0 ? "pB" : `add(pB, ${i * 32})`);
const coff = (i: number) => (i === 0 ? "pC" : `add(pC, ${i * 32})`);
const doff = (i: number) => (i === 0 ? "pD" : `add(pD, ${i * 32})`);

const lines: string[] = [];
const L = (s: string) => lines.push("                " + s);
// theta
for (let x = 0; x < 5; x++) {
    L(`mstore(${coff(x)}, xor(xor(xor(xor(mload(${off(x)}), mload(${off(x + 5)})), mload(${off(x + 10)})), mload(${off(x + 15)})), mload(${off(x + 20)})))`);
}
for (let x = 0; x < 5; x++) {
    L(`{ let c := mload(${coff((x + 1) % 5)}) mstore(${doff(x)}, xor(mload(${coff((x + 4) % 5)}), and(or(shl(1, c), shr(63, c)), M))) }`);
}
// rho + pi: B[y][2x+3y] = rot(A[x][y] ^ D[x], R[x][y])
for (let x = 0; x < 5; x++) {
    for (let y = 0; y < 5; y++) {
        const nx = y;
        const ny = (2 * x + 3 * y) % 5;
        const v = `xor(mload(${off(x + 5 * y)}), mload(${doff(x)}))`;
        const r = R[x][y];
        if (r === 0) L(`mstore(${boff(nx + 5 * ny)}, ${v})`);
        else L(`{ let t := ${v} mstore(${boff(nx + 5 * ny)}, and(or(shl(${r}, t), shr(${64 - r}, t)), M)) }`);
    }
}
// chi
for (let y = 0; y < 5; y++) {
    L(`{`);
    for (let x = 0; x < 5; x++) L(`    let b${x} := mload(${boff(x + 5 * y)})`);
    for (let x = 0; x < 5; x++) {
        const out = `xor(b${x}, and(xor(b${(x + 1) % 5}, M), b${(x + 2) % 5}))`;
        if (x === 0 && y === 0) L(`    mstore(pA, xor(${out}, rc(i)))`);
        else L(`    mstore(${off(x + 5 * y)}, ${out})`);
    }
    L(`}`);
}


const rcCases = RC.map((c, k) => (k === 23 ? `                default { c := 0x${c.toString(16)} }` : `                case ${k} { c := 0x${c.toString(16)} }`)).join("\n");
const out = lines.map((l) => "    " + l.replace(/\bM\b/g, "0xffffffffffffffff"));
const src = `// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.28;

// AUTO-GENERATED by test/e2e/relay/algorand/codegen/keccak.ts — do not edit by hand.

/// @title ClprShake256Engine
/// @notice Stand-alone SHAKE256 engine (FIPS 202: Keccak-f[1600], rate 136 bytes, domain padding
///         0x1F … 0x80). The KECCAK256 opcode cannot be used: it fixes the Keccak padding and the output
///         length. Algorand uses SHAKE256 for the state-proof coins and for Falcon's hash-to-point.
///         Like {ClprBlake2sHasher}, the contract owns its memory (lanes at fixed addresses), which keeps
///         the unrolled rounds out of the via-IR stack-to-memory mover. Called with \`staticcall\`.
///
///         Calldata \`0x01 ‖ outLen (u32 BE) ‖ data\` returns SHAKE256(data) truncated to \`outLen\` bytes.
///         Calldata \`0x02 ‖ data\` returns Falcon \`HashToPoint\` (n = 1024, q = 12289; the
///         falcon \`hash_to_point_vartime\` rejection rule \`w < 61445 → w mod q\` on big-endian 16-bit
///         words): 1,024 coefficients, one per 32-byte word.
/// @dev Memory map: 0x000 lanes A[25] · 0x320 B[25] · 0x640 C[5] · 0x6e0 D[5] · 0x780 the four array
///      bases · 0x800 input · output after input.
contract ClprShake256Engine {
    fallback() external {
        assembly {
            function rc(i) -> c {
                switch i
${rcCases}
            }
            // The lane, scratch, C and D arrays are addressed through bases read from memory (0x780…0x7e0),
            // so the optimizer cannot prove a store to one array leaves the others unchanged and does not
            // forward stored lanes into expressions with more live values than the stack holds.
            function permute() {
                for { let i := 0 } lt(i, 24) { i := add(i, 1) } {
                    let pA := mload(0x780)
                    let pB := mload(0x7a0)
                    let pC := mload(0x7c0)
                    let pD := mload(0x7e0)
${out.join("\n")}
                }
            }
            // absorb calldata[off, end) with SHAKE padding; leaves the first output block in A[0..16]
            function absorb(off, end) {
                for { let i := 0 } lt(i, 0x6a0) { i := add(i, 32) } { mstore(i, 0) }
                mstore(0x780, 0x000)
                mstore(0x7a0, 0x320)
                mstore(0x7c0, 0x640)
                mstore(0x7e0, 0x6e0)
                let len := sub(end, off)
                calldatacopy(0x800, off, len)
                let pos := 0
                for {} 1 {} {
                    let n := sub(len, pos)
                    if gt(n, 135) { n := 136 }
                    for { let i := 0 } lt(i, n) { i := add(i, 1) } {
                        let ln := shl(5, shr(3, i))
                        mstore(ln, xor(mload(ln), shl(shl(3, and(i, 7)), byte(0, mload(add(0x800, add(pos, i)))))))
                    }
                    if lt(n, 136) {
                        let ln := shl(5, shr(3, n))
                        mstore(ln, xor(mload(ln), shl(shl(3, and(n, 7)), 0x1f)))
                        mstore(0x200, xor(mload(0x200), shl(56, 0x80)))
                        permute()
                        break
                    }
                    permute()
                    pos := add(pos, 136)
                }
            }
            let op := byte(0, calldataload(0))
            switch op
            case 1 {
                let outLen := shr(224, calldataload(1))
                absorb(5, calldatasize())
                let o := add(0x800, calldatasize())
                for { let k := 0 } lt(k, outLen) { k := add(k, 1) } {
                    let r := mod(k, 136)
                    if and(gt(k, 0), iszero(r)) { permute() }
                    mstore8(add(o, k), and(shr(shl(3, and(r, 7)), mload(shl(5, shr(3, r)))), 0xff))
                }
                return(o, outLen)
            }
            case 2 {
                absorb(1, calldatasize())
                let o := add(0x800, calldatasize())
                o := and(add(o, 31), not(31))
                let n := 0
                for {} 1 {} {
                    // 17 lanes = 68 big-endian 16-bit words per block
                    for { let l := 0 } and(lt(l, 17), lt(n, 1024)) { l := add(l, 1) } {
                        let v := mload(shl(5, l))
                        for { let j := 0 } and(lt(j, 4), lt(n, 1024)) { j := add(j, 1) } {
                            let w := or(shl(8, and(shr(shl(4, j), v), 0xff)), and(shr(add(shl(4, j), 8), v), 0xff))
                            if lt(w, 61445) {
                                mstore(add(o, shl(5, n)), mod(w, 12289))
                                n := add(n, 1)
                            }
                        }
                    }
                    if eq(n, 1024) { break }
                    permute()
                }
                return(o, 32768)
            }
            default { revert(0, 0) }
        }
    }
}
`;
const outFile = new URL("../../../../../src/libraries/proof/algorand/ClprShake256Engine.sol", import.meta.url);
writeFileSync(outFile, src);
execFileSync("forge", ["fmt", fileURLToPath(outFile)]); // keep generated code in repo format
console.log("wrote ClprShake256Engine.sol", lines.length, "lines/round");
