import {writeFileSync} from "node:fs";
import path from "node:path";
import {fileURLToPath} from "node:url";
import {keccak256, type Hex} from "viem";
import {
    combStart,
    combTable,
    nibbleTable,
    PEDERSEN_POINTS,
    POSEIDON_RC,
    type Point
} from "../../test/e2e/relay/starknet.js";

/// Generates src/libraries/proof/starknet/StarkTables.sol: the precomputed Pedersen comb tables (two
/// data contracts, each runtime = 0x00 ‖ 255 comb points ‖ 15 nibble points, 64 bytes per affine point)
/// and the Poseidon round constants. Every value is derived here from the five pedersen_params.json
/// points and sha256("Hades" ‖ i), so the generated file can be reproduced and diffed.
///
/// Run: npx tsx script/starknet/genStarkTables.ts && forge fmt src/libraries/proof/starknet/StarkTables.sol

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.resolve(__dirname, "../../src/libraries/proof/starknet/StarkTables.sol");

const word = (v: bigint) => v.toString(16).padStart(64, "0");
const pt = (p: Point) => {
    if (!p) throw new Error("point at infinity in table");
    return word(p.x) + word(p.y);
};

function runtime(comb: Point[], nib: Point[]): string {
    return "00" + comb.slice(1).map(pt).join("") + nib.slice(1).map(pt).join("");
}

const pp = PEDERSEN_POINTS;
const tableA = runtime(combTable(pp.p0), nibbleTable(pp.p1));
const tableB = runtime(combTable(pp.p2), nibbleTable(pp.p3));
const q = combStart()!;
const rc = POSEIDON_RC.map(word).join("");

const chunk = (hex: string, width = 96) => hex.match(new RegExp(`.{1,${width}}`, "g"))!.map((l) => `            hex"${l}"`).join("\n");

const src = `// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.28;

// GENERATED by script/starknet/genStarkTables.ts — do not edit by hand.

/// @title StarkTables
/// @notice Constants for {StarkPedersen} and {StarkPoseidon}.
library StarkTables {
    /// @dev Comb accumulator start Q = 2^-31 · shift_point (mod the curve order): after the 31 comb
    ///      doublings it is exactly the Pedersen shift point.
    uint256 internal constant COMB_START_X = 0x${word(q.x)};
    uint256 internal constant COMB_START_Y = 0x${word(q.y)};
    /// @dev keccak256 of the runtime code of {StarkPedersenTableA} / {StarkPedersenTableB}.
    bytes32 internal constant TABLE_A_CODEHASH = ${keccak256(("0x" + tableA) as Hex)};
    bytes32 internal constant TABLE_B_CODEHASH = ${keccak256(("0x" + tableB) as Hex)};
    /// @dev Poseidon (Hades) round constants: 91 rounds × 3, sha256("Hades" ‖ i) mod p, big-endian words.
    bytes internal constant POSEIDON_RC =
${chunk(rc)};
}

/// @title StarkPedersenTableA
/// @notice Data contract: runtime = 0x00 ‖ T0[1..255] ‖ T1[1..15], T0[u] = Σ_{i∈bits(u)} 2^(31i)·P0,
///         T1[d] = d·P1 (affine x ‖ y). The leading STOP byte makes it non-executable.
contract StarkPedersenTableA {
    constructor() {
        bytes memory code =
${chunk(tableA)};
        assembly ("memory-safe") {
            return(add(code, 0x20), mload(code))
        }
    }
}

/// @title StarkPedersenTableB
/// @notice Data contract: runtime = 0x00 ‖ T2[1..255] ‖ T3[1..15] for P2 / P3, as {StarkPedersenTableA}.
contract StarkPedersenTableB {
    constructor() {
        bytes memory code =
${chunk(tableB)};
        assembly ("memory-safe") {
            return(add(code, 0x20), mload(code))
        }
    }
}
`;
writeFileSync(OUT, src);
console.log(`wrote ${path.relative(process.cwd(), OUT)} (tables ${tableA.length / 2} B each, poseidon ${rc.length / 2} B)`);
