// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.28;

import {console} from "forge-std/Test.sol";
import {OpStackVerifier} from "@hiero-ledger/clpr/verifiers/evm/opstack/OpStackVerifier.sol";
import {OpStackProposedVerifier} from "@hiero-ledger/clpr/verifiers/evm/opstack/OpStackProposedVerifier.sol";
import {OpStackVerifierBase} from "@hiero-ledger/clpr/verifiers/evm/opstack/OpStackVerifierBase.sol";
import {EthL1StateVerifier} from "@hiero-ledger/clpr/verifiers/evm/ethereum/EthL1StateVerifier.sol";
import {IEthL1StateVerifier} from "@hiero-ledger/clpr/verifiers/evm/ethereum/lib/IEthL1StateVerifier.sol";
import {ClprEvmBundleVerifier} from "@hiero-ledger/clpr/verifiers/evm/common/ClprEvmBundleVerifier.sol";
import {OpStackOutputRootProof as OP} from "@hiero-ledger/clpr/libraries/proof/opstack/OpStackOutputRootProof.sol";
import {EthBeaconLightClient} from "@hiero-ledger/clpr/libraries/proof/beacon/EthBeaconLightClient.sol";
import {ClprBeaconSsz} from "@hiero-ledger/clpr/libraries/proof/beacon/ClprBeaconSsz.sol";
import {ClprEvmStateProof} from "@hiero-ledger/clpr/libraries/proof/evm/ClprEvmStateProof.sol";
import {ClprTypes} from "@hiero-ledger/clpr/libraries/ClprTypes.sol";
import {ClprProtobuf} from "@hiero-ledger/clpr/libraries/codec/ClprProtobuf.sol";
import {RLP} from "@openzeppelin/contracts/utils/RLP.sol";
import {EthCommitteeFixtures} from "@test/verifiers/evm/ethereum/EthCommitteeFixtures.sol";

/// @dev Stand-in for the Ethereum light client: returns a fixed L1 execution state root and slot for
///      any proof, so the dispute-game matrix can be tested against synthetic L1 state. The real light
///      client runs in {OpStackVerifierEndToEndTest} (Foundry, generator committee) and in the vitest
///      live Base Sepolia spec (real sync committee).
contract MockEthL1StateVerifier is IEthL1StateVerifier {
    bytes32 internal immutable STATE_ROOT;
    uint64 internal immutable SLOT;

    constructor(bytes32 stateRoot, uint64 slot) {
        STATE_ROOT = stateRoot;
        SLOT = slot;
    }

    function verifyL1State(bytes calldata, bytes calldata)
        external
        view
        returns (bytes32, uint64, bytes memory, bytes memory)
    {
        return (STATE_ROOT, SLOT, "", "");
    }

    function genesisTrustAnchor(bytes calldata, bytes32)
        external
        pure
        returns (bytes memory, bytes memory, bytes memory)
    {
        revert("unused");
    }
}

/// @dev Shared fixture plumbing: the synthetic L1/L2 state generated by
///      `test/e2e/relay/buildOpStackSyntheticFixture.ts` (anvil eth_getProof, real MPT proofs).
abstract contract OpStackFixture is EthCommitteeFixtures {
    struct Case {
        bytes disputeProof;
        string name;
        bytes preimage;
    }

    string internal json;
    mapping(bytes32 => Case) internal cases;

    bytes32 internal l1StateRoot;
    uint64 internal l1Slot;
    uint256 internal l1Time;
    address internal asr;
    address internal asrStartingOnly;
    bytes32 internal asrImplCodeHash;
    address internal gameImpl;
    uint256 internal finalityDelay;

    bytes32 internal l2StateRoot;
    address internal service;
    bytes32 internal serviceCodeHash;
    bytes32 internal channelId;
    bytes internal l2AccountProof;
    bytes internal l2StorageProof;

    function setUp() public virtual override {
        super.setUp();
        json = vm.readFile(string.concat(vm.projectRoot(), "/test/verifiers/evm/opstack/fixtures/synthetic.json"));
        l1StateRoot = vm.parseJsonBytes32(json, ".l1.stateRoot");
        l1Slot = uint64(vm.parseJsonUint(json, ".l1.slot"));
        l1Time = vm.parseJsonUint(json, ".l1.time");
        asr = vm.parseJsonAddress(json, ".l1.anchorStateRegistry");
        asrStartingOnly = vm.parseJsonAddress(json, ".l1.anchorStateRegistryStartingOnly");
        asrImplCodeHash = vm.parseJsonBytes32(json, ".l1.anchorStateRegistryImplCodeHash");
        gameImpl = vm.parseJsonAddress(json, ".l1.gameImplementation");
        finalityDelay = vm.parseJsonUint(json, ".l1.finalityDelaySeconds");
        l2StateRoot = vm.parseJsonBytes32(json, ".l2.stateRoot");
        service = vm.parseJsonAddress(json, ".l2.service");
        serviceCodeHash = vm.parseJsonBytes32(json, ".l2.serviceCodeHash");
        channelId = vm.parseJsonBytes32(json, ".l2.channelId");
        l2AccountProof = vm.parseJsonBytes(json, ".l2.accountProof");
        l2StorageProof = vm.parseJsonBytes(json, ".l2.storageProof");
        Case[] memory all = abi.decode(vm.parseJson(json, ".cases"), (Case[]));
        for (uint256 i = 0; i < all.length; i++) {
            cases[keccak256(bytes(all[i].name))] = all[i];
        }
    }

    function _case(string memory name) internal view returns (Case memory c) {
        c = cases[keccak256(bytes(name))];
        require(c.disputeProof.length != 0, string.concat("unknown case ", name));
    }

    function _layout() internal pure returns (OP.Layout memory) {
        return OP.Layout({
            asrDisputeGameFactorySlot: 1,
            asrAnchorGameSlot: 2,
            asrStartingAnchorRootSlot: 3,
            asrBlacklistSlot: 5,
            asrRespectedGameTypeSlot: 6,
            asrRespectedGameTypeOffset: 0,
            asrRetirementTimestampOffset: 4,
            dgfGamesSlot: 103,
            gameStateSlot: 0,
            gameCreatedAtOffset: 0,
            gameResolvedAtOffset: 8,
            gameStatusOffset: 16,
            gameWasRespectedSlot: 0,
            gameWasRespectedOffset: 18
        });
    }

    function _profile(address registry, uint256 delay) internal view returns (OP.Profile memory) {
        return OP.Profile({
            rootFormat: OP.RootFormat.OUTPUT_ROOT,
            l2ChainId: 84532,
            anchorStateRegistry: registry,
            anchorStateRegistryImplCodeHash: asrImplCodeHash,
            disputeGameFinalityDelaySeconds: delay,
            gameImplementation: gameImpl,
            gameArgsHash: bytes32(0),
            layout: _layout()
        });
    }

    /// Flat 260-byte anchor carrying `channelId` and the pinned L2 service code hash (the committee
    /// fields only matter to the real light client).
    function _anchor(bytes32 cid, bytes32 codeHash, bytes32 committeeRoot, bytes memory aggregate)
        internal
        pure
        returns (bytes memory a)
    {
        a = new bytes(EthBeaconLightClient.TRUST_ANCHOR_LENGTH);
        bytes memory agg = aggregate.length == 128 ? aggregate : new bytes(128);
        assembly {
            let d := add(a, 32)
            mstore(add(d, 36), cid)
            mcopy(add(d, 68), add(agg, 32), 128)
            mstore(add(d, 196), committeeRoot)
            mstore(add(d, 228), codeHash)
        }
    }

    function _channelContext(bytes32 cid) internal view returns (bytes memory) {
        return ClprTypes.encodeChannelContext(
            ClprTypes.ChannelContext({channelId: cid, remoteServiceAddress: abi.encodePacked(service)})
        );
    }

    function _bundle(bytes memory lightClientProof, Case memory c) internal view returns (bytes memory) {
        bytes[] memory items = new bytes[](6);
        items[0] = RLP.encode(lightClientProof);
        items[1] = c.disputeProof;
        items[2] = RLP.encode(c.preimage);
        items[3] = l2AccountProof;
        items[4] = l2StorageProof;
        items[5] = RLP.encode(bytes(""));
        return RLP.encode(items);
    }

    function _assertExpectedMetadata(ClprTypes.QueueMetadata memory m) internal view {
        assertEq(uint8(m.state), vm.parseJsonUint(json, ".l2.expected.status"), "status");
        assertEq(m.nextMessageId, vm.parseJsonUint(json, ".l2.expected.nextMessageId"), "nextMessageId");
        assertEq(m.receivedMessageId, vm.parseJsonUint(json, ".l2.expected.receivedMessageId"), "receivedMessageId");
        assertEq(m.sentRunningHash, vm.parseJsonBytes32(json, ".l2.expected.sentRunningHash"), "sentRunningHash");
        assertEq(
            m.receivedRunningHash, vm.parseJsonBytes32(json, ".l2.expected.receivedRunningHash"), "receivedRunningHash"
        );
        assertEq(
            m.endpointManifestVersion,
            vm.parseJsonUint(json, ".l2.expected.endpointManifestVersion"),
            "endpointManifestVersion"
        );
    }
}

/// @notice The dispute-game acceptance matrix of both tiers on synthetic L1 state, with the L1 light
///         client mocked (see {MockEthL1StateVerifier}).
contract OpStackVerifierTest is OpStackFixture {
    MockEthL1StateVerifier internal l1;
    OpStackVerifier internal finalized;
    OpStackProposedVerifier internal proposed;
    bytes internal anchor;
    bytes internal ctx;

    function setUp() public override {
        super.setUp();
        l1 = new MockEthL1StateVerifier(l1StateRoot, l1Slot);
        finalized = new OpStackVerifier(l1, 0, 12, _profile(asr, finalityDelay));
        proposed = new OpStackProposedVerifier(l1, 0, 12, _profile(asr, finalityDelay));
        anchor = _anchor(channelId, serviceCodeHash, bytes32(0), "");
        ctx = _channelContext(channelId);
    }

    function _verify(OpStackVerifierBase v, string memory name)
        internal
        view
        returns (ClprTypes.QueueMetadata memory m)
    {
        (m,,,,) = v.verifyBundle(_bundle("", _case(name)), anchor, ctx);
    }

    function _expectReject(OpStackVerifierBase v, string memory name, bytes4 selector) internal {
        bytes memory proof = _bundle("", _case(name));
        vm.expectPartialRevert(selector);
        v.verifyBundle(proof, anchor, ctx);
    }

    // ── tiers ────────────────────────────────────────────────────────────────

    function test_finality_labels() public view {
        assertEq(uint8(finalized.FINALITY()), uint8(OpStackVerifierBase.Finality.FINALIZED));
        assertEq(uint8(proposed.FINALITY()), uint8(OpStackVerifierBase.Finality.PROPOSED));
    }

    // ── FINALIZED: accepted ──────────────────────────────────────────────────

    function test_finalized_acceptsResolvedDefenderWinsGamePastDelay() public view {
        _assertExpectedMetadata(_verify(finalized, "game:finalized"));
    }

    function test_finalized_acceptsAnchorGameRoot() public view {
        _assertExpectedMetadata(_verify(finalized, "anchor:game"));
    }

    function test_finalized_acceptsStartingAnchorRoot() public {
        OpStackVerifier v = new OpStackVerifier(l1, 0, 12, _profile(asrStartingOnly, finalityDelay));
        _assertExpectedMetadata(_verify(v, "anchor:startingRoot"));
    }

    function test_verifyL2StateRoot_returnsTheOutputRootsStateRoot() public view {
        Case memory c = _case("game:finalized");
        (bytes32 root, bytes memory na, bytes memory naId) = finalized.verifyL2StateRoot(_bundle("", c), anchor);
        assertEq(root, l2StateRoot);
        assertEq(na.length, 0);
        assertEq(naId.length, 0);
    }

    // ── FINALIZED: rejected ──────────────────────────────────────────────────

    function test_finalized_rejectsGameInsideFinalityDelay() public {
        _expectReject(finalized, "game:insideDelay", OP.GameNotFinalized.selector);
    }

    function test_finalized_rejectsChallengerWins() public {
        _expectReject(finalized, "game:challengerWins", OP.GameChallengerWins.selector);
    }

    function test_finalized_rejectsInProgressGame() public {
        _expectReject(finalized, "game:inProgress", OP.GameNotResolved.selector);
    }

    function test_finalized_rejectsBlacklistedGame() public {
        _expectReject(finalized, "game:blacklisted", OP.GameBlacklisted.selector);
    }

    function test_finalized_rejectsRetiredGame() public {
        _expectReject(finalized, "game:retired", OP.GameRetired.selector);
    }

    function test_finalized_rejectsWrongGameType() public {
        _expectReject(finalized, "game:wrongType", OP.GameTypeNotRespected.selector);
    }

    function test_finalized_rejectsWrongGameTypeClaimedAsRespected() public {
        _expectReject(finalized, "game:wrongType:claimedRespected", OP.GameNotRegistered.selector);
    }

    function test_finalized_rejectsGameNotRespectedWhenCreated() public {
        _expectReject(finalized, "game:notRespected", OP.GameNotRespectedWhenCreated.selector);
    }

    function test_finalized_rejectsCloneOfOtherImplementation() public {
        _expectReject(finalized, "game:wrongImpl", OP.GameImplementationMismatch.selector);
    }

    function test_finalized_rejectsForgedGameCode() public {
        _expectReject(finalized, "game:finalized:forgedCode", OP.GameCodeMismatch.selector);
    }

    function test_finalized_rejectsWrongOutputRootPreimage() public {
        _expectReject(finalized, "game:finalized:tamperedPreimage", OP.GameNotRegistered.selector);
        _expectReject(finalized, "anchor:game:tamperedPreimage", OP.GameNotRegistered.selector);
    }

    function test_finalized_rejectsNonZeroOutputRootVersion() public {
        _expectReject(finalized, "game:finalized:badVersion", OP.UnsupportedOutputRootVersion.selector);
    }

    function test_finalized_rejectsUnknownMode() public {
        _expectReject(finalized, "game:finalized:mode7", OP.UnknownProofMode.selector);
    }

    function test_anchor_rejectsRegisteredGameThatIsNotTheAnchor() public {
        _expectReject(finalized, "anchor:notAnchorGame", OP.OutputRootNotAnchor.selector);
        _expectReject(proposed, "anchor:notAnchorGame", OP.OutputRootNotAnchor.selector);
    }

    function test_rejectsUnpinnedAnchorStateRegistryImplementation() public {
        OP.Profile memory p = _profile(asr, finalityDelay);
        p.anchorStateRegistryImplCodeHash = keccak256("some other AnchorStateRegistry");
        OpStackVerifier v = new OpStackVerifier(l1, 0, 12, p);
        _expectReject(v, "game:finalized", OP.AnchorStateRegistryImplMismatch.selector);
    }

    function test_rejectsProofForAnotherRegistry() public {
        // Pinned to the second registry, the first registry's account proof does not verify.
        OpStackVerifier v = new OpStackVerifier(l1, 0, 12, _profile(asrStartingOnly, finalityDelay));
        bytes memory proof = _bundle("", _case("game:finalized"));
        vm.expectRevert();
        v.verifyBundle(proof, anchor, ctx);
    }

    /// `l1Time − resolvedAt > delay` is strict, as in `AnchorStateRegistry.isGameFinalized`.
    function test_finalityDelay_boundary() public {
        uint256 age = 10 days; // the finalized game resolved 10 days before the proven L1 time
        OpStackVerifier atBoundary = new OpStackVerifier(l1, 0, 12, _profile(asr, age));
        _expectReject(atBoundary, "game:finalized", OP.GameNotFinalized.selector);
        OpStackVerifier justPast = new OpStackVerifier(l1, 0, 12, _profile(asr, age - 1));
        _verify(justPast, "game:finalized");
    }

    function test_l1Clock_fromBeaconSlot() public {
        // Same state, but the L1 clock says the proof is from before the finalized game resolved + delay.
        OpStackVerifier early = new OpStackVerifier(l1, 0, 1, _profile(asr, finalityDelay)); // 1 s/slot
        _expectReject(early, "game:finalized", OP.GameNotFinalized.selector);
    }

    // ── L2 half ──────────────────────────────────────────────────────────────

    function test_rejectsWrongPinnedL2CodeHash() public {
        bytes memory proof = _bundle("", _case("game:finalized"));
        bytes memory otherAnchor = _anchor(channelId, keccak256("other"), bytes32(0), "");
        vm.expectRevert(ClprEvmBundleVerifier.CodeHashMismatch.selector);
        finalized.verifyBundle(proof, otherAnchor, ctx);
    }

    function test_rejectsStorageProofOfAnotherChannel() public {
        bytes memory proof = _bundle("", _case("game:finalized"));
        bytes memory otherAnchor = _anchor(keccak256("other channel"), serviceCodeHash, bytes32(0), "");
        vm.expectPartialRevert(ClprEvmStateProof.SlotNotProven.selector);
        finalized.verifyBundle(proof, otherAnchor, ctx);
    }

    function test_rejectsBadShapes() public {
        vm.expectRevert(OpStackVerifierBase.InvalidTrustAnchor.selector);
        finalized.verifyBundle(_bundle("", _case("game:finalized")), hex"00", ctx);

        bytes[] memory three = new bytes[](3);
        for (uint256 i = 0; i < 3; i++) {
            three[i] = RLP.encode(bytes(""));
        }
        vm.expectRevert(OpStackVerifierBase.InvalidPayloadShape.selector);
        finalized.verifyBundle(RLP.encode(three), anchor, ctx);

        bytes[] memory items = new bytes[](6);
        items[0] = RLP.encode(bytes(""));
        items[1] = RLP.encode(new bytes[](0)); // dispute proof with 0 fields
        items[2] = RLP.encode(_case("game:finalized").preimage);
        items[3] = l2AccountProof;
        items[4] = l2StorageProof;
        items[5] = RLP.encode(bytes(""));
        vm.expectPartialRevert(OP.InvalidDisputeProof.selector);
        finalized.verifyBundle(RLP.encode(items), anchor, ctx);

        items[1] = _case("game:finalized").disputeProof;
        items[2] = RLP.encode(bytes("short"));
        vm.expectPartialRevert(OP.InvalidOutputRootPreimage.selector);
        finalized.verifyBundle(RLP.encode(items), anchor, ctx);
    }

    function test_constructor_rejectsIncompleteProfile() public {
        OP.Profile memory p = _profile(asr, finalityDelay);
        vm.expectRevert(OpStackVerifierBase.InvalidDeployment.selector);
        new OpStackVerifier(IEthL1StateVerifier(address(0)), 0, 12, p);
        vm.expectRevert(OpStackVerifierBase.InvalidDeployment.selector);
        new OpStackVerifier(l1, 0, 0, p);
        p.gameImplementation = address(0);
        vm.expectRevert(OpStackVerifierBase.InvalidDeployment.selector);
        new OpStackVerifier(l1, 0, 12, p);
    }

    function test_profile_roundTrips() public view {
        OP.Profile memory p = finalized.profile();
        assertEq(p.anchorStateRegistry, asr);
        assertEq(p.anchorStateRegistryImplCodeHash, asrImplCodeHash);
        assertEq(p.disputeGameFinalityDelaySeconds, finalityDelay);
        assertEq(p.gameImplementation, gameImpl);
        assertEq(abi.encode(p.layout), abi.encode(_layout()));
    }

    // ── SUPER roots (OP Mainnet-style SuperFaultDisputeGame) ────────────────

    function _superVerifier() internal returns (OpStackVerifier) {
        OP.Profile memory p = _profile(asr, finalityDelay);
        p.rootFormat = OP.RootFormat.SUPER_ROOT_V1;
        p.l2ChainId = vm.parseJsonUint(json, ".l1.l2ChainId");
        p.layout.gameWasRespectedSlot = 9; // SuperFaultDisputeGame keeps it in its own slot
        p.layout.gameWasRespectedOffset = 0;
        return new OpStackVerifier(l1, 0, 12, p);
    }

    function test_super_acceptsOutputRootThroughSuperRoot() public {
        _assertExpectedMetadata(_verify(_superVerifier(), "super:finalized"));
    }

    function test_super_rejectsSuperRootWithoutOurChain() public {
        _expectReject(_superVerifier(), "super:withoutOurChain", OP.OutputRootNotInSuperRoot.selector);
    }

    function test_super_rejectsOtherOutputRootForOurChain() public {
        _expectReject(_superVerifier(), "super:tamperedPreimage", OP.OutputRootNotInSuperRoot.selector);
    }

    function test_super_rejectsBadOrMissingPreimage() public {
        OpStackVerifier v = _superVerifier();
        _expectReject(v, "super:badVersion", OP.InvalidSuperRootPreimage.selector);
        _expectReject(v, "super:missing", OP.InvalidSuperRootPreimage.selector);
    }

    function test_outputRootVerifier_rejectsSuperRootPreimage() public {
        _expectReject(finalized, "super:finalized", OP.InvalidSuperRootPreimage.selector);
    }

    function test_constructor_superRootNeedsChainId() public {
        OP.Profile memory p = _profile(asr, finalityDelay);
        p.rootFormat = OP.RootFormat.SUPER_ROOT_V1;
        p.l2ChainId = 0;
        vm.expectRevert(OpStackVerifierBase.InvalidDeployment.selector);
        new OpStackVerifier(l1, 0, 12, p);
    }

    // ── PROPOSED ─────────────────────────────────────────────────────────────

    /// The fast tier accepts exactly what the finalized tier rejects for lack of resolution/finality…
    function test_proposed_acceptsWhatFinalizedRejects() public {
        _expectReject(finalized, "game:inProgress", OP.GameNotResolved.selector);
        _assertExpectedMetadata(_verify(proposed, "game:inProgress"));

        _expectReject(finalized, "game:insideDelay", OP.GameNotFinalized.selector);
        _assertExpectedMetadata(_verify(proposed, "game:insideDelay"));
    }

    function test_proposed_acceptsFinalizedAndAnchor() public view {
        _assertExpectedMetadata(_verify(proposed, "game:finalized"));
        _assertExpectedMetadata(_verify(proposed, "anchor:game"));
    }

    /// …but never a game its proposer lost, nor any game the registry disowns.
    function test_proposed_stillRejects() public {
        _expectReject(proposed, "game:challengerWins", OP.GameChallengerWins.selector);
        _expectReject(proposed, "game:blacklisted", OP.GameBlacklisted.selector);
        _expectReject(proposed, "game:retired", OP.GameRetired.selector);
        _expectReject(proposed, "game:wrongType", OP.GameTypeNotRespected.selector);
        _expectReject(proposed, "game:notRespected", OP.GameNotRespectedWhenCreated.selector);
        _expectReject(proposed, "game:wrongImpl", OP.GameImplementationMismatch.selector);
        _expectReject(proposed, "game:finalized:tamperedPreimage", OP.GameNotRegistered.selector);
    }
}

/// @notice Both tiers end to end with the REAL {EthL1StateVerifier}: a self-consistent generator sync
///         committee (sk = 1) signs a beacon header whose body commits the synthetic L1 state root, so
///         BLS, the SSZ execution branch, the L1 dispute proofs and the L2 proofs all run for real.
contract OpStackVerifierEndToEndTest is OpStackFixture {
    bytes4 internal constant FORK_VERSION = 0x06000000;
    bytes32 internal constant GVR = bytes32(uint256(0x5e9011a));
    EthL1StateVerifier internal l1;
    OpStackVerifier internal finalized;
    OpStackProposedVerifier internal proposed;
    bytes internal anchor;
    bytes internal lightClientProof;

    function setUp() public override {
        super.setUp();
        l1 = new EthL1StateVerifier(
            ClprBeaconSsz.GINDEX_EXECUTION_STATE_ROOT_IN_BODY,
            9,
            ClprBeaconSsz.GINDEX_NEXT_SYNC_COMMITTEE_IN_STATE,
            6,
            8192
        );
        finalized = new OpStackVerifier(l1, 0, 12, _profile(asr, finalityDelay));
        proposed = new OpStackProposedVerifier(l1, 0, 12, _profile(asr, finalityDelay));

        bytes memory aggregate = _committeeAggregate();
        anchor = EthBeaconLightClient.encodeTrustAnchor(
            _uncompressedKeys(SYNC_COMMITTEE_SIZE),
            aggregate,
            GVR,
            abi.encodePacked(FORK_VERSION),
            channelId,
            serviceCodeHash
        );

        // Body root committing l1StateRoot at gindex 802 (zero siblings), header at the fixture's slot.
        bytes32[] memory branch = new bytes32[](9);
        bytes32 bodyRoot = l1StateRoot;
        uint256 idx = ClprBeaconSsz.GINDEX_EXECUTION_STATE_ROOT_IN_BODY;
        for (uint256 i = 0; i < 9; i++) {
            bodyRoot = idx & 1 == 1
                ? sha256(abi.encodePacked(branch[i], bodyRoot))
                : sha256(abi.encodePacked(bodyRoot, branch[i]));
            idx >>= 1;
        }
        bytes32 headerRoot =
            ClprBeaconSsz.beaconBlockHeaderRoot(l1Slot, 7, bytes32(uint256(1)), bytes32(uint256(2)), bodyRoot);
        bytes32 signingRoot =
            ClprBeaconSsz.computeSigningRoot(headerRoot, ClprBeaconSsz.computeSyncCommitteeDomain(FORK_VERSION, GVR));

        bytes[] memory header = new bytes[](5);
        header[0] = RLP.encode(uint256(l1Slot));
        header[1] = RLP.encode(uint256(7));
        header[2] = RLP.encode(bytes32(uint256(1)));
        header[3] = RLP.encode(bytes32(uint256(2)));
        header[4] = RLP.encode(bodyRoot);
        bytes[] memory agg = new bytes[](2);
        agg[0] = RLP.encode(_fullBits());
        agg[1] = RLP.encode(_aggSig(signingRoot, SYNC_COMMITTEE_SIZE));
        bytes[] memory br = new bytes[](9);
        for (uint256 i = 0; i < 9; i++) {
            br[i] = RLP.encode(branch[i]);
        }
        bytes[] memory lc = new bytes[](7);
        lc[0] = RLP.encode(header);
        lc[1] = RLP.encode(agg);
        lc[2] = RLP.encode(l1StateRoot);
        lc[3] = RLP.encode(br);
        lc[4] = RLP.encode(bytes("")); // no rotation
        lc[5] = RLP.encode(new bytes[](0));
        lc[6] = RLP.encode(new bytes[](0)); // full participation: no non-signers
        lightClientProof = RLP.encode(lc);
    }

    function _fullBits() internal pure returns (bytes memory b) {
        b = new bytes(64);
        for (uint256 i = 0; i < 64; i++) {
            b[i] = 0xff;
        }
    }

    function test_endToEnd_finalizedGame_withRealLightClient() public view {
        bytes memory proof = _bundle(lightClientProof, _case("game:finalized"));
        bytes memory ctx = _channelContext(channelId);
        uint256 g = gasleft();
        (ClprTypes.QueueMetadata memory m,, bytes memory na,,) = finalized.verifyBundle(proof, anchor, ctx);
        uint256 used = g - gasleft();
        _assertExpectedMetadata(m);
        assertEq(na.length, 0);
        console.log("OpStackVerifier.verifyBundle (GAME mode, 512/512, no rotation) execution gas:", used);
        console.log("  proofBytes:", proof.length);
    }

    function test_endToEnd_anchor_withRealLightClient() public view {
        bytes memory proof = _bundle(lightClientProof, _case("anchor:game"));
        uint256 g = gasleft();
        (ClprTypes.QueueMetadata memory m,,,,) = finalized.verifyBundle(proof, anchor, _channelContext(channelId));
        console.log("OpStackVerifier.verifyBundle (ANCHOR mode) execution gas:", g - gasleft());
        _assertExpectedMetadata(m);
    }

    function test_endToEnd_proposedTierAcceptsInProgressGame_finalizedRejects() public {
        bytes memory proof = _bundle(lightClientProof, _case("game:inProgress"));
        bytes memory ctx = _channelContext(channelId);
        (ClprTypes.QueueMetadata memory m,,,,) = proposed.verifyBundle(proof, anchor, ctx);
        _assertExpectedMetadata(m);
        vm.expectPartialRevert(OP.GameNotResolved.selector);
        finalized.verifyBundle(proof, anchor, ctx);
    }

    function test_endToEnd_rejectsSignatureUnderOtherForkVersion() public {
        bytes memory proof = _bundle(lightClientProof, _case("game:finalized"));
        bytes memory other = anchor;
        other[35] = 0x01; // fork version byte 3
        vm.expectRevert();
        finalized.verifyBundle(proof, other, _channelContext(channelId));
    }

    function test_verifyConfig_buildsEthAnchorAndDecodesLedgerConfig() public view {
        ClprTypes.LedgerConfiguration memory lc;
        lc.chainId = "eip155:84532";
        lc.serviceAddress = abi.encodePacked(service);
        lc.throttles.maxPeerEndpoints = 9;
        bytes[] memory cfg = new bytes[](6);
        cfg[0] = RLP.encode(uint256(8192 * 3 + 5));
        cfg[1] = _encodeCommittee(_uncompressedKeys(SYNC_COMMITTEE_SIZE), _committeeAggregate());
        cfg[2] = RLP.encode(GVR);
        cfg[3] = RLP.encode(abi.encodePacked(FORK_VERSION));
        cfg[4] = RLP.encode(ClprProtobuf.encodeControlMessage(lc));
        cfg[5] = RLP.encode(serviceCodeHash);
        (
            bytes memory channelContext,
            string memory chainId,
            bytes memory serviceAddress,,
            ClprTypes.Throttles memory throttles,
            bytes memory initialAnchor,
            bytes memory anchorId,
            ClprTypes.ClprEndpointManifest memory manifest
        ) = finalized.verifyConfig(RLP.encode(cfg), channelId, "");
        assertEq(initialAnchor, anchor, "same anchor as the bundle path");
        assertEq(anchorId, abi.encodePacked(uint64(3)));
        assertEq(chainId, "eip155:84532");
        assertEq(serviceAddress, abi.encodePacked(service));
        assertEq(throttles.maxPeerEndpoints, 9);
        assertEq(channelContext, _channelContext(channelId));
        assertEq(manifest.version, 0, "no manifest proof -> uninitialized");
    }
}

/// @notice {EthL1StateVerifier} guards.
contract EthL1StateVerifierTest is EthCommitteeFixtures {
    function test_constructor_rejectsInconsistentLayout() public {
        vm.expectRevert(EthL1StateVerifier.InvalidBeaconLayout.selector);
        new EthL1StateVerifier(802, 8, 87, 6, 8192); // 802 is depth 9
        vm.expectRevert(EthL1StateVerifier.InvalidBeaconLayout.selector);
        new EthL1StateVerifier(802, 9, 87, 6, 0);
    }

    function test_verifyL1State_rejectsBadInputs() public {
        EthL1StateVerifier v = new EthL1StateVerifier(802, 9, 87, 6, 8192);
        vm.expectRevert(EthL1StateVerifier.InvalidTrustAnchor.selector);
        v.verifyL1State(RLP.encode(new bytes[](7)), hex"00");
        vm.expectRevert(EthL1StateVerifier.InvalidLightClientProof.selector);
        v.verifyL1State(RLP.encode(new bytes[](0)), new bytes(260));
        vm.expectRevert(EthL1StateVerifier.InvalidConfigPayload.selector);
        v.genesisTrustAnchor(RLP.encode(new bytes[](0)), bytes32(0));
    }
}
