// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.28;

import {IZkSyncStateTreeVerifier} from "@hiero-ledger/clpr/verifiers/evm/zksync/lib/IZkSyncStateTreeVerifier.sol";

/// @title ZkSyncStateTreeVerifier
/// @notice Verifies `zks_getProof` storage proofs against a ZKsync Era (EraVM) state-tree root. Deployed
///         once and shared by every ZK Stack verifier; it holds no state.
///
/// ## The tree (zksync-era `core/lib/merkle_tree`, checked at commit ff5f519, 2026-08-25)
/// - Key: `blake2s(address left-padded to 32 bytes ‖ slot)` (`StorageKey::raw_hashed_key`), read as a
///   LITTLE-endian U256 (`hashed_key_u256`). Bit `d` of that integer chooses the side at depth `d`, depth 0
///   being the leaf level (`fold_merkle_path`: bit set → `hash(sibling ‖ node)`).
/// - Leaf: `blake2s(leafIndex as 8 bytes big-endian ‖ value)`; an absent key is the empty leaf
///   `blake2s(0^40)` (index 0, value 0).
/// - Branch: `blake2s(left ‖ right)`. Empty subtree of depth `d + 1`: `blake2s(e_d ‖ e_d)`.
/// - `zks_getProof` returns the siblings root-to-leaf (`metadata_calculator/src/api_server/mod.rs` reverses
///   the tree's leaf-to-root path) and omits the empty-subtree siblings nearest the leaf.
/// - A proof with leaf index 0 must carry value 0 (`TreeEntryWithProof::verify`).
///
/// ## Why no precompile
/// Hedera's BLAKE2F precompile (EIP-152, address 0x09) is the Blake2b F function: 64-bit words, 12
/// rounds, rotations 32/24/16/63 and a different IV. Blake2s uses 32-bit words, 10 rounds and rotations
/// 16/12/8/7, so BLAKE2F cannot compute it. Blake2s runs here in plain EVM code.
///
/// ## How Blake2s is computed
/// Every hash in a proof is a single 64-byte block (branches and key derivation) or a single padded
/// 40-byte block (leaves), so only the final-block compression is needed. The 4×4 state is kept as four
/// row words; word `i` of a row sits in bits `[64i, 64i+32)` of its row, so one G step runs on four columns
/// (then four diagonals) at once. Message word `k` sits zero-padded in its own memory slot at
/// `M_BASE + 32k`, so `mload(M_BASE + 32k + 8i)` yields it already placed in lane `i`. The rounds are
/// generated by `script/zksync/generateBlake2s.ts`.
///
/// Node hashes stay in that lane form between levels; only the root, the key inputs, the leaf and the
/// siblings cross the boundary. Siblings arrive in W-form (see {IZkSyncStateTreeVerifier}) so each one is
/// spread into message slots with shifts only. The empty-subtree hashes are a 256-entry W-form table
/// generated from the definition above.
///
/// ## Records
/// A proof of six or seven entries costs about 2M gas per entry, which together with the L1 half nears
/// Hedera's 15M limit. {recordStorage} proves entries in a separate transaction and stores `keccak256(value)`
/// under `keccak256(root ‖ account ‖ key)`; a later proof marks such an entry with `pathLen = RECORDED`
/// and pays one SLOAD for it. A record is a statement about `root` only, so recording needs no
/// permission: whoever later relies on it still has to authenticate `root`.
///
/// @dev Memory: `verifyStorage` owns memory. It copies the table to 0x80 (and asserts that), keeps the
///      root at 0x20a0 with the record-key scratch after it, the message slots at 0x2100–0x22ff (zero above
///      each word, and 0x2300–0x231f zero), the root and key lanes at 0x2340–0x23bf, and writes the
///      result at 0x2400. The assembly is therefore not marked memory-safe.
contract ZkSyncStateTreeVerifier is IZkSyncStateTreeVerifier {
    /// @notice `pathLen` value marking an entry proven earlier through {recordStorage}: no siblings follow, and the
    ///         value is checked against the record instead of folded.
    uint16 public constant RECORDED = 0xffff;

    /// @dev Empty-subtree hashes e_0 … e_255 in W-form (e_0 is the empty leaf).
    // <generated:empty-subtrees>
    bytes internal constant EMPTY_SUBTREE_HASHES = hex"5415bb94f6f42620016f41071be2ff9d32bb9bb35a0892cc0a6615b6f4be5f6b1a6652793435d6b5f872eac5ddd88718b114f56bb79f8e4cb0feb614a096fb2e"
        hex"8d80753d68e932b56979cc5b085f0fad246b0872cd282be03c6edfc77123bdc126344629c7f42d09f4bf14af5e827d975b3dd9359955752c5dbce07ab3b103a5"
        hex"e7f8bd557e20d59a2cd917a3a2ce094066bbe99fd5cfd6e020fe0cb57bc1b72ba09a267b976683a2a76aa3c2a4611de9c4eef3e8f0a4ddfd002c8fe2d9f295d8"
        hex"ce6cd3e77341aca1f97f9062bee72a75bc8033aff454c577159918c056f1e2c6c2e3d9d2b9410d06034451efd41edfcbd6f7ac73ab1805b1ac19e10a64ad1338"
        hex"5a4e9e768796e1a4d761b762ecc13b21836a48970ad1d9b6d3be1d82b19a617e46170801cb834e73e8c9fc0ae271dc84743b89dc72e60a19330ab133baaa1838"
        hex"16d6c6dc282164718a490ce25f7eead0998617024bfaa3a2781f346d276f1bec1a63aa904523950aaf7fc3a6bc15969fc3f39bb790fb82e43694e2e7d65ce982"
        hex"3e801c35cd9c5f4ac6888eb36d1e7f3a84779d418aa54dda22badb4d887b94bb8452f96f72afa2d7f6fa9bfac7bf75816d4dd4265ed52ce43ccd560989e7545a"
        hex"b5ae05333f475f571a56c62b69a62a8abca9e79d31dbd10ded77358425d086e17f7e2ab5f7d00996560508d2caccc4024d0336842d8fbeca8f1433ff0e17eb3b"
        hex"f0df213b24d41f5c336ea0789903851ec1ca3bab78f796ca914f1eb1ebf3c595691cf95f45ece807c8cb5dacd66b4d61b9874ebce4152661269214a16168ce0a"
        hex"8490caf35372a4d4ea428da630fff165cdd94de1709601e02981722f07c8a9349cc87153f441a23bbbcb3152b062d42fc6f855db5a795c384f708f53d0a8255b"
        hex"a82e0e07acefce000c98aa5d780c25b101b4de6909d0d5282b76ada762f1989529f75259e4ded9de5d3cefa4ade29895d8930295e5a11f0611f4dc3ac9f9097c"
        hex"784dfe15df7515d7ac493b8913913dc357f37a55748838fe0f210a9bec6187cf8ee2073d7a4e5efe553c2f7e5b0f287f584fa29b0358ee4f9f1b6157e5cb6593"
        hex"f4170089a4b2343476a395b94deb55e41abc926695d99b9ac8fd11f0c10adc64a886b02b39b8756dcb2df6508593bed272c7b7749e008412001a485a463d4985"
        hex"8d4486f4b5d767fdeed280ff5ed0f17d4b5f84b69ae5d71b48b05029ce800374e501d49345a305c1600309c1dcfe6f7968743781b8e3d6dee0f6d0c532d29bbc"
        hex"2da559bdea783e3466b31709258c046f477d561c69eda757a0e1ae20d4344f4950a310b4ff2bfeab2d60fe5cf5624ffdfdf678c18aa405796e01575dd2648474"
        hex"c5f7f29bf99a73fff34fb0dcdab2ddf410ed2daa2472c39f7e09bfab3a88db7916012b2b71030623c57a28c1ea72b9d0063ecc0a629c4725ae1d8bf50e4f4e9a"
        hex"72dcfd1668013fc53175bcb05b95715fd96d615a1ddc76e9f87e85707ff8bc51a4df6d4f7282a7e78ac776d45ed7208e1748b3679e69a9fe27437a15bdea9a99"
        hex"19da488afa757939da82f34854b00ddf29148a3ff891078957d8f9ed0c09cc01d53accef06002178dc5b1a39df1644c1f15e668cfba6348a818c76eee2706136"
        hex"6b70c2dfeb46003bd04db04439689c1f6b56696c15ef78d8af0216fa71320c6dbce675e5a6d563c8946f94371c67aa995365021aebea44ff3a59ce6b0995bed7"
        hex"b15d88fb3c0de1029e8b5c88d3c115c2ab1444f55372a3a4ca27bd8788573b4a1fad7b30cfaa84eb7b351f2242d84fd4d99acd4dc7b7e71b88262c5cdca209dd"
        hex"b4a4fa264f18c613c1e577e58a65cc8194b7a6b8eb207249530a879e16869ccf9fc0da973caf27624cb8a48fcaf4c78aa5e5d078a51fd8aca0639241b0e770b7"
        hex"125f61ed66a98eb69c3d6a365612aefadd21a70b2df44ee68ec2e3b4dce7e9eb6a53fb464c28cb51100e22e7a9b71fc62cce1d58087836f3fecf7c2b6fe878b0"
        hex"064abe6596dada1eab7eed640623b8cbd2c41dddee5d21576609ff2c31eed7830a123c55e7251f03e910c575b2854b2064ac44d70e0c89f6ae982f375d1b1168"
        hex"e3233591c262e00e7d3014f0244477bb38c6cd4753ce5645ae30ce851d3ffe99adfc68599e9071e049fe286b73183344fc3c443fd10879998f65ad8caa63d551"
        hex"b6d4630071b24e837ddbe3321a27a5bcece31b1c47e1780256f9386223c9d27ba1f7bf272502ef160d7f936b5499186eeb55dafc1a31d0dbf21067ddefac8745"
        hex"550a033d86363da606929daf89e911fc094d75bbf3de311e99a966b70fccd7265d72acbc31066e36b7c8fe58db34ef65a16146fe064d026a8c8b7e8be269c969"
        hex"c04c7b66eab7db62372dce7359268565509e0dba8f1caefe0cd9030ecc3f3463626e7b7d59d751b2a334ae2519664b06c02be9b1578ab0d18469bb8bd01b101f"
        hex"1c2e4062561dd2e7cc8aabd772ef7aa3483be110414eeef78a734b8d22eda73e8417ff8323ce5d60b2fec06182194ebd381ff35c0db13218b7f4af1937a105a5"
        hex"1f1b79a1bcae059a33ca1287236e7818f1225324a8c6a9a76b459ca1d665500d068b1b758f1faa9ee0f94fecde858bf812943f606d4443e05bcf369a86a3cffc"
        hex"eee0068abc23a748ae5783c7d6fb42b10f995372238552ff951afa3dafa1a29658a4f852facbf11368661d0f82c8ac13d6bda8df2139ed5932384d50c23552c5"
        hex"cace77f3cbadba1985127eb307b5fa0e39a4c0294c90aa8a8d6f6036b65a47e76a6d1e510113e377252b61e6e6e2216f5a820d26535a79750950717bdb29d966"
        hex"66fa3fbeac990aa4957fa97072dde848c8e7308d91fcf5df433208448df0e043f71973609f4f52dd8be72b0ac8202646b7620976227e959f7241ad188395e85e"
        hex"e0a4fd5869bc1c0007766fd7ef9b08affa4b7f313b288f31349b1eb1c9df1b5e48a5986cd73ff103a83060472c4ff63db7f74b1dfb9f2155cc588b73da1b06e3"
        hex"33183c401477fcbc0873f2362c3b51f20922c406c1b563f2e025cbc2ea3a1750b720a25f2dfc9dbb44f7a70f1eb7b4c23533118fc7c2df0da2390cfaa4ab4c53"
        hex"166889ac00283c66def8117c86398ec940fd9c1fe3921206aa89ed11b06d42e4de7c6dc77285ada8bc3691202b3fee24174e703c96fcae9f662c2a1e716797b0"
        hex"90ce825733bf9b4f11997f719df288a7c14326d81bcd926eb912113041c3d8d293229a84286ab78af66f3d35b1772768485f349b808692f24f48f415fc8bce1e"
        hex"c41644ea8e978e6e68bf244d6ac3bbf1e9246a7c2871d637d0cd1e062013c0efce90daaba115b054fc049b913a318573e050d693d497bc1aa43929ea57f3aba8"
        hex"1d088b45d4ffdcc30888d8358fadad4829c32a0f572164ad08a3e0635adb286284ad457b751d672b30af2b79bc455ea7dcb6f9971e6df83790c0306b4ed21b2d"
        hex"0ce602fe2a883501be8485dd6485b2f8a375ebccd02d60c7d795cd0f87d4263e6b94402ecda5a69bbb90b0be7d9167dd55da98e6d9f5cc517aa1e3fb8b3614be"
        hex"f1e045baa748fa422d6c34aba05084c3608e0e3b2132106f448e368ba7cdc66670f4b4b251b1a77a92e7598106eee88a310a201ea691a7ed17e4dcde78aca445"
        hex"cc11ae9481368f3bb0a424514f33e7a5e3fcb9bc9013bb174b3321e4d96fcfd660ffbb9e95d2e14bc01f13ffc0dcd999fa50d073e4d5c85265df768f815264d2"
        hex"8a184a5e004a951986c501761912ba4ce6e1524e689009fbe970efd4a6345d4c08483fbcc5fcfbd77774e62bdccd3243d078c4bf18ccfe3851a06615a0e936e6"
        hex"7f6fe25ae4612406ba5091ad6cb090708fe815cf09880d780e9c90000cef5166078fe41aca1567b5a19d312f381eb21b0a35586affb65d7232066a1aae306124"
        hex"34dd2aa38a5aa746810714aace3fc07f24bbdc862fc5cc88e77b18d10c485e23fda0bd6623f230d0e73f1bd6fcda7eb1864b0afb7252a66a3939dceef24dbcdf"
        hex"68033cd16d7ff40564684e020ba63e98066aad9947b366ea4c167dd86b459930298e7ee825a410e3755deeb5fa850ebd668729e136dbbc0baa31084240027a87"
        hex"ef139936a58887a08758e6b6c4f4a78b4ad7f2355657d42498f3d816309d27c4a063fcc1c355a424e13126b91a34bee2c6c1711646f7579ff80270394478fde8"
        hex"275e246c3f201a87a0dff413aa50539629ad54a9d4235208d077f08125fb4cb54be3a4b571729fdf29f1a32c02dd28a77f64686263628096329c8d76df0ede7f"
        hex"2f6655116c30a03bc47845a833e0f0d5ec2df3e226f3fd059253cc0def0aeefeca98ee5c7b7c5cade6d844295b1d19eba28ee5e648ec841403e6d94d190ee622"
        hex"2ca97b728dab6619cdf27e650ee32ac088ccfc95b429d577e98d309c62daf2d2753ab08811d0e9bd1b45f56e69393afc88b156580efafeddeeb3af4e9b264a55"
        hex"bb59e13767bac82756a8a88de632c726e567c066fd9a1415604b95904fac5c0a4ff54630c2759744a9e95200cec910ac0e3a91b6d087a819f33b422c45de1a0a"
        hex"2b02082e10de6729c21b9a7fed4c90305475b67a6ece7b25a979a49e954e0c9b208348dbaf57b78ab23f5fe830b77c29bc013d5cd9f8ccaa9413b856184c2411"
        hex"e4fa392a2a836a4ee49cc08ffba6994ce08941cc7147e5181430b2d36852912a16ad2e66f7653a356303fbca977f8e522836d87655d13aa2eecba89e2e56eeff"
        hex"eb6d1634b56270f8c99e4a1506522f3338df2a2c1382d464986a8c4c7c0f1718e6294be45fbc6894c2c28975b56df5ec38aaefaa186ae4ada0995b0c6cd85f51"
        hex"3e5e3822f222f6caf0d912f82175ad968c8bee85425bf2543678fa639275818849e65eecc3991fcb1ab1d2cbc0b941d3261fb4eb9f6e04c9893ec5bf4dd50005"
        hex"f36ca1373d6e5cddc641c589f7d0a017cf7c687db5761babf5d84e10152b24313fadf3d7d8f335f1a0981441035e75b346607baf5eb3769b0c489bec3e7c12f0"
        hex"67d9d610e486d485776167d975170087042e3736701b2ea344e6b37e49588c6928a40ef80570e0d76297f2a346a1e85ad1aff95375725dbe8dfa0c40f5ab671b"
        hex"953b38a930fd6e6370fff6b1ef46ea9ed3760ae15deab3e3d6ce9acc2778b69ffa318d82be8e70b8aa604d60ef8b6ead33728fbff72abefa08a81b0086444751"
        hex"1c5ae8fa2e6655dd2ec1f90cb974c819d4dbe132b9e834e3794aa48c29baa3202d7ebfc3b57c78444191515960dfa1a41840be00bd886185b1b56a60180c4b2e"
        hex"319691e4b924f6d03ff470cdc7b61e209e62a3a82657df037c1fae5b38bd7ac0478eafb66880ffdc35ba8c50be672afd4b7c53418e430a809d327cbc7d7d4bd4"
        hex"ce273656e5743d3ea8ec2bd16a9ab851c888b4576c5bdd9fd0e33d8091c05672c669bb058b29484a704bf0afea9898f12da2a9d277a3d808e3b3b0901963720e"
        hex"db0dd736de616aced797e1dfe01b297cb8fbcda86f3d94497f18e0e9ebbaa0bc13327be16464874592d181cab42a913666bce067c81b39713efb2383bda15edf"
        hex"91361d14a3d4598341e285b77d8098ef004e98bd274fd2daa787dc811b17e09a692084adc86a22a2e45fafa422dabb499d194934a0419497a0e43a35523deb4f"
        hex"4d94cc73ee3e84bbdbcbb036b968b2251190039467586c2dfb142ab18bd3cf553aab20db4522aed2689785b114694c4018276909e330da08300d5199a60982a6"
        hex"d5468e8928d32c1e8ad6fdc3123d9bb5156c495130979615af5c2456dca294239303b5c2ccf43a32bea0db3fd5767f86cc7ee700f79a4cd43ad50fd5376f2551"
        hex"9faefe44a56d3059435741f31774fac1a887c07ee2d9f73b5c7a357e00d80151c13ac7997d3591b854400d93327cad1a50e701ee59a6256c10ebf6a29353b191"
        hex"f634aba31129e7a0be2e5dc710210adcdd4bf6a0a5666c984f97efe1227beccdcb97698407dfd3705ac1349d7ec02803f52cc2e0c227c075ef4c06404baf0aa1"
        hex"6de766a795e91df9d612d1c68536ff5f57e463e84c9fda86ebe10858c8ffc26d39adfadb69f4493b4fe9f4cd9cc38da00e50b6e1820715f2e603d337594b29cb"
        hex"ba0623c638567ec133464cda669f9236a041d63169f1f277795810ae900bfd74f2f39d87f97e794343e4d42438d1430485a056923fd66f72ab1821fb968ada78"
        hex"d6d8af9550489c297868cd0ece82647bdb861dde28be625062c97644b12c43f23e242e15450a06dbf9b56de3a041b4a7d58c6e8133dcdbdee7a0d6ee4ee5adff"
        hex"28d32d65f63dca617150f809a1b22cad71879ce2df2424cdc23a5f0183573057fa66d1d9354535544b4e632f06f4f364db450c39bcce718b8e37349b137c44b8"
        hex"30787e4f5b15854c6728d0d0d9f4e905a6bb0dab507165be7b0aceba668dca85367165b59f51198d28d26db4466a72bf4b550dd8c07710f27b0147c25f2a17e1"
        hex"fab1176fed75d6e556bcf19b9ef61dccfa7aaf699ef57aad780cf2357c9deae2c931c5620654c649dfc8a029c1e8e3c7ba03d7010cee4542d84dbe7b213c8aea"
        hex"1a09e11fa087dcf902c6c172b7813d2ee3917d832593bbcfa0a6d1beaf2774d433f5a455a1c9dad6c191d41cba84c352a9a8e2bdd6336ab246bf86a9cbb33e64"
        hex"195a4812045d3d0baffdf1f7213ae9a1e2585d5bc750ce4886f799bb1f5eac30ba6056956ad3b39d04c612baa6ec0bc71bc7403acc36c1e77402c7aedfc48101"
        hex"171f4fa3009fcf8e4916acbcadafa58f4e3954ba0a4b037dbf8c4e75ce6b68237bb853cc02e1a55066c3e1d2ae150f0418b99f6de91faebffb1f3bb9d1f489a7"
        hex"4ff92888048f8c4ff29da4e0185ff6d00869ecad74c0e74d9aaccfdffe161918b7df292a2a9e01894695b87c281e5624d79f72db9e1a6ff9dbcd803db919349a"
        hex"982c355853817faefac0089ddd8856a5dbf14b2c9b1f4cbd715797f00e3b85366446978af95bdfcca45fe38266eb07a812170c15474fd574dcc45ab825d24995"
        hex"3bbb643883ad64f34b77355ffb61ffcb4b412c1aa6f48ac97341fc24828f82b8330fc8b26c262f31fd6b38bfe7742af8504b8e1ca52808e31ccaf79d5bac286c"
        hex"2e9c0f0528bd44118d9cf0e42f87a5e641eb5a620daf2fc16592f0abadc48d019353d6c393843aed0e8bea462c0fc624f46b67eaa1fa5f73c2973f360ee5c68d"
        hex"3472445baddc28b393b61a7e439b5712db201825f4478924364396b93873c38e04481b65de954bd2c85d373b0ae920bb78ff7e9f4ad8a85d43f09cb70857f442"
        hex"533cc4ad6caf4640c3c7f170e9bde766d67f41cf27cf1625f7cc4a4dd6d17352b2cf79f205b90434e0c87506980d05c826473fc0e7379c0d6fd94a5bd4bd8fca"
        hex"a82d7ff09fdb53371445fad6823ee4ebfea3b6a71af5554981bb70c14a43a708e1d443e6479e492cee301c02946840299c8e7635cec0622ff8a40cc6c092983e"
        hex"ccfd108b8caea4f34b5e958ff76be9b674a13ae87d0faf7fe3153f1b2b9f29ca0918f2051ac0861c1a0c55c87d6bd1ed3c1a2293149f8efa93e9bba5ff43758d"
        hex"9e3b2f69df8276cf5e7af4497e0eb34a5036627a3fcfd5bb80b315e501ab06d62755c4f31eb32b6cdfe02420d295280a59869186d93681a272d42ed51c53b954"
        hex"7debbbdd7cfb40a8772c49ce1b4734c2cf56472c2765d8ce35dbbadd538337ee19641590afcefeb5624068d0af91dd26b42ecfb8a1a6f1357ec5548edeb8d9fa"
        hex"5a12d49cfe61bef66ea32a5e9d871505b79ccb39fc400b3c752750f85da06c134130250a8be29cb97be2dd866c7c18939556e8da8f10cf6bdea78c6f722d2076"
        hex"7f74dd153630a5edc00aa0713390128166e6bdad25356e432c81050bca5b22e7a0e02ac06469301e6a2214770ffe6f4dbc9866413f4cfdc439c01b0c6ed21915"
        hex"a5ef2be1490448302e5264b1369e441f2d1345a87f94ae2fd73c6cad3b3cb9984078add9364cb0a0939f63f0c06676d93b71f98d5b311ee4ff1e34d65cdc6024"
        hex"56a2daea0f32def8bd43eca2d110c499303b7390e3507b293480506bd288f25b03a58828cb82574ac592e71d8ceab2ca3639ec95295989942daad4ad615dd255"
        hex"565d0895b80a1c7f6d147d6f0d397f690161774f7ea1e877fa0e6a01bed1a64d09296a0cf0082a7917307dc166ad75d3bd67254e7d5f93f7aeb003fad5a7dde0"
        hex"9a629b1a83b1f4fb861701e5ab48930206ab67b3ecac5624ffd66c11edf90d218145ae126b25afb7b440c07021129b325c4e114bd4005c7b0c245e8cace74905"
        hex"a57e86eb0efac8316fad6ce346ed1bffd6b55019c507edeb9276abad9912599ed3e01282fdb78471a669436e309ef9389c8a79afbdcf4c5de08518e51f3b4742"
        hex"66e6f97e346e3b41e9a5c06a61f10ed804dd6e2d956214ef10abfa642da796b2fe107d488ec754da090fc6f46044ced12c7e55b8a9f16bc842632bd13fa7985d"
        hex"35b168c2e8809d328d98c3277a326e761a18ce1462a333c6b96ee82c0bc113c3c76c02cc5f87659a44a474907cd42694dc6f9aa796fa97460419af170ce32d40"
        hex"d56e9a918d76ebd2f63c2b31911c6e4fc3485b23c91ff42903fa321f52a5bdd95c1106edfed63c7159cbd42ac5531470886ccb3d5272ab41cbe1bb30c2ffd555"
        hex"461ae1efa63394f29b2859929a3e6636cfdcc22a9c3359d9314389393b95fef29d93428f675be40d602e91b67eecf1a206eeb5b22bf27dee9b144fd7f6da7385"
        hex"f1e2ccef371e33502d36e8a9bfc06929b03336f6bfdb9fefdb046446c6e3492765b436c1a8788fb65fd0b63d7ab39b6356f5ff4554b9917de20b6dec497dc766"
        hex"387246500bb4e4ef595024a21001043699a7780fc71568691da04a14a45baaefbbdf073a46db8da036557f7ed03fd61e7d84aa2d196f59b2b3b93893e2453e22"
        hex"b19e846fc81dcb26c388b57eeb82d44f9513868e73b092c979df880b8a1b262f982fa8b4aa646bb9abf9bd4f4f42db268fdaac9fc6bb1bc1fe285019436755b2"
        hex"daf4c3986d94a9fcf5da7fdd2f22882882f255343007d975114ee94781e1784ecc93df168f7338da5bcad85a8fe9e03d88e0af623e9f51c8cfda63d67a971eef"
        hex"29e9ad19aa30620ed15bf034862d2fdddc37784cbaef674f3aac667762e68f68ba942275e561c0e665bd09e0dfc51a688b0dbe76ebaf2ffdb0cd3cb5766a64d7"
        hex"91f320f2a7bc295ca70250ed7f5a8195d423588353c10ca7e067f2d718d17c8189d07911435d2e2a55971d768ae6dd2e3e9658caa0240a04ddb2b0d3a847ef6c"
        hex"dc1003b8455cd6e107c4f64c511b1ab5ccca360be286f581bd336dbae32459830206b7629563e0c5b980a728acd96b5340a0447555907a34eb946cba51ea3e4a"
        hex"479159fddecbfe272e643b05d2d07855b48b1c43648b425b04275b763b4e44065eb5fa171b13827e3a8fc78398482977f05e4dbfba973061683061b84042dd04"
        hex"1cf22cb8cd87c5372f6c24048e54e5e870c100fd7128ee60f7819d4210f15e7577348b9890238fe8090a5c9bfe89c6f8cbee59dd4a298a868251a30c81f94631"
        hex"efff119e246af46954d3e51567da610c73cc88348e7017026fa5e87947e860b0f7289162e8934de258ceaac49e3d67b4c2def935d163066dbd23b86ec2a7fc17"
        hex"ab9c622db73de381b9da48e0729dc7103b97fbac965b6217bce52c974facb2175bfcf660dc2f2b61c9a44037779780eef75bbdf604c7ae1e21db36006d58a4da"
        hex"26560ea82475ef44f2546552df5fcd16590ddd9accfa8283ba561ca4e9371f4ba494723037c99764899e352815d1685edeaffbbd6180eef56b16d8b82185aff2"
        hex"1e018f69904b2e9bcaa791b05da33cba537482d6e606f6910f7e68ccbc22aa2de6ba4e7f98d0500371b634f8c9848991d8055cad47def7938006dd93f096f106"
        hex"e7eff66b423dddec0bf62d31077208b7e519d865fb593f8ffb6f94501bf8c46ff7cd3fb4c6d2e2249ae4b52d94afa28889fe7f068176e38478ff64e6c0e4cdcc"
        hex"a122e3a0f4c763bb3601a03c52630fa6317c45a520ea6aa6565437b376dd4b2e7673c21c6d0d600d2d4b60766b9f5ddbae32dd7b50c731b25cd821753530bdd4"
        hex"ad7230cfffa0be71f00d9055f623b28e2d2ea360c192e66464576abb7b7d694ea229201e3830e05a52a80fbecb8eb18714d6fcc367ac784f2fae6d996f9ed716"
        hex"64d706c8adfb4be90142e90cee996837370eac64a24301f122b60802750e125eeac5d3c81eb0450eb30088b8f0e486d17e96ed5472c0ae3ac8a258146e717fd6"
        hex"0d596fb6b6a040e8a11b438b93d4c7c49679bbd91728f9b81fe97a62fa945ff868ccee6934c84843a286f7fd7b0d2c3a1c70b6f254ab1f954a1bbaaa42b670e8"
        hex"b629aea6f0db752310aec800abfce04839e0567b82162049a5d03e55f98b274838e3390ad137249d5cd9f3601cf630dfa252fd1ad2af2cf8b6a632ac9b3e82ea"
        hex"aa394215bc46f5e4ea0075024c717ce220d01ae047bf6204647580c668a4e4e02dbb9bf000812119299bddf06aacb7f614ba09bd6d9a1e5ae3b189f9227c099f"
        hex"f8c1a7e718feea7bd4bcc295d777fc219967f734c2d9c0d2b971cf3b9926fcff289c4ebb3d4e172cca638c4399baec400fcbe4b68c6c5cc53ffd40c9c928655c"
        hex"bf5b2deddcbce662bae11e2e8127cf6368e67eebfdb29efbd017e79e836f1aced125c66c40fafb3206c16b8fecb46d178f3bec6fd06555a5ad0a5b6104331923"
        hex"fbe097669068539063a0e70884d04ae89fe22ebf60bcc5a80cf47f85e66fd96d41d3721e5ff7f5b415889edb17b3d616a566a025a03875ed0493905de779881e"
        hex"64afc7c690176c4842e1f43cac276bf46487a3a0a05cd47691cca4f8c4de1e309323de1a801711a699230ed7f4d4f768d0c72888d5d92ad6c55cca8afd2c6ffd"
        hex"a3074ca5f56e14fe0e63cabc6b5fdfeed9b7d93c342b0fe9d656af2d0ef76ddb28aa819c47a7fc6aa9b6511f3642a0d169ef9def7cd45919b27f852b6889357d"
        hex"d92961b119b4c9c368dce6d24986e3ce4ce8cd8d935447008ff0b122a47ee52a8a19fd283b175e2a11fa4f9c0ca5110ab12b6fde0825264312bef92b5ca7fb24"
        hex"d56dabd1cdf7e9d745f07ceb42dbbee908970d825389be2e886871eb7d075969dda145c310db32f78ee7a16cd4c70f7d4c676e1daba8f399c9e9df889fa1edeb"
        hex"446fe95377ba1c93550d25b53844802f889ae14aef805df7083596d8d66df0d32809cd7bdbc1f3e4aadbc2666af46b457292d8aca1c49b5a597ab8c8183f694c"
        hex"86e695a52381fbf17db600bf53580b220d47cef8398723946af0062bded049675548b3618e9bdcbf82f57bc9507e40bd47126ecda484e4cd9df2acdabaabe8cc"
        hex"d7d670ded674ae99c982221cb490b704e94aead898f8c6cf87a9161eece4464814050032854ad3e1c632b7f7276df1a0b2ff25cc5c1cde38de6f3246a5e3581a"
        hex"f2a8f16fe72dbae18fca48cc40a9066070a099166811cc326df0e7e222fcd0d09016397f348e1b46baf6e2680da5cb0fd65b19f07118bbd1000b65805a3da1b2"
        hex"6d31bb6bad552129a0472b8d3e0304357400f7fbe930111498a746e3214990f557be5e3925cab0b2179bbc92f7edaa3e1c12c0226b3808f9016db5f2c0e9fd79";

    // </generated:empty-subtrees>

    /// @inheritdoc IZkSyncStateTreeVerifier
    function verifyStorage(bytes32 root, address[] calldata accounts, bytes32[] calldata keys, bytes calldata proof)
        external
        view
        returns (bytes32[] memory)
    {
        if (accounts.length != keys.length) revert AccountsKeysLengthMismatch();
        bytes memory table = EMPTY_SUBTREE_HASHES;
        assembly {
            // The table must sit at 0x80 so that 0x2100+ is free scratch (see the contract's @dev).
            if iszero(eq(table, 0x80)) { revert(0, 0) }
            let rootLanes0, rootLanes1 := lanesOf(root)
            mstore(0x2340, rootLanes0)
            mstore(0x2360, rootLanes1)
            mstore(0x20a0, root)
            let p := proof.offset
            let end := add(p, proof.length)
            let n := keys.length
            mstore(0x2400, 0x20)
            mstore(0x2420, n)
            for { let i := 0 } lt(i, n) { i := add(i, 1) } {
                let value
                p, value :=
                    verifyEntry(
                    p,
                    end,
                    i,
                    calldataload(add(accounts.offset, shl(5, i))),
                    calldataload(add(keys.offset, shl(5, i)))
                )
                mstore(add(0x2440, shl(5, i)), value)
            }
            if iszero(eq(p, end)) { fail0(0x56401de4) } // MalformedStorageProof()
            return(0x2400, add(0x40, shl(5, n)))

            // ── helpers ──────────────────────────────────────────────────────────────
            function fail0(selector) {
                mstore(0, shl(224, selector))
                revert(0, 4)
            }

            function fail1(selector, arg) {
                mstore(0, shl(224, selector))
                mstore(4, arg)
                revert(0, 0x24)
            }

            /// Check the entry at `at` for (account, key) against the root (bytes at 0x20a0, lanes at 0x2340);
            /// return the next entry's offset and the proven value.
            function verifyEntry(at, limit, index, account, key) -> next, value {
                if gt(add(at, 42), limit) { fail0(0x56401de4) } // MalformedStorageProof()
                value := calldataload(at)
                let pathLen := shr(240, calldataload(add(at, 40)))
                if eq(pathLen, 0xffff) {
                    // Proven earlier by recordStorage(): compare with the stored value hash.
                    next := add(at, 42)
                    mstore(0x00, value)
                    // EntryNotRecorded(index)
                    if iszero(eq(sload(recordSlot(account, key)), keccak256(0x00, 0x20))) {
                        fail1(0x306e9eca, index)
                    }
                    leave
                }
                let leafIndex := shr(192, calldataload(add(at, 32)))
                next := add(add(at, 42), shl(5, pathLen))
                if or(gt(pathLen, 256), gt(next, limit)) { fail0(0x56401de4) }
                // NonZeroValueWithoutLeafIndex(index)
                if and(iszero(leafIndex), iszero(iszero(value))) { fail1(0x73f416e3, index) }
                // Tree key: blake2s(address left-padded to 32 bytes ‖ slot).
                spreadW(bswapWords(account), 0x2100)
                spreadW(bswapWords(key), 0x2200)
                let k0, k1 := compress(64)
                mstore(0x2380, k0)
                mstore(0x23a0, k1)
                // Leaf: blake2s(leafIndex as 8 bytes big-endian ‖ value), 40 bytes.
                spreadW(bswapWords(or(shl(192, leafIndex), shr(64, value))), 0x2100)
                spreadW(bswapWords(shl(192, value)), 0x2200)
                let h0, h1 := compress(40)
                h0, h1 := fold(h0, h1, add(at, 42), pathLen)
                // StorageProofRootMismatch(index)
                if iszero(and(eq(h0, mload(0x2340)), eq(h1, mload(0x2360)))) { fail1(0xbd7429ab, index) }
            }

            /// Storage slot of the record for (root at 0x20a0, account, key).
            function recordSlot(account, key) -> slot {
                mstore(0x20c0, account)
                mstore(0x20e0, key)
                slot := keccak256(0x20a0, 0x60)
            }

            /// Walk from the leaf (depth 0) to the root. `path` holds the siblings of depths 255 down to
            /// 256 − pathLen (root-to-leaf); deeper siblings are empty subtrees (table at 0xa0).
            function fold(leaf0, leaf1, path, pathLen) -> h0, h1 {
                h0 := leaf0
                h1 := leaf1
                for { let d := 0 } lt(d, 256) { d := add(d, 1) } {
                    // Bit d of the key (little-endian U256): word d/32 sits in lane (d/32) % 4 of the
                    // key-hash lane word for d < 128 (0x2380) or d ≥ 128 (0x23a0).
                    let bit :=
                        and(shr(add(shl(6, and(shr(5, d), 3)), and(d, 31)), mload(add(0x2380, shl(5, gt(d, 127))))), 1)
                    let sibling := mload(add(0xa0, shl(5, d)))
                    if lt(sub(255, d), pathLen) { sibling := calldataload(add(path, shl(5, sub(255, d)))) }
                    let hOff := shl(8, bit)
                    spreadLanes(h0, h1, add(0x2100, hOff))
                    spreadW(sibling, add(0x2100, xor(hOff, 0x100)))
                    h0, h1 := compress(64)
                }
            }

            // <generated:yul-helpers>
            /// Byte-reverse every 4-byte group: standard bytes <-> W-form.
            function bswapWords(x) -> y {
                y := or(
                    shr(8, and(x, 0xff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00)),
                    shl(8, and(x, 0x00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff))
                )
                y := or(
                    shr(16, and(y, 0xffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000)),
                    shl(16, and(y, 0x0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff))
                )
            }
            /// W-form word -> eight zero-padded message slots at `base`.
            function spreadW(w, base) {
                mstore(base, shr(224, w))
                mstore(add(base, 0x20), and(shr(192, w), 0xffffffff))
                mstore(add(base, 0x40), and(shr(160, w), 0xffffffff))
                mstore(add(base, 0x60), and(shr(128, w), 0xffffffff))
                mstore(add(base, 0x80), and(shr(96, w), 0xffffffff))
                mstore(add(base, 0xa0), and(shr(64, w), 0xffffffff))
                mstore(add(base, 0xc0), and(shr(32, w), 0xffffffff))
                mstore(add(base, 0xe0), and(w, 0xffffffff))
            }
            /// Lane-form hash -> eight zero-padded message slots at `base`.
            function spreadLanes(l0, l1, base) {
                mstore(base, and(l0, 0xffffffff))
                mstore(add(base, 0x20), and(shr(64, l0), 0xffffffff))
                mstore(add(base, 0x40), and(shr(128, l0), 0xffffffff))
                mstore(add(base, 0x60), shr(192, l0))
                mstore(add(base, 0x80), and(l1, 0xffffffff))
                mstore(add(base, 0xa0), and(shr(64, l1), 0xffffffff))
                mstore(add(base, 0xc0), and(shr(128, l1), 0xffffffff))
                mstore(add(base, 0xe0), shr(192, l1))
            }
            /// Standard 32-byte hash -> lane form.
            function lanesOf(x) -> l0, l1 {
                let w := bswapWords(x)
                l0 := or(
                    or(shr(224, w), shl(64, and(shr(192, w), 0xffffffff))),
                    or(shl(128, and(shr(160, w), 0xffffffff)), shl(192, and(shr(128, w), 0xffffffff)))
                )
                l1 := or(
                    or(and(shr(96, w), 0xffffffff), shl(64, and(shr(64, w), 0xffffffff))),
                    or(shl(128, and(shr(32, w), 0xffffffff)), shl(192, and(w, 0xffffffff)))
                )
            }
            /// Lane form -> standard 32-byte hash.
            function standardOf(l0, l1) -> x {
                let w :=
                    or(
                        or(shl(224, and(l0, 0xffffffff)), shl(192, and(shr(64, l0), 0xffffffff))),
                        or(shl(160, and(shr(128, l0), 0xffffffff)), shl(128, shr(192, l0)))
                    )
                w := or(
                    w,
                    or(
                        or(shl(96, and(l1, 0xffffffff)), shl(64, and(shr(64, l1), 0xffffffff))),
                        or(shl(32, and(shr(128, l1), 0xffffffff)), shr(192, l1))
                    )
                )
                x := bswapWords(w)
            }
            /// Blake2s final-block compression of the message in slots 0x2100.. (t = 64 or 40).
            function compress(t) -> o0, o1 {
                let M := 0x00000000ffffffff00000000ffffffff00000000ffffffff00000000ffffffff
                let a := 0x00000000a54ff53a000000003c6ef37200000000bb67ae85000000006b08e647
                let b := 0x000000005be0cd19000000001f83d9ab000000009b05688c00000000510e527f
                let c := 0x00000000a54ff53a000000003c6ef37200000000bb67ae85000000006a09e667
                let d := xor(0x000000005be0cd1900000000e07c2654000000009b05688c00000000510e527f, t)
                let y
                // round 0: columns; then rows 1-3 rotate left by 1, 2, 3 lanes for the diagonals
                a := and(add(add(a, b), or(or(mload(0x2100), mload(0x2148)), or(mload(0x2190), mload(0x21d8)))), M)
                d := and(shr(16, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                b := and(shr(12, mul(xor(b, c), 0x100000001)), M)
                a := and(add(add(a, b), or(or(mload(0x2120), mload(0x2168)), or(mload(0x21b0), mload(0x21f8)))), M)
                d := and(shr(8, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                y := mul(xor(b, c), 0x100000001)
                b := and(or(shr(71, y), shl(185, y)), M)
                c := or(shr(128, c), shl(128, c))
                d := or(shl(64, d), shr(192, d))
                // round 0: diagonals; then rows 1-3 rotate back
                a := and(add(add(a, b), or(or(mload(0x2200), mload(0x2248)), or(mload(0x2290), mload(0x22d8)))), M)
                d := and(shr(16, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                b := and(shr(12, mul(xor(b, c), 0x100000001)), M)
                a := and(add(add(a, b), or(or(mload(0x2220), mload(0x2268)), or(mload(0x22b0), mload(0x22f8)))), M)
                d := and(shr(8, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                y := mul(xor(b, c), 0x100000001)
                b := and(or(shl(57, y), shr(199, y)), M)
                c := or(shr(128, c), shl(128, c))
                d := or(shr(64, d), shl(192, d))
                // round 1: columns; then rows 1-3 rotate left by 1, 2, 3 lanes for the diagonals
                a := and(add(add(a, b), or(or(mload(0x22c0), mload(0x2188)), or(mload(0x2230), mload(0x22b8)))), M)
                d := and(shr(16, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                b := and(shr(12, mul(xor(b, c), 0x100000001)), M)
                a := and(add(add(a, b), or(or(mload(0x2240), mload(0x2208)), or(mload(0x22f0), mload(0x21d8)))), M)
                d := and(shr(8, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                y := mul(xor(b, c), 0x100000001)
                b := and(or(shr(71, y), shl(185, y)), M)
                c := or(shr(128, c), shl(128, c))
                d := or(shl(64, d), shr(192, d))
                // round 1: diagonals; then rows 1-3 rotate back
                a := and(add(add(a, b), or(or(mload(0x2120), mload(0x2108)), or(mload(0x2270), mload(0x21b8)))), M)
                d := and(shr(16, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                b := and(shr(12, mul(xor(b, c), 0x100000001)), M)
                a := and(add(add(a, b), or(or(mload(0x2280), mload(0x2148)), or(mload(0x21f0), mload(0x2178)))), M)
                d := and(shr(8, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                y := mul(xor(b, c), 0x100000001)
                b := and(or(shl(57, y), shr(199, y)), M)
                c := or(shr(128, c), shl(128, c))
                d := or(shr(64, d), shl(192, d))
                // round 2: columns; then rows 1-3 rotate left by 1, 2, 3 lanes for the diagonals
                a := and(add(add(a, b), or(or(mload(0x2260), mload(0x2288)), or(mload(0x21b0), mload(0x22f8)))), M)
                d := and(shr(16, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                b := and(shr(12, mul(xor(b, c), 0x100000001)), M)
                a := and(add(add(a, b), or(or(mload(0x2200), mload(0x2108)), or(mload(0x2150), mload(0x22b8)))), M)
                d := and(shr(8, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                y := mul(xor(b, c), 0x100000001)
                b := and(or(shr(71, y), shl(185, y)), M)
                c := or(shr(128, c), shl(128, c))
                d := or(shl(64, d), shr(192, d))
                // round 2: diagonals; then rows 1-3 rotate back
                a := and(add(add(a, b), or(or(mload(0x2240), mload(0x2168)), or(mload(0x21f0), mload(0x2238)))), M)
                d := and(shr(16, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                b := and(shr(12, mul(xor(b, c), 0x100000001)), M)
                a := and(add(add(a, b), or(or(mload(0x22c0), mload(0x21c8)), or(mload(0x2130), mload(0x2198)))), M)
                d := and(shr(8, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                y := mul(xor(b, c), 0x100000001)
                b := and(or(shl(57, y), shr(199, y)), M)
                c := or(shr(128, c), shl(128, c))
                d := or(shr(64, d), shl(192, d))
                // round 3: columns; then rows 1-3 rotate left by 1, 2, 3 lanes for the diagonals
                a := and(add(add(a, b), or(or(mload(0x21e0), mload(0x2168)), or(mload(0x22b0), mload(0x2278)))), M)
                d := and(shr(16, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                b := and(shr(12, mul(xor(b, c), 0x100000001)), M)
                a := and(add(add(a, b), or(or(mload(0x2220), mload(0x2128)), or(mload(0x2290), mload(0x22d8)))), M)
                d := and(shr(8, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                y := mul(xor(b, c), 0x100000001)
                b := and(or(shr(71, y), shl(185, y)), M)
                c := or(shr(128, c), shl(128, c))
                d := or(shl(64, d), shr(192, d))
                // round 3: diagonals; then rows 1-3 rotate back
                a := and(add(add(a, b), or(or(mload(0x2140), mload(0x21a8)), or(mload(0x2190), mload(0x22f8)))), M)
                d := and(shr(16, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                b := and(shr(12, mul(xor(b, c), 0x100000001)), M)
                a := and(add(add(a, b), or(or(mload(0x21c0), mload(0x2248)), or(mload(0x2110), mload(0x2218)))), M)
                d := and(shr(8, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                y := mul(xor(b, c), 0x100000001)
                b := and(or(shl(57, y), shr(199, y)), M)
                c := or(shr(128, c), shl(128, c))
                d := or(shr(64, d), shl(192, d))
                // round 4: columns; then rows 1-3 rotate left by 1, 2, 3 lanes for the diagonals
                a := and(add(add(a, b), or(or(mload(0x2220), mload(0x21a8)), or(mload(0x2150), mload(0x2258)))), M)
                d := and(shr(16, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                b := and(shr(12, mul(xor(b, c), 0x100000001)), M)
                a := and(add(add(a, b), or(or(mload(0x2100), mload(0x21e8)), or(mload(0x2190), mload(0x22f8)))), M)
                d := and(shr(8, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                y := mul(xor(b, c), 0x100000001)
                b := and(or(shr(71, y), shl(185, y)), M)
                c := or(shr(128, c), shl(128, c))
                d := or(shl(64, d), shr(192, d))
                // round 4: diagonals; then rows 1-3 rotate back
                a := and(add(add(a, b), or(or(mload(0x22c0), mload(0x2268)), or(mload(0x21d0), mload(0x2178)))), M)
                d := and(shr(16, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                b := and(shr(12, mul(xor(b, c), 0x100000001)), M)
                a := and(add(add(a, b), or(or(mload(0x2120), mload(0x2288)), or(mload(0x2210), mload(0x22b8)))), M)
                d := and(shr(8, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                y := mul(xor(b, c), 0x100000001)
                b := and(or(shl(57, y), shr(199, y)), M)
                c := or(shr(128, c), shl(128, c))
                d := or(shr(64, d), shl(192, d))
                // round 5: columns; then rows 1-3 rotate left by 1, 2, 3 lanes for the diagonals
                a := and(add(add(a, b), or(or(mload(0x2140), mload(0x21c8)), or(mload(0x2110), mload(0x2218)))), M)
                d := and(shr(16, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                b := and(shr(12, mul(xor(b, c), 0x100000001)), M)
                a := and(add(add(a, b), or(or(mload(0x2280), mload(0x2248)), or(mload(0x2270), mload(0x2178)))), M)
                d := and(shr(8, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                y := mul(xor(b, c), 0x100000001)
                b := and(or(shr(71, y), shl(185, y)), M)
                c := or(shr(128, c), shl(128, c))
                d := or(shl(64, d), shr(192, d))
                // round 5: diagonals; then rows 1-3 rotate back
                a := and(add(add(a, b), or(or(mload(0x2180), mload(0x21e8)), or(mload(0x22f0), mload(0x2138)))), M)
                d := and(shr(16, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                b := and(shr(12, mul(xor(b, c), 0x100000001)), M)
                a := and(add(add(a, b), or(or(mload(0x22a0), mload(0x21a8)), or(mload(0x22d0), mload(0x2238)))), M)
                d := and(shr(8, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                y := mul(xor(b, c), 0x100000001)
                b := and(or(shl(57, y), shr(199, y)), M)
                c := or(shr(128, c), shl(128, c))
                d := or(shr(64, d), shl(192, d))
                // round 6: columns; then rows 1-3 rotate left by 1, 2, 3 lanes for the diagonals
                a := and(add(add(a, b), or(or(mload(0x2280), mload(0x2128)), or(mload(0x22d0), mload(0x2198)))), M)
                d := and(shr(16, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                b := and(shr(12, mul(xor(b, c), 0x100000001)), M)
                a := and(add(add(a, b), or(or(mload(0x21a0), mload(0x22e8)), or(mload(0x22b0), mload(0x2258)))), M)
                d := and(shr(8, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                y := mul(xor(b, c), 0x100000001)
                b := and(or(shr(71, y), shl(185, y)), M)
                c := or(shr(128, c), shl(128, c))
                d := or(shl(64, d), shr(192, d))
                // round 6: diagonals; then rows 1-3 rotate back
                a := and(add(add(a, b), or(or(mload(0x2100), mload(0x21c8)), or(mload(0x2230), mload(0x2218)))), M)
                d := and(shr(16, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                b := and(shr(12, mul(xor(b, c), 0x100000001)), M)
                a := and(add(add(a, b), or(or(mload(0x21e0), mload(0x2168)), or(mload(0x2150), mload(0x2278)))), M)
                d := and(shr(8, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                y := mul(xor(b, c), 0x100000001)
                b := and(or(shl(57, y), shr(199, y)), M)
                c := or(shr(128, c), shl(128, c))
                d := or(shr(64, d), shl(192, d))
                // round 7: columns; then rows 1-3 rotate left by 1, 2, 3 lanes for the diagonals
                a := and(add(add(a, b), or(or(mload(0x22a0), mload(0x21e8)), or(mload(0x2290), mload(0x2178)))), M)
                d := and(shr(16, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                b := and(shr(12, mul(xor(b, c), 0x100000001)), M)
                a := and(add(add(a, b), or(or(mload(0x2260), mload(0x22c8)), or(mload(0x2130), mload(0x2238)))), M)
                d := and(shr(8, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                y := mul(xor(b, c), 0x100000001)
                b := and(or(shr(71, y), shl(185, y)), M)
                c := or(shr(128, c), shl(128, c))
                d := or(shl(64, d), shr(192, d))
                // round 7: diagonals; then rows 1-3 rotate back
                a := and(add(add(a, b), or(or(mload(0x21a0), mload(0x22e8)), or(mload(0x2210), mload(0x2158)))), M)
                d := and(shr(16, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                b := and(shr(12, mul(xor(b, c), 0x100000001)), M)
                a := and(add(add(a, b), or(or(mload(0x2100), mload(0x2188)), or(mload(0x21d0), mload(0x2258)))), M)
                d := and(shr(8, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                y := mul(xor(b, c), 0x100000001)
                b := and(or(shl(57, y), shr(199, y)), M)
                c := or(shr(128, c), shl(128, c))
                d := or(shr(64, d), shl(192, d))
                // round 8: columns; then rows 1-3 rotate left by 1, 2, 3 lanes for the diagonals
                a := and(add(add(a, b), or(or(mload(0x21c0), mload(0x22c8)), or(mload(0x2270), mload(0x2118)))), M)
                d := and(shr(16, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                b := and(shr(12, mul(xor(b, c), 0x100000001)), M)
                a := and(add(add(a, b), or(or(mload(0x22e0), mload(0x2228)), or(mload(0x2170), mload(0x2218)))), M)
                d := and(shr(8, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                y := mul(xor(b, c), 0x100000001)
                b := and(or(shr(71, y), shl(185, y)), M)
                c := or(shr(128, c), shl(128, c))
                d := or(shl(64, d), shr(192, d))
                // round 8: diagonals; then rows 1-3 rotate back
                a := and(add(add(a, b), or(or(mload(0x2280), mload(0x22a8)), or(mload(0x2130), mload(0x2258)))), M)
                d := and(shr(16, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                b := and(shr(12, mul(xor(b, c), 0x100000001)), M)
                a := and(add(add(a, b), or(or(mload(0x2140), mload(0x21e8)), or(mload(0x2190), mload(0x21b8)))), M)
                d := and(shr(8, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                y := mul(xor(b, c), 0x100000001)
                b := and(or(shl(57, y), shr(199, y)), M)
                c := or(shr(128, c), shl(128, c))
                d := or(shr(64, d), shl(192, d))
                // round 9: columns; then rows 1-3 rotate left by 1, 2, 3 lanes for the diagonals
                a := and(add(add(a, b), or(or(mload(0x2240), mload(0x2208)), or(mload(0x21f0), mload(0x2138)))), M)
                d := and(shr(16, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                b := and(shr(12, mul(xor(b, c), 0x100000001)), M)
                a := and(add(add(a, b), or(or(mload(0x2140), mload(0x2188)), or(mload(0x21d0), mload(0x21b8)))), M)
                d := and(shr(8, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                y := mul(xor(b, c), 0x100000001)
                b := and(or(shr(71, y), shl(185, y)), M)
                c := or(shr(128, c), shl(128, c))
                d := or(shl(64, d), shr(192, d))
                // round 9: diagonals; then rows 1-3 rotate back
                a := and(add(add(a, b), or(or(mload(0x22e0), mload(0x2228)), or(mload(0x2170), mload(0x22b8)))), M)
                d := and(shr(16, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                b := and(shr(12, mul(xor(b, c), 0x100000001)), M)
                a := and(add(add(a, b), or(or(mload(0x2260), mload(0x22c8)), or(mload(0x2290), mload(0x2118)))), M)
                d := and(shr(8, mul(xor(d, a), 0x100000001)), M)
                c := and(add(c, d), M)
                y := mul(xor(b, c), 0x100000001)
                b := and(or(shl(57, y), shr(199, y)), M)
                c := or(shr(128, c), shl(128, c))
                d := or(shr(64, d), shl(192, d))
                o0 := xor(xor(a, c), 0x00000000a54ff53a000000003c6ef37200000000bb67ae85000000006b08e647)
                o1 := xor(xor(b, d), 0x000000005be0cd19000000001f83d9ab000000009b05688c00000000510e527f)
            }
            // </generated:yul-helpers>
        }
    }

    /// @inheritdoc IZkSyncStateTreeVerifier
    /// @dev Anyone may call it: a record is a fact about `root` alone, and a bundle still has to
    ///      authenticate `root` itself (an executed batch on L1). Relayers use it to split one bundle's
    ///      tree proofs across transactions.
    function recordStorage(bytes32 root, address[] calldata accounts, bytes32[] calldata keys, bytes calldata proof)
        external
        returns (bytes32[] memory values)
    {
        // A fresh call frame: verifyStorage owns its memory.
        values = this.verifyStorage(root, accounts, keys, proof);
        for (uint256 i = 0; i < values.length; i++) {
            bytes32 slot = _recordSlot(root, accounts[i], keys[i]);
            bytes32 valueHash = keccak256(abi.encode(values[i]));
            assembly ("memory-safe") {
                sstore(slot, valueHash)
            }
            emit StorageRecorded(root, accounts[i], keys[i], values[i]);
        }
    }

    /// @inheritdoc IZkSyncStateTreeVerifier
    function recordedValueHash(bytes32 root, address account, bytes32 key) external view returns (bytes32 valueHash) {
        bytes32 slot = _recordSlot(root, account, key);
        assembly ("memory-safe") {
            valueHash := sload(slot)
        }
    }

    function _recordSlot(bytes32 root, address account, bytes32 key) private pure returns (bytes32) {
        return keccak256(abi.encode(root, account, key));
    }
}
