// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.28;

/// @title Sha256Midstate
/// @notice SHA-256 that can resume from a chaining state ("midstate"). The SHA-256 precompile only
///         hashes complete messages, but Rootstock's merged-mining proof ships the Bitcoin coinbase
///         as `byteCount ‖ midstate ‖ tail`: the first `byteCount` bytes are already compressed into
///         the midstate and only the tail is public. Resuming from that state is the only way to
///         recompute the coinbase txid (RSKj `ProofOfWorkRule.isValid`).
/// @dev Generated by script/gen/gen_sha.py (edit the generator). Same structure as {Sha512t256}:
///      one round per iteration over a rolling memory buffer, rotations as shifts of `x ‖ x`.
library Sha256Midstate {
    /// @dev SHA-256 initial hash value H(0), packed H0‖…‖H7 (big-endian words).
    bytes32 internal constant IV = 0x6a09e667bb67ae853c6ef372a54ff53a510e527f9b05688c1f83d9ab5be0cd19;

    error Sha256BadByteCount();

    /// @notice Finish a SHA-256 computation: `state` is the chaining value after `byteCount` bytes
    ///         (a multiple of 64), `tail` the remaining message bytes. Returns the digest.
    function resume(bytes32 state, uint256 byteCount, bytes memory tail) internal pure returns (bytes32 out) {
        if (byteCount % 64 != 0 || byteCount > type(uint64).max / 8 - tail.length) revert Sha256BadByteCount();
        assembly ("memory-safe") {
            // Scratch: W[64] | K[64] | V[72] | state[8] | tail[128 B]
            function compress(blk, w) {
                let M := 0xffffffff
                for { let i := 0 } lt(i, 16) { i := add(i, 1) } {
                    mstore(add(w, shl(5, i)), shr(224, mload(add(blk, mul(i, 4)))))
                }
                for { let q := add(w, 0x200) } lt(q, add(w, 0x800)) { q := add(q, 0x20) } {
                    let x := mload(sub(q, 0x1e0)) // W[i-15]
                    let y := mload(sub(q, 0x40)) // W[i-2]
                    let s0 := xor(xor(shr(7, or(x, shl(32, x))), shr(18, or(x, shl(32, x)))), shr(3, x))
                    let s1 := xor(xor(shr(17, or(y, shl(32, y))), shr(19, or(y, shl(32, y)))), shr(10, y))
                    mstore(q, and(add(add(s0, s1), add(mload(sub(q, 0xe0)), mload(sub(q, 0x200)))), M))
                }
                // V[0..7] = h, g, f, e, d, c, b, a (the chaining state, reversed)
                let v := add(w, 0x1000)
                let st := add(v, 0x900)
                for { let i := 0 } lt(i, 8) { i := add(i, 1) } {
                    mstore(add(v, shl(5, i)), mload(add(st, shl(5, sub(7, i)))))
                }
                for { let i := 0 } lt(i, 64) { i := add(i, 1) } {
                    let p := add(v, shl(5, i))
                    let t1 := 0
                    {
                        let e := mload(add(p, 0x60))
                        let f := mload(add(p, 0x40))
                        let g := mload(add(p, 0x20))
                        let ee := or(e, shl(32, e))
                        t1 := add(
                            add(mload(p), xor(xor(shr(6, ee), shr(11, ee)), shr(25, ee))),
                            add(
                                xor(g, and(e, xor(f, g))),
                                add(mload(add(w, shl(5, i))), mload(add(w, add(0x800, shl(5, i)))))
                            )
                        )
                    }
                    mstore(add(p, 0x80), and(add(mload(add(p, 0x80)), t1), M))
                    let a := mload(add(p, 0xe0))
                    let b := mload(add(p, 0xc0))
                    let c := mload(add(p, 0xa0))
                    let aa := or(a, shl(32, a))
                    mstore(
                        add(p, 0x100),
                        and(
                            add(
                                t1,
                                add(xor(xor(shr(2, aa), shr(13, aa)), shr(22, aa)), or(and(a, b), and(c, or(a, b))))
                            ),
                            M
                        )
                    )
                }
                // After the last round V[rounds..rounds+7] = h, g, f, e, d, c, b, a.
                let last := add(v, 0x800)
                for { let i := 0 } lt(i, 8) { i := add(i, 1) } {
                    let sp := add(st, shl(5, i))
                    mstore(sp, and(add(mload(sp), mload(add(last, shl(5, sub(7, i))))), M))
                }
            }

            let w := mload(0x40)
            mstore(add(w, 0x800), 0x428a2f98)
            mstore(add(w, 0x820), 0x71374491)
            mstore(add(w, 0x840), 0xb5c0fbcf)
            mstore(add(w, 0x860), 0xe9b5dba5)
            mstore(add(w, 0x880), 0x3956c25b)
            mstore(add(w, 0x8a0), 0x59f111f1)
            mstore(add(w, 0x8c0), 0x923f82a4)
            mstore(add(w, 0x8e0), 0xab1c5ed5)
            mstore(add(w, 0x900), 0xd807aa98)
            mstore(add(w, 0x920), 0x12835b01)
            mstore(add(w, 0x940), 0x243185be)
            mstore(add(w, 0x960), 0x550c7dc3)
            mstore(add(w, 0x980), 0x72be5d74)
            mstore(add(w, 0x9a0), 0x80deb1fe)
            mstore(add(w, 0x9c0), 0x9bdc06a7)
            mstore(add(w, 0x9e0), 0xc19bf174)
            mstore(add(w, 0xa00), 0xe49b69c1)
            mstore(add(w, 0xa20), 0xefbe4786)
            mstore(add(w, 0xa40), 0x0fc19dc6)
            mstore(add(w, 0xa60), 0x240ca1cc)
            mstore(add(w, 0xa80), 0x2de92c6f)
            mstore(add(w, 0xaa0), 0x4a7484aa)
            mstore(add(w, 0xac0), 0x5cb0a9dc)
            mstore(add(w, 0xae0), 0x76f988da)
            mstore(add(w, 0xb00), 0x983e5152)
            mstore(add(w, 0xb20), 0xa831c66d)
            mstore(add(w, 0xb40), 0xb00327c8)
            mstore(add(w, 0xb60), 0xbf597fc7)
            mstore(add(w, 0xb80), 0xc6e00bf3)
            mstore(add(w, 0xba0), 0xd5a79147)
            mstore(add(w, 0xbc0), 0x06ca6351)
            mstore(add(w, 0xbe0), 0x14292967)
            mstore(add(w, 0xc00), 0x27b70a85)
            mstore(add(w, 0xc20), 0x2e1b2138)
            mstore(add(w, 0xc40), 0x4d2c6dfc)
            mstore(add(w, 0xc60), 0x53380d13)
            mstore(add(w, 0xc80), 0x650a7354)
            mstore(add(w, 0xca0), 0x766a0abb)
            mstore(add(w, 0xcc0), 0x81c2c92e)
            mstore(add(w, 0xce0), 0x92722c85)
            mstore(add(w, 0xd00), 0xa2bfe8a1)
            mstore(add(w, 0xd20), 0xa81a664b)
            mstore(add(w, 0xd40), 0xc24b8b70)
            mstore(add(w, 0xd60), 0xc76c51a3)
            mstore(add(w, 0xd80), 0xd192e819)
            mstore(add(w, 0xda0), 0xd6990624)
            mstore(add(w, 0xdc0), 0xf40e3585)
            mstore(add(w, 0xde0), 0x106aa070)
            mstore(add(w, 0xe00), 0x19a4c116)
            mstore(add(w, 0xe20), 0x1e376c08)
            mstore(add(w, 0xe40), 0x2748774c)
            mstore(add(w, 0xe60), 0x34b0bcb5)
            mstore(add(w, 0xe80), 0x391c0cb3)
            mstore(add(w, 0xea0), 0x4ed8aa4a)
            mstore(add(w, 0xec0), 0x5b9cca4f)
            mstore(add(w, 0xee0), 0x682e6ff3)
            mstore(add(w, 0xf00), 0x748f82ee)
            mstore(add(w, 0xf20), 0x78a5636f)
            mstore(add(w, 0xf40), 0x84c87814)
            mstore(add(w, 0xf60), 0x8cc70208)
            mstore(add(w, 0xf80), 0x90befffa)
            mstore(add(w, 0xfa0), 0xa4506ceb)
            mstore(add(w, 0xfc0), 0xbef9a3f7)
            mstore(add(w, 0xfe0), 0xc67178f2)
            let s := add(w, 0x1900)
            for { let i := 0 } lt(i, 8) { i := add(i, 1) } {
                mstore(add(s, shl(5, i)), and(shr(sub(224, shl(5, i)), state), 0xffffffff))
            }
            let len := mload(tail)
            let src := add(tail, 0x20)
            let full := and(len, not(63))
            for { let off := 0 } lt(off, full) { off := add(off, 64) } {
                compress(add(src, off), w)
            }
            let t := add(s, 0x100)
            for { let i := 0 } lt(i, 0x80) { i := add(i, 0x20) } {
                mstore(add(t, i), 0)
            }
            let rem := sub(len, full)
            mcopy(t, add(src, full), rem)
            mstore8(add(t, rem), 0x80)
            let tl := 64
            if gt(rem, 55) { tl := 128 }
            // 64-bit big-endian bit length of the WHOLE message (midstate bytes included).
            mstore(add(t, sub(tl, 0x20)), or(mload(add(t, sub(tl, 0x20))), shl(3, add(byteCount, len))))
            compress(t, w)
            if eq(tl, 128) { compress(add(t, 64), w) }
            for { let i := 0 } lt(i, 8) { i := add(i, 1) } {
                out := or(out, shl(sub(224, shl(5, i)), mload(add(s, shl(5, i)))))
            }
        }
    }
}
