// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.28;

/// @title Sha512t256
/// @notice SHA-512/256 (FIPS 180-4 §5.3.6.2): the SHA-512 compression function with its own initial
///         hash value, truncated to the first 256 bits. Stacks uses it for block hashes, the signer
///         signature hash, index block ids and every MARF node hash.
/// @dev Generated by script/gen/gen_sha.py (edit the generator). One round per loop iteration with the
///      working variables in a rolling memory buffer (round i reads V[i..i+7], writes V[i+4] and
///      V[i+8]); a 64-bit rotation is one shift of the doubled word `x ‖ x`. K, W and V live in
///      unreserved scratch memory past the free-memory pointer. A fully unrolled variant was tried
///      and abandoned: solc via-IR needed more than 10 GB to compile it.
library Sha512t256 {
    function hash(bytes memory data) internal pure returns (bytes32 out) {
        assembly ("memory-safe") {
            // Scratch: W[80] | K[80] | V[88] | state[8] | tail[256 B]
            function compress(blk, w) {
                let M := 0xffffffffffffffff
                for { let i := 0 } lt(i, 16) { i := add(i, 1) } {
                    mstore(add(w, shl(5, i)), shr(192, mload(add(blk, mul(i, 8)))))
                }
                for { let q := add(w, 0x200) } lt(q, add(w, 0xa00)) { q := add(q, 0x20) } {
                    let x := mload(sub(q, 0x1e0)) // W[i-15]
                    let y := mload(sub(q, 0x40)) // W[i-2]
                    let s0 := xor(xor(shr(1, or(x, shl(64, x))), shr(8, or(x, shl(64, x)))), shr(7, x))
                    let s1 := xor(xor(shr(19, or(y, shl(64, y))), shr(61, or(y, shl(64, y)))), shr(6, y))
                    mstore(q, and(add(add(s0, s1), add(mload(sub(q, 0xe0)), mload(sub(q, 0x200)))), M))
                }
                // V[0..7] = h, g, f, e, d, c, b, a (the chaining state, reversed)
                let v := add(w, 0x1400)
                let st := add(v, 0xb00)
                for { let i := 0 } lt(i, 8) { i := add(i, 1) } {
                    mstore(add(v, shl(5, i)), mload(add(st, shl(5, sub(7, i)))))
                }
                for { let i := 0 } lt(i, 80) { i := add(i, 1) } {
                    let p := add(v, shl(5, i))
                    let t1 := 0
                    {
                        let e := mload(add(p, 0x60))
                        let f := mload(add(p, 0x40))
                        let g := mload(add(p, 0x20))
                        let ee := or(e, shl(64, e))
                        t1 := add(
                            add(mload(p), xor(xor(shr(14, ee), shr(18, ee)), shr(41, ee))),
                            add(
                                xor(g, and(e, xor(f, g))),
                                add(mload(add(w, shl(5, i))), mload(add(w, add(0xa00, shl(5, i)))))
                            )
                        )
                    }
                    mstore(add(p, 0x80), and(add(mload(add(p, 0x80)), t1), M))
                    let a := mload(add(p, 0xe0))
                    let b := mload(add(p, 0xc0))
                    let c := mload(add(p, 0xa0))
                    let aa := or(a, shl(64, a))
                    mstore(
                        add(p, 0x100),
                        and(
                            add(
                                t1,
                                add(xor(xor(shr(28, aa), shr(34, aa)), shr(39, aa)), or(and(a, b), and(c, or(a, b))))
                            ),
                            M
                        )
                    )
                }
                // After the last round V[rounds..rounds+7] = h, g, f, e, d, c, b, a.
                let last := add(v, 0xa00)
                for { let i := 0 } lt(i, 8) { i := add(i, 1) } {
                    let sp := add(st, shl(5, i))
                    mstore(sp, and(add(mload(sp), mload(add(last, shl(5, sub(7, i))))), M))
                }
            }

            let w := mload(0x40)
            mstore(add(w, 0xa00), 0x428a2f98d728ae22)
            mstore(add(w, 0xa20), 0x7137449123ef65cd)
            mstore(add(w, 0xa40), 0xb5c0fbcfec4d3b2f)
            mstore(add(w, 0xa60), 0xe9b5dba58189dbbc)
            mstore(add(w, 0xa80), 0x3956c25bf348b538)
            mstore(add(w, 0xaa0), 0x59f111f1b605d019)
            mstore(add(w, 0xac0), 0x923f82a4af194f9b)
            mstore(add(w, 0xae0), 0xab1c5ed5da6d8118)
            mstore(add(w, 0xb00), 0xd807aa98a3030242)
            mstore(add(w, 0xb20), 0x12835b0145706fbe)
            mstore(add(w, 0xb40), 0x243185be4ee4b28c)
            mstore(add(w, 0xb60), 0x550c7dc3d5ffb4e2)
            mstore(add(w, 0xb80), 0x72be5d74f27b896f)
            mstore(add(w, 0xba0), 0x80deb1fe3b1696b1)
            mstore(add(w, 0xbc0), 0x9bdc06a725c71235)
            mstore(add(w, 0xbe0), 0xc19bf174cf692694)
            mstore(add(w, 0xc00), 0xe49b69c19ef14ad2)
            mstore(add(w, 0xc20), 0xefbe4786384f25e3)
            mstore(add(w, 0xc40), 0x0fc19dc68b8cd5b5)
            mstore(add(w, 0xc60), 0x240ca1cc77ac9c65)
            mstore(add(w, 0xc80), 0x2de92c6f592b0275)
            mstore(add(w, 0xca0), 0x4a7484aa6ea6e483)
            mstore(add(w, 0xcc0), 0x5cb0a9dcbd41fbd4)
            mstore(add(w, 0xce0), 0x76f988da831153b5)
            mstore(add(w, 0xd00), 0x983e5152ee66dfab)
            mstore(add(w, 0xd20), 0xa831c66d2db43210)
            mstore(add(w, 0xd40), 0xb00327c898fb213f)
            mstore(add(w, 0xd60), 0xbf597fc7beef0ee4)
            mstore(add(w, 0xd80), 0xc6e00bf33da88fc2)
            mstore(add(w, 0xda0), 0xd5a79147930aa725)
            mstore(add(w, 0xdc0), 0x06ca6351e003826f)
            mstore(add(w, 0xde0), 0x142929670a0e6e70)
            mstore(add(w, 0xe00), 0x27b70a8546d22ffc)
            mstore(add(w, 0xe20), 0x2e1b21385c26c926)
            mstore(add(w, 0xe40), 0x4d2c6dfc5ac42aed)
            mstore(add(w, 0xe60), 0x53380d139d95b3df)
            mstore(add(w, 0xe80), 0x650a73548baf63de)
            mstore(add(w, 0xea0), 0x766a0abb3c77b2a8)
            mstore(add(w, 0xec0), 0x81c2c92e47edaee6)
            mstore(add(w, 0xee0), 0x92722c851482353b)
            mstore(add(w, 0xf00), 0xa2bfe8a14cf10364)
            mstore(add(w, 0xf20), 0xa81a664bbc423001)
            mstore(add(w, 0xf40), 0xc24b8b70d0f89791)
            mstore(add(w, 0xf60), 0xc76c51a30654be30)
            mstore(add(w, 0xf80), 0xd192e819d6ef5218)
            mstore(add(w, 0xfa0), 0xd69906245565a910)
            mstore(add(w, 0xfc0), 0xf40e35855771202a)
            mstore(add(w, 0xfe0), 0x106aa07032bbd1b8)
            mstore(add(w, 0x1000), 0x19a4c116b8d2d0c8)
            mstore(add(w, 0x1020), 0x1e376c085141ab53)
            mstore(add(w, 0x1040), 0x2748774cdf8eeb99)
            mstore(add(w, 0x1060), 0x34b0bcb5e19b48a8)
            mstore(add(w, 0x1080), 0x391c0cb3c5c95a63)
            mstore(add(w, 0x10a0), 0x4ed8aa4ae3418acb)
            mstore(add(w, 0x10c0), 0x5b9cca4f7763e373)
            mstore(add(w, 0x10e0), 0x682e6ff3d6b2b8a3)
            mstore(add(w, 0x1100), 0x748f82ee5defb2fc)
            mstore(add(w, 0x1120), 0x78a5636f43172f60)
            mstore(add(w, 0x1140), 0x84c87814a1f0ab72)
            mstore(add(w, 0x1160), 0x8cc702081a6439ec)
            mstore(add(w, 0x1180), 0x90befffa23631e28)
            mstore(add(w, 0x11a0), 0xa4506cebde82bde9)
            mstore(add(w, 0x11c0), 0xbef9a3f7b2c67915)
            mstore(add(w, 0x11e0), 0xc67178f2e372532b)
            mstore(add(w, 0x1200), 0xca273eceea26619c)
            mstore(add(w, 0x1220), 0xd186b8c721c0c207)
            mstore(add(w, 0x1240), 0xeada7dd6cde0eb1e)
            mstore(add(w, 0x1260), 0xf57d4f7fee6ed178)
            mstore(add(w, 0x1280), 0x06f067aa72176fba)
            mstore(add(w, 0x12a0), 0x0a637dc5a2c898a6)
            mstore(add(w, 0x12c0), 0x113f9804bef90dae)
            mstore(add(w, 0x12e0), 0x1b710b35131c471b)
            mstore(add(w, 0x1300), 0x28db77f523047d84)
            mstore(add(w, 0x1320), 0x32caab7b40c72493)
            mstore(add(w, 0x1340), 0x3c9ebe0a15c9bebc)
            mstore(add(w, 0x1360), 0x431d67c49c100d4c)
            mstore(add(w, 0x1380), 0x4cc5d4becb3e42b6)
            mstore(add(w, 0x13a0), 0x597f299cfc657e2a)
            mstore(add(w, 0x13c0), 0x5fcb6fab3ad6faec)
            mstore(add(w, 0x13e0), 0x6c44198c4a475817)
            let s := add(w, 0x1f00)
            mstore(s, 0x22312194fc2bf72c)
            mstore(add(s, 0x20), 0x9f555fa3c84c64c2)
            mstore(add(s, 0x40), 0x2393b86b6f53b151)
            mstore(add(s, 0x60), 0x963877195940eabd)
            mstore(add(s, 0x80), 0x96283ee2a88effe3)
            mstore(add(s, 0xa0), 0xbe5e1e2553863992)
            mstore(add(s, 0xc0), 0x2b0199fc2c85b8aa)
            mstore(add(s, 0xe0), 0x0eb72ddc81c52ca2)

            let len := mload(data)
            let src := add(data, 0x20)
            let full := and(len, not(127))
            for { let off := 0 } lt(off, full) { off := add(off, 128) } {
                compress(add(src, off), w)
            }
            // Tail: the remaining (len mod 128) bytes, 0x80, zero padding and the 128-bit bit length.
            let t := add(s, 0x100)
            for { let i := 0 } lt(i, 0x100) { i := add(i, 0x20) } {
                mstore(add(t, i), 0)
            }
            let rem := sub(len, full)
            mcopy(t, add(src, full), rem)
            mstore8(add(t, rem), 0x80)
            let tl := 128
            if gt(rem, 111) { tl := 256 }
            mstore(add(t, sub(tl, 0x20)), or(mload(add(t, sub(tl, 0x20))), shl(3, len)))
            compress(t, w)
            if eq(tl, 256) { compress(add(t, 128), w) }
            out := or(
                or(shl(192, mload(s)), shl(128, mload(add(s, 0x20)))),
                or(shl(64, mload(add(s, 0x40))), mload(add(s, 0x60)))
            )
        }
    }
}
