// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.28;

// AUTO-GENERATED by test/e2e/relay/algorand/codegen/keccak.ts — do not edit by hand.

/// @title ClprShake256Engine
/// @notice Stand-alone SHAKE256 engine (FIPS 202: Keccak-f[1600], rate 136 bytes, domain padding
///         0x1F … 0x80). The KECCAK256 opcode cannot be used: it fixes the Keccak padding and the output
///         length. Algorand uses SHAKE256 for the state-proof coins and for Falcon's hash-to-point.
///         Like {ClprBlake2sHasher}, the contract owns its memory (lanes at fixed addresses), which keeps
///         the unrolled rounds out of the via-IR stack-to-memory mover. Called with `staticcall`.
///
///         Calldata `0x01 ‖ outLen (u32 BE) ‖ data` returns SHAKE256(data) truncated to `outLen` bytes.
///         Calldata `0x02 ‖ data` returns Falcon `HashToPoint` (n = 1024, q = 12289; the
///         falcon `hash_to_point_vartime` rejection rule `w < 61445 → w mod q` on big-endian 16-bit
///         words): 1,024 coefficients, one per 32-byte word.
/// @dev Memory map: 0x000 lanes A[25] · 0x320 B[25] · 0x640 C[5] · 0x6e0 D[5] · 0x780 the four array
///      bases · 0x800 input · output after input.
contract ClprShake256Engine {
    fallback() external {
        assembly {
            function rc(i) -> c {
                switch i
                case 0 { c := 0x1 }
                case 1 { c := 0x8082 }
                case 2 { c := 0x800000000000808a }
                case 3 { c := 0x8000000080008000 }
                case 4 { c := 0x808b }
                case 5 { c := 0x80000001 }
                case 6 { c := 0x8000000080008081 }
                case 7 { c := 0x8000000000008009 }
                case 8 { c := 0x8a }
                case 9 { c := 0x88 }
                case 10 { c := 0x80008009 }
                case 11 { c := 0x8000000a }
                case 12 { c := 0x8000808b }
                case 13 { c := 0x800000000000008b }
                case 14 { c := 0x8000000000008089 }
                case 15 { c := 0x8000000000008003 }
                case 16 { c := 0x8000000000008002 }
                case 17 { c := 0x8000000000000080 }
                case 18 { c := 0x800a }
                case 19 { c := 0x800000008000000a }
                case 20 { c := 0x8000000080008081 }
                case 21 { c := 0x8000000000008080 }
                case 22 { c := 0x80000001 }
                default { c := 0x8000000080008008 }
            }
            // The lane, scratch, C and D arrays are addressed through bases read from memory (0x780…0x7e0),
            // so the optimizer cannot prove a store to one array leaves the others unchanged and does not
            // forward stored lanes into expressions with more live values than the stack holds.
            function permute() {
                for { let i := 0 } lt(i, 24) { i := add(i, 1) } {
                    let pA := mload(0x780)
                    let pB := mload(0x7a0)
                    let pC := mload(0x7c0)
                    let pD := mload(0x7e0)
                    mstore(
                        pC,
                        xor(
                            xor(xor(xor(mload(pA), mload(add(pA, 160))), mload(add(pA, 320))), mload(add(pA, 480))),
                            mload(add(pA, 640))
                        )
                    )
                    mstore(
                        add(pC, 32),
                        xor(
                            xor(
                                xor(xor(mload(add(pA, 32)), mload(add(pA, 192))), mload(add(pA, 352))),
                                mload(add(pA, 512))
                            ),
                            mload(add(pA, 672))
                        )
                    )
                    mstore(
                        add(pC, 64),
                        xor(
                            xor(
                                xor(xor(mload(add(pA, 64)), mload(add(pA, 224))), mload(add(pA, 384))),
                                mload(add(pA, 544))
                            ),
                            mload(add(pA, 704))
                        )
                    )
                    mstore(
                        add(pC, 96),
                        xor(
                            xor(
                                xor(xor(mload(add(pA, 96)), mload(add(pA, 256))), mload(add(pA, 416))),
                                mload(add(pA, 576))
                            ),
                            mload(add(pA, 736))
                        )
                    )
                    mstore(
                        add(pC, 128),
                        xor(
                            xor(
                                xor(xor(mload(add(pA, 128)), mload(add(pA, 288))), mload(add(pA, 448))),
                                mload(add(pA, 608))
                            ),
                            mload(add(pA, 768))
                        )
                    )
                    {
                        let c := mload(add(pC, 32))
                        mstore(pD, xor(mload(add(pC, 128)), and(or(shl(1, c), shr(63, c)), 0xffffffffffffffff)))
                    }
                    {
                        let c := mload(add(pC, 64))
                        mstore(add(pD, 32), xor(mload(pC), and(or(shl(1, c), shr(63, c)), 0xffffffffffffffff)))
                    }
                    {
                        let c := mload(add(pC, 96))
                        mstore(add(pD, 64), xor(mload(add(pC, 32)), and(or(shl(1, c), shr(63, c)), 0xffffffffffffffff)))
                    }
                    {
                        let c := mload(add(pC, 128))
                        mstore(add(pD, 96), xor(mload(add(pC, 64)), and(or(shl(1, c), shr(63, c)), 0xffffffffffffffff)))
                    }
                    {
                        let c := mload(pC)
                        mstore(
                            add(pD, 128),
                            xor(mload(add(pC, 96)), and(or(shl(1, c), shr(63, c)), 0xffffffffffffffff))
                        )
                    }
                    mstore(pB, xor(mload(pA), mload(pD)))
                    {
                        let t := xor(mload(add(pA, 160)), mload(pD))
                        mstore(add(pB, 512), and(or(shl(36, t), shr(28, t)), 0xffffffffffffffff))
                    }
                    {
                        let t := xor(mload(add(pA, 320)), mload(pD))
                        mstore(add(pB, 224), and(or(shl(3, t), shr(61, t)), 0xffffffffffffffff))
                    }
                    {
                        let t := xor(mload(add(pA, 480)), mload(pD))
                        mstore(add(pB, 736), and(or(shl(41, t), shr(23, t)), 0xffffffffffffffff))
                    }
                    {
                        let t := xor(mload(add(pA, 640)), mload(pD))
                        mstore(add(pB, 448), and(or(shl(18, t), shr(46, t)), 0xffffffffffffffff))
                    }
                    {
                        let t := xor(mload(add(pA, 32)), mload(add(pD, 32)))
                        mstore(add(pB, 320), and(or(shl(1, t), shr(63, t)), 0xffffffffffffffff))
                    }
                    {
                        let t := xor(mload(add(pA, 192)), mload(add(pD, 32)))
                        mstore(add(pB, 32), and(or(shl(44, t), shr(20, t)), 0xffffffffffffffff))
                    }
                    {
                        let t := xor(mload(add(pA, 352)), mload(add(pD, 32)))
                        mstore(add(pB, 544), and(or(shl(10, t), shr(54, t)), 0xffffffffffffffff))
                    }
                    {
                        let t := xor(mload(add(pA, 512)), mload(add(pD, 32)))
                        mstore(add(pB, 256), and(or(shl(45, t), shr(19, t)), 0xffffffffffffffff))
                    }
                    {
                        let t := xor(mload(add(pA, 672)), mload(add(pD, 32)))
                        mstore(add(pB, 768), and(or(shl(2, t), shr(62, t)), 0xffffffffffffffff))
                    }
                    {
                        let t := xor(mload(add(pA, 64)), mload(add(pD, 64)))
                        mstore(add(pB, 640), and(or(shl(62, t), shr(2, t)), 0xffffffffffffffff))
                    }
                    {
                        let t := xor(mload(add(pA, 224)), mload(add(pD, 64)))
                        mstore(add(pB, 352), and(or(shl(6, t), shr(58, t)), 0xffffffffffffffff))
                    }
                    {
                        let t := xor(mload(add(pA, 384)), mload(add(pD, 64)))
                        mstore(add(pB, 64), and(or(shl(43, t), shr(21, t)), 0xffffffffffffffff))
                    }
                    {
                        let t := xor(mload(add(pA, 544)), mload(add(pD, 64)))
                        mstore(add(pB, 576), and(or(shl(15, t), shr(49, t)), 0xffffffffffffffff))
                    }
                    {
                        let t := xor(mload(add(pA, 704)), mload(add(pD, 64)))
                        mstore(add(pB, 288), and(or(shl(61, t), shr(3, t)), 0xffffffffffffffff))
                    }
                    {
                        let t := xor(mload(add(pA, 96)), mload(add(pD, 96)))
                        mstore(add(pB, 160), and(or(shl(28, t), shr(36, t)), 0xffffffffffffffff))
                    }
                    {
                        let t := xor(mload(add(pA, 256)), mload(add(pD, 96)))
                        mstore(add(pB, 672), and(or(shl(55, t), shr(9, t)), 0xffffffffffffffff))
                    }
                    {
                        let t := xor(mload(add(pA, 416)), mload(add(pD, 96)))
                        mstore(add(pB, 384), and(or(shl(25, t), shr(39, t)), 0xffffffffffffffff))
                    }
                    {
                        let t := xor(mload(add(pA, 576)), mload(add(pD, 96)))
                        mstore(add(pB, 96), and(or(shl(21, t), shr(43, t)), 0xffffffffffffffff))
                    }
                    {
                        let t := xor(mload(add(pA, 736)), mload(add(pD, 96)))
                        mstore(add(pB, 608), and(or(shl(56, t), shr(8, t)), 0xffffffffffffffff))
                    }
                    {
                        let t := xor(mload(add(pA, 128)), mload(add(pD, 128)))
                        mstore(add(pB, 480), and(or(shl(27, t), shr(37, t)), 0xffffffffffffffff))
                    }
                    {
                        let t := xor(mload(add(pA, 288)), mload(add(pD, 128)))
                        mstore(add(pB, 192), and(or(shl(20, t), shr(44, t)), 0xffffffffffffffff))
                    }
                    {
                        let t := xor(mload(add(pA, 448)), mload(add(pD, 128)))
                        mstore(add(pB, 704), and(or(shl(39, t), shr(25, t)), 0xffffffffffffffff))
                    }
                    {
                        let t := xor(mload(add(pA, 608)), mload(add(pD, 128)))
                        mstore(add(pB, 416), and(or(shl(8, t), shr(56, t)), 0xffffffffffffffff))
                    }
                    {
                        let t := xor(mload(add(pA, 768)), mload(add(pD, 128)))
                        mstore(add(pB, 128), and(or(shl(14, t), shr(50, t)), 0xffffffffffffffff))
                    }
                    {
                        let b0 := mload(pB)
                        let b1 := mload(add(pB, 32))
                        let b2 := mload(add(pB, 64))
                        let b3 := mload(add(pB, 96))
                        let b4 := mload(add(pB, 128))
                        mstore(pA, xor(xor(b0, and(xor(b1, 0xffffffffffffffff), b2)), rc(i)))
                        mstore(add(pA, 32), xor(b1, and(xor(b2, 0xffffffffffffffff), b3)))
                        mstore(add(pA, 64), xor(b2, and(xor(b3, 0xffffffffffffffff), b4)))
                        mstore(add(pA, 96), xor(b3, and(xor(b4, 0xffffffffffffffff), b0)))
                        mstore(add(pA, 128), xor(b4, and(xor(b0, 0xffffffffffffffff), b1)))
                    }
                    {
                        let b0 := mload(add(pB, 160))
                        let b1 := mload(add(pB, 192))
                        let b2 := mload(add(pB, 224))
                        let b3 := mload(add(pB, 256))
                        let b4 := mload(add(pB, 288))
                        mstore(add(pA, 160), xor(b0, and(xor(b1, 0xffffffffffffffff), b2)))
                        mstore(add(pA, 192), xor(b1, and(xor(b2, 0xffffffffffffffff), b3)))
                        mstore(add(pA, 224), xor(b2, and(xor(b3, 0xffffffffffffffff), b4)))
                        mstore(add(pA, 256), xor(b3, and(xor(b4, 0xffffffffffffffff), b0)))
                        mstore(add(pA, 288), xor(b4, and(xor(b0, 0xffffffffffffffff), b1)))
                    }
                    {
                        let b0 := mload(add(pB, 320))
                        let b1 := mload(add(pB, 352))
                        let b2 := mload(add(pB, 384))
                        let b3 := mload(add(pB, 416))
                        let b4 := mload(add(pB, 448))
                        mstore(add(pA, 320), xor(b0, and(xor(b1, 0xffffffffffffffff), b2)))
                        mstore(add(pA, 352), xor(b1, and(xor(b2, 0xffffffffffffffff), b3)))
                        mstore(add(pA, 384), xor(b2, and(xor(b3, 0xffffffffffffffff), b4)))
                        mstore(add(pA, 416), xor(b3, and(xor(b4, 0xffffffffffffffff), b0)))
                        mstore(add(pA, 448), xor(b4, and(xor(b0, 0xffffffffffffffff), b1)))
                    }
                    {
                        let b0 := mload(add(pB, 480))
                        let b1 := mload(add(pB, 512))
                        let b2 := mload(add(pB, 544))
                        let b3 := mload(add(pB, 576))
                        let b4 := mload(add(pB, 608))
                        mstore(add(pA, 480), xor(b0, and(xor(b1, 0xffffffffffffffff), b2)))
                        mstore(add(pA, 512), xor(b1, and(xor(b2, 0xffffffffffffffff), b3)))
                        mstore(add(pA, 544), xor(b2, and(xor(b3, 0xffffffffffffffff), b4)))
                        mstore(add(pA, 576), xor(b3, and(xor(b4, 0xffffffffffffffff), b0)))
                        mstore(add(pA, 608), xor(b4, and(xor(b0, 0xffffffffffffffff), b1)))
                    }
                    {
                        let b0 := mload(add(pB, 640))
                        let b1 := mload(add(pB, 672))
                        let b2 := mload(add(pB, 704))
                        let b3 := mload(add(pB, 736))
                        let b4 := mload(add(pB, 768))
                        mstore(add(pA, 640), xor(b0, and(xor(b1, 0xffffffffffffffff), b2)))
                        mstore(add(pA, 672), xor(b1, and(xor(b2, 0xffffffffffffffff), b3)))
                        mstore(add(pA, 704), xor(b2, and(xor(b3, 0xffffffffffffffff), b4)))
                        mstore(add(pA, 736), xor(b3, and(xor(b4, 0xffffffffffffffff), b0)))
                        mstore(add(pA, 768), xor(b4, and(xor(b0, 0xffffffffffffffff), b1)))
                    }
                }
            }
            // absorb calldata[off, end) with SHAKE padding; leaves the first output block in A[0..16]
            function absorb(off, end) {
                for { let i := 0 } lt(i, 0x6a0) { i := add(i, 32) } { mstore(i, 0) }
                mstore(0x780, 0x000)
                mstore(0x7a0, 0x320)
                mstore(0x7c0, 0x640)
                mstore(0x7e0, 0x6e0)
                let len := sub(end, off)
                calldatacopy(0x800, off, len)
                let pos := 0
                for {} 1 {} {
                    let n := sub(len, pos)
                    if gt(n, 135) { n := 136 }
                    for { let i := 0 } lt(i, n) { i := add(i, 1) } {
                        let ln := shl(5, shr(3, i))
                        mstore(ln, xor(mload(ln), shl(shl(3, and(i, 7)), byte(0, mload(add(0x800, add(pos, i)))))))
                    }
                    if lt(n, 136) {
                        let ln := shl(5, shr(3, n))
                        mstore(ln, xor(mload(ln), shl(shl(3, and(n, 7)), 0x1f)))
                        mstore(0x200, xor(mload(0x200), shl(56, 0x80)))
                        permute()
                        break
                    }
                    permute()
                    pos := add(pos, 136)
                }
            }
            let op := byte(0, calldataload(0))
            switch op
            case 1 {
                let outLen := shr(224, calldataload(1))
                absorb(5, calldatasize())
                let o := add(0x800, calldatasize())
                for { let k := 0 } lt(k, outLen) { k := add(k, 1) } {
                    let r := mod(k, 136)
                    if and(gt(k, 0), iszero(r)) { permute() }
                    mstore8(add(o, k), and(shr(shl(3, and(r, 7)), mload(shl(5, shr(3, r)))), 0xff))
                }
                return(o, outLen)
            }
            case 2 {
                absorb(1, calldatasize())
                let o := add(0x800, calldatasize())
                o := and(add(o, 31), not(31))
                let n := 0
                for {} 1 {} {
                    // 17 lanes = 68 big-endian 16-bit words per block
                    for { let l := 0 } and(lt(l, 17), lt(n, 1024)) { l := add(l, 1) } {
                        let v := mload(shl(5, l))
                        for { let j := 0 } and(lt(j, 4), lt(n, 1024)) { j := add(j, 1) } {
                            let w := or(shl(8, and(shr(shl(4, j), v), 0xff)), and(shr(add(shl(4, j), 8), v), 0xff))
                            if lt(w, 61445) {
                                mstore(add(o, shl(5, n)), mod(w, 12289))
                                n := add(n, 1)
                            }
                        }
                    }
                    if eq(n, 1024) { break }
                    permute()
                }
                return(o, 32768)
            }
            default { revert(0, 0) }
        }
    }
}
