// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.28;

// AUTO-GENERATED by test/e2e/relay/algorand/codegen/sumhash.ts — do not edit by hand.

import {ClprSumHashTableChunk} from "./ClprSumHashTableChunk.sol";

/// @title ClprSumHash512Engine
/// @notice Stand-alone SumHash512 engine (algorand/go-sumhash, as used by go-algorand `crypto.Sumhash`):
///         a subset-sum compression `A·x mod 2^64` with an 8 × 1024 matrix A expanded by
///         SHAKE256(u16 64 ‖ u16 8 ‖ u16 1024 ‖ "Algorand"), Merkle–Damgård over 64-byte blocks with a zero
///         IV, the 64-byte chaining value prepended to each block, and padding
///         `0x01 0… (to 48 mod 64) ‖ bitlen LE64 ‖ 0 LE64`. Algorand state proofs commit to participants,
///         signatures and Falcon ephemeral keys with SumHash512 vector commitments (crypto/merklearray).
///
///         The compression uses a nibble table: for each of the 256 nibble positions of the 128-byte input
///         and each nibble value, the precomputed 8-lane column sum (256 KiB). It lives in 16 data
///         contracts whose code hashes are pinned below and checked in the constructor; the engine copies
///         it into memory once per call.
///
///         Calldata is a list of jobs `leafLen u32 ‖ leaf ‖ pos u64 ‖ depth u8 ‖ path (depth × 64)`. For each
///         job the engine hashes the leaf preimage (caller supplies the domain prefix) and folds the
///         vector-commitment path: the leaf sits at tree position `reverseBits(pos, depth)`
///         (merklearray `merkleTreeToVectorCommitmentIndex`), and each level hashes
///         `"MA" ‖ left ‖ right`. Returns the 64-byte root of each job (the leaf hash when depth is 0).
/// @dev Memory map: 0x0000 chunk index · 0x0200 leaf buffer · 0x1400 node buffer · 0x1600 output ·
///
///      0x2000 table (0x40000 bytes).
contract ClprSumHash512Engine {
    bytes32 internal constant CHUNK_0 = 0xd0bd839c754e9041336a068f1c34512e2557da0f45d807f98559606c04375662;
    bytes32 internal constant CHUNK_1 = 0xf1d6b5337d368ac63bf65c0c344daa8927c6d5d0472730bb1a51f3150fc5f2ec;
    bytes32 internal constant CHUNK_2 = 0x397b5d6cd69b3fba0f7a28ffcd1202339718137e5f3b6e53b6cf5bb51c15573b;
    bytes32 internal constant CHUNK_3 = 0x346dacc35090fec10964a7e4e1ebe9a0a16c9d276a0fe7d1a30c0b944ca2eb25;
    bytes32 internal constant CHUNK_4 = 0x22d5eb3e13035e1b9690685eae93df3ce2353adc08c1a9de42ccc29fe1c1a878;
    bytes32 internal constant CHUNK_5 = 0xbba92885db1b9d2da15be72d68e3adeaf28fdf42a9056ccc24e43b60dccc6eed;
    bytes32 internal constant CHUNK_6 = 0x0ba1c288eee0e6716198f4e631b03c25945c3f9b67daeb12a171348905009087;
    bytes32 internal constant CHUNK_7 = 0x34e915aaa25edd44506fee2ed9ee362fc2b3fa3cc97593eadfefb9cd717511ea;
    bytes32 internal constant CHUNK_8 = 0x2fec837c98a91ba1dbd247c71e1ff07615a610a8d38cc29c15ccc1da3f77c30c;
    bytes32 internal constant CHUNK_9 = 0x208a23db60953e07bd3e6ea3dd2e7c8316870299588447bdae2a68ec476cb45d;
    bytes32 internal constant CHUNK_10 = 0x2d37b394e266669606c2d249079811f1dd7402a504a1e9c16afeb9a4e621b960;
    bytes32 internal constant CHUNK_11 = 0x3dab0028101f68f405d80122149eb8ffadbf11991c185acf9cd6c54b938e5923;
    bytes32 internal constant CHUNK_12 = 0x3ac20c8aac24ec73d6dcf126e5846a2c482b74c2a9bf4983173da49e01cdc06d;
    bytes32 internal constant CHUNK_13 = 0x75707c047b49fe7f745b4f6207bba0784edb89da42918176ae27f4e4b5d00138;
    bytes32 internal constant CHUNK_14 = 0x508f3cb23045f30242332e4a529118ee1e12a57817ab80fb8019a8c3fe8ef932;
    bytes32 internal constant CHUNK_15 = 0x075dbe1a5ac4fe94942fe4efd28e65dee074add7cc5399805d5dd97cc51f1c4f;

    uint256 internal constant MAX_LEAF = 4400;
    uint256 internal constant MAX_JOBS = 32;
    uint256 internal constant MAX_DEPTH = 20;

    /// @notice Data contract holding the 16 table-chunk addresses (20 bytes each, after a STOP byte).
    address public immutable INDEX;

    error BadTableChunk(uint256 index);

    constructor(address[16] memory chunks) {
        bytes32[16] memory expected = [
            CHUNK_0,
            CHUNK_1,
            CHUNK_2,
            CHUNK_3,
            CHUNK_4,
            CHUNK_5,
            CHUNK_6,
            CHUNK_7,
            CHUNK_8,
            CHUNK_9,
            CHUNK_10,
            CHUNK_11,
            CHUNK_12,
            CHUNK_13,
            CHUNK_14,
            CHUNK_15
        ];
        bytes memory idx = abi.encodePacked(uint8(0));
        for (uint256 i = 0; i < 16; i++) {
            if (chunks[i].codehash != expected[i]) revert BadTableChunk(i);
            idx = abi.encodePacked(idx, chunks[i]);
        }
        INDEX = address(new ClprSumHashTableChunk(idx));
    }

    fallback() external {
        address index = INDEX;
        assembly {
            function rev(x) -> y {
                y := or(
                    shr(8, and(x, 0xff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00)),
                    shl(8, and(x, 0x00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff))
                )
                y := or(
                    shr(16, and(y, 0xffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000)),
                    shl(16, and(y, 0x0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff))
                )
                y := or(
                    shr(32, and(y, 0xffffffff00000000ffffffff00000000ffffffff00000000ffffffff00000000)),
                    shl(32, and(y, 0x00000000ffffffff00000000ffffffff00000000ffffffff00000000ffffffff))
                )
                y := or(
                    shr(64, and(y, 0xffffffffffffffff0000000000000000ffffffffffffffff0000000000000000)),
                    shl(64, and(y, 0x0000000000000000ffffffffffffffff0000000000000000ffffffffffffffff))
                )
                y := or(shr(128, y), shl(128, y))
            }
            // chaining value (h0, h1): message bits 0..255 / 256..511, least significant bit first;
            // the 64-byte block is read as two big-endian words. Iteration q looks up nibble q of h0
            // (position q), of h1 (q + 64) and both nibbles of block byte q (128 + 2q, 129 + 2q).
            // Accumulators: a = Σ w and e = Σ (w & even lanes), so a − e = Σ (w & odd lanes); every lane
            // keeps its carries in the 64-bit gap above it.
            function compress(h0, h1, blk) -> r0, r1 {
                let a0 := 0
                let e0 := 0
                let a1 := 0
                let e1 := 0
                let ME := 0x0000000000000000ffffffffffffffff0000000000000000ffffffffffffffff
                for { let q := 0 } lt(q, 64) { q := add(q, 1) } {
                    // entry addresses: nibble q of h0 (position q), of h1 (q + 64), and the low / high
                    // nibbles of block byte q (128 + 2q, 129 + 2q); entry (p, v) is at 0x2000 + 1024·p + 64·v
                    let base := add(0x2000, shl(10, q))
                    let x0 := add(base, and(shl(6, shr(shl(2, q), h0)), 0x3c0))
                    let x1 := add(add(base, 0x10000), and(shl(6, shr(shl(2, q), h1)), 0x3c0))
                    let byt := byte(0, mload(add(blk, q)))
                    let x2 := add(add(0x22000, shl(11, q)), shl(6, and(byt, 15)))
                    let x3 := add(add(0x22400, shl(11, q)), shl(6, shr(4, byt)))
                    a0 := add(a0, add(add(mload(x0), mload(x1)), add(mload(x2), mload(x3))))
                    e0 := add(
                        e0,
                        add(add(and(mload(x0), ME), and(mload(x1), ME)), add(and(mload(x2), ME), and(mload(x3), ME)))
                    )
                    x0 := add(x0, 32)
                    x1 := add(x1, 32)
                    x2 := add(x2, 32)
                    x3 := add(x3, 32)
                    a1 := add(a1, add(add(mload(x0), mload(x1)), add(mload(x2), mload(x3))))
                    e1 := add(
                        e1,
                        add(add(and(mload(x0), ME), and(mload(x1), ME)), add(and(mload(x2), ME), and(mload(x3), ME)))
                    )
                }
                r0 := or(and(e0, ME), and(sub(a0, e0), not(ME)))
                r1 := or(and(e1, ME), and(sub(a1, e1), not(ME)))
            }
            // SumHash512 of memory [ptr, ptr + len), padded in place (the buffer has 128 spare bytes)
            function sumhash(ptr, len) -> h0, h1 {
                let r := mod(len, 64)
                let padLen := sub(48, r)
                if iszero(lt(r, 48)) { padLen := sub(112, r) }
                let end := add(add(ptr, len), add(padLen, 16))
                for { let z := add(ptr, len) } lt(z, end) { z := add(z, 32) } { mstore(z, 0) }
                mstore8(add(ptr, len), 1)
                let bits := shl(3, len)
                let tl := add(add(ptr, len), padLen)
                for { let k := 0 } lt(k, 8) { k := add(k, 1) } { mstore8(add(tl, k), and(shr(shl(3, k), bits), 0xff)) }
                for { let o := ptr } lt(o, end) { o := add(o, 64) } { h0, h1 := compress(h0, h1, o) }
            }

            // load the table: 16 chunks of 16 KiB
            extcodecopy(index, 0, 1, 320)
            for { let i := 0 } lt(i, 16) { i := add(i, 1) } {
                extcodecopy(shr(96, mload(mul(i, 20))), add(0x2000, shl(14, i)), 1, 16384)
            }

            let cd := 0
            let out := 0x1600
            for {} lt(cd, calldatasize()) {} {
                if iszero(lt(out, add(0x1600, shl(6, 32)))) { revert(0, 0) }
                let len := shr(224, calldataload(cd))
                cd := add(cd, 4)
                if gt(len, 4400) { revert(0, 0) }
                calldatacopy(0x200, cd, len)
                cd := add(cd, len)
                let pos := shr(192, calldataload(cd))
                let depth := byte(0, calldataload(add(cd, 8)))
                cd := add(cd, 9)
                if gt(depth, 20) { revert(0, 0) }
                if iszero(lt(pos, shl(depth, 1))) { revert(0, 0) }
                if gt(add(cd, shl(6, depth)), calldatasize()) { revert(0, 0) }
                let h0, h1 := sumhash(0x200, len)
                let tp := 0
                for { let i := 0 } lt(i, depth) { i := add(i, 1) } { tp := or(shl(1, tp), and(shr(i, pos), 1)) }
                for { let l := 0 } lt(l, depth) { l := add(l, 1) } {
                    mstore(0x1400, shl(240, 0x4d41))
                    switch and(tp, 1)
                    case 0 {
                        mstore(0x1402, rev(h0))
                        mstore(0x1422, rev(h1))
                        calldatacopy(0x1442, cd, 64)
                    }
                    default {
                        calldatacopy(0x1402, cd, 64)
                        mstore(0x1442, rev(h0))
                        mstore(0x1462, rev(h1))
                    }
                    cd := add(cd, 64)
                    h0, h1 := sumhash(0x1400, 130)
                    tp := shr(1, tp)
                }
                mstore(out, rev(h0))
                mstore(add(out, 32), rev(h1))
                out := add(out, 64)
            }
            return(0x1600, sub(out, 0x1600))
        }
    }
}
