// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.28;

import {Test} from "forge-std/Test.sol";
import {MonadVerifier} from "@hiero-ledger/clpr/verifiers/evm/monad/MonadVerifier.sol";
import {MonadValsetRotation} from "@hiero-ledger/clpr/verifiers/evm/monad/MonadValsetRotation.sol";
import {ClprTypes} from "@hiero-ledger/clpr/libraries/ClprTypes.sol";

/// @dev Fixture: test/verifiers/evm/monad/fixtures/synthetic/*.json, generated by
///      test/e2e/relay/monad/buildMonadFixtures.ts (196 validators, real BLS / BLAKE3 / MPT encodings).
contract MonadVerifierTest is Test {
    MonadVerifier verifier;
    bytes ctx;

    string internal constant DIR = "test/verifiers/evm/monad/fixtures/synthetic/";

    function setUp() public {
        verifier = new MonadVerifier(new MonadValsetRotation());
        ctx = vm.parseJsonBytes(_j(), ".channelContext");
    }

    /// @dev meta.json (small); each case lives in its own file.
    function _j() internal view returns (string memory) {
        return vm.readFile(string.concat(DIR, "meta.json"));
    }

    function _file(string memory name) internal view returns (string memory) {
        return vm.readFile(string.concat(DIR, name, ".json"));
    }

    function _case(string memory name) internal view returns (bytes memory proof, bytes memory anchor) {
        string memory c = _file(name);
        proof = vm.parseJsonBytes(c, ".proof");
        anchor = vm.parseJsonBytes(c, ".anchor");
    }

    function _verify(bytes memory proof, bytes memory anchor)
        internal
        view
        returns (
            ClprTypes.QueueMetadata memory m,
            bytes[] memory msgs,
            bytes memory na,
            bytes memory nid,
            ClprTypes.ClprEndpointManifest memory man
        )
    {
        return verifier.verifyBundle(proof, anchor, ctx);
    }

    function _expectRevert(string memory name, bytes4 selector) internal {
        (bytes memory proof, bytes memory anchor) = _case(name);
        vm.expectRevert(selector);
        verifier.verifyBundle(proof, anchor, ctx);
    }

    // ── positive ──────────────────────────────────────────────────────────────

    function test_bundle_finalized() public view {
        (bytes memory proof, bytes memory anchor) = _case("bundle_ok");
        (
            ClprTypes.QueueMetadata memory m,
            bytes[] memory msgs,
            bytes memory na,
            bytes memory nid,
            ClprTypes.ClprEndpointManifest memory man
        ) = _verify(proof, anchor);
        assertEq(m.nextMessageId, vm.parseJsonUint(_j(), ".meta.channel.nextMessageId"));
        assertEq(m.receivedMessageId, vm.parseJsonUint(_j(), ".meta.channel.receivedMessageId"));
        assertEq(m.sentRunningHash, vm.parseJsonBytes32(_j(), ".meta.channel.sentRunningHash"));
        assertEq(m.receivedRunningHash, vm.parseJsonBytes32(_j(), ".meta.channel.receivedRunningHash"));
        assertEq(uint8(m.state), 1);
        assertEq(m.endpointManifestVersion, 1);
        assertEq(msgs.length, 2);
        assertEq(msgs[0], vm.parseJsonBytes(_j(), ".messages[0]"));
        assertEq(na.length, 0);
        assertEq(nid.length, 0);
        assertEq(man.version, 0);
    }

    function test_bundle_withManifest() public view {
        (bytes memory proof, bytes memory anchor) = _case("bundle_manifest");
        (,,,, ClprTypes.ClprEndpointManifest memory man) = _verify(proof, anchor);
        assertEq(man.version, 2);
        assertEq(man.serviceAddress, abi.encodePacked(vm.parseJsonAddress(_j(), ".meta.service")));
    }

    function test_blockIds_matchBlake3() public view {
        // The fixture's P/B ids are blake3(rlp(header)) computed off-chain; the bundle only verifies if
        // the on-chain BLAKE3 agrees, but check the tooling entry point too.
        (bytes memory proof,) = _case("bundle_ok");
        proof; // ids are covered by test_bundle_finalized
        assertTrue(vm.parseJsonBytes32(_j(), ".meta.blockIdP") != bytes32(0));
    }

    function test_fullRotation_thenNextEpoch() public {
        (bytes memory proof, bytes memory anchor) = _case("rotation_start");
        (,, bytes memory na,,) = _verify(proof, anchor);
        assertEq(na, vm.parseJsonBytes(_file("rotation_start"), ".note"), "pending anchor");

        uint256 steps = vm.parseJsonUint(_j(), ".rotationSteps");
        for (uint256 i = 0; i < steps; ++i) {
            string memory st = _file(string.concat("rotation_step_", vm.toString(i)));
            bytes memory nid;
            (,, na, nid,) = _verify(vm.parseJsonBytes(st, ".proof"), na);
            assertEq(na, vm.parseJsonBytes(st, ".anchorAfter"));
            assertGt(nid.length, 0);
        }
        assertEq(na, vm.parseJsonBytes(_j(), ".anchor1"), "rotated anchor");

        (proof,) = _case("bundle_next_epoch");
        (ClprTypes.QueueMetadata memory m,,,,) = _verify(proof, na);
        assertEq(m.nextMessageId, 4);
    }

    function test_coldRotation_allKeysProven() public view {
        bytes memory na = vm.parseJsonBytes(_j(), ".coldStart");
        uint256 steps = vm.parseJsonUint(_j(), ".rotationColdSteps");
        for (uint256 i = 0; i < steps; ++i) {
            string memory st = _file(string.concat("rotation_cold_step_", vm.toString(i)));
            (,, na,,) = _verify(vm.parseJsonBytes(st, ".proof"), na);
            assertEq(na, vm.parseJsonBytes(st, ".anchorAfter"));
        }
        assertEq(na, vm.parseJsonBytes(_j(), ".anchor1"), "rotated anchor (cold)");
    }

    function test_rotationRestart_keepsProgress() public view {
        (bytes memory proof, bytes memory anchor) = _case("rotation_restart_keeps_progress");
        (,, bytes memory na,,) = _verify(proof, anchor);
        assertEq(na, vm.parseJsonBytes(_file("rotation_restart_keeps_progress"), ".note"));
    }

    function test_finalize_separately() public view {
        (bytes memory proof, bytes memory anchor) = _case("finalize_ok_separate");
        (,, bytes memory na,,) = _verify(proof, anchor);
        assertEq(na, vm.parseJsonBytes(_file("finalize_ok_separate"), ".note"));
    }

    function test_verifyConfig() public view {
        bytes32 channelId = vm.parseJsonBytes32(_j(), ".channelId");
        (
            bytes memory cctx,
            string memory chainId,
            bytes memory svc,,
            ClprTypes.Throttles memory t,
            bytes memory anchor,
            bytes memory anchorId,
            ClprTypes.ClprEndpointManifest memory man
        ) = verifier.verifyConfig(
            vm.parseJsonBytes(_j(), ".config"), channelId, vm.parseJsonBytes(_j(), ".manifestProof")
        );
        assertEq(cctx, ctx);
        assertEq(chainId, "eip155:143");
        assertEq(svc, abi.encodePacked(vm.parseJsonAddress(_j(), ".meta.service")));
        assertEq(t.maxMessagesPerBundle, 50);
        assertEq(t.maxPeerEndpoints, 8);
        assertEq(anchor, vm.parseJsonBytes(_j(), ".anchor0"));
        assertEq(anchorId.length, 24);
        assertEq(man.version, 2);

        // Without a manifest proof: UNINITIALIZED manifest (version 0) for bring-up.
        (,,,,,,, man) = verifier.verifyConfig(vm.parseJsonBytes(_j(), ".config"), channelId, "");
        assertEq(man.version, 0);
    }

    // ── negative: finality / QC ───────────────────────────────────────────────

    function test_rejects_badSignature() public {
        _expectRevert("bad_signature", bytes4(keccak256("BlsSignatureInvalid()")));
    }

    function test_rejects_signatureNotBoundToQc() public {
        _expectRevert("bad_signature_encoding", bytes4(keccak256("BlsSignatureEncoding()")));
    }

    function test_rejects_belowThreshold() public {
        _expectRevert("below_threshold", MonadVerifier.InsufficientStake.selector);
    }

    function test_rejects_wrongValidatorSet() public {
        _expectRevert("wrong_validator_set", MonadVerifier.ValidatorSetMismatch.selector);
        _expectRevert("wrong_anchor_set", MonadVerifier.ValidatorSetMismatch.selector);
    }

    function test_rejects_notCommitted() public {
        _expectRevert("not_committed", MonadVerifier.NotCommitted.selector);
    }

    function test_rejects_delayedRootForWrongBlock() public {
        _expectRevert("delayed_mismatch", MonadVerifier.DelayedResultMismatch.selector);
    }

    function test_rejects_unlinkedHeaders() public {
        _expectRevert("block_id_mismatch", MonadVerifier.BlockIdMismatch.selector);
    }

    function test_rejects_staleOrReplayedEpoch() public {
        _expectRevert("stale_epoch", MonadVerifier.EpochMismatch.selector);
        // An epoch-E bundle replayed after rotation carries epoch E's validator set → rejected at the set binding.
        _expectRevert("replay_old_epoch_after_rotation", MonadVerifier.ValidatorSetMismatch.selector);
        _expectRevert("next_epoch_qc_before_rotation", MonadVerifier.EpochMismatch.selector);
    }

    // ── negative: storage ─────────────────────────────────────────────────────

    function test_rejects_wrongStorageProof() public {
        _expectRevert("wrong_storage_value", bytes4(keccak256("PageCommitmentMismatch()")));
        _expectRevert("wrong_storage_node", bytes4(keccak256("MptHashMismatch()")));
        _expectRevert("wrong_code_hash", bytes4(keccak256("CodeHashMismatch()")));
    }

    function test_rejects_missingPage() public {
        (bytes memory proof, bytes memory anchor) = _case("missing_page");
        vm.expectPartialRevert(bytes4(keccak256("PageNotProven(bytes32)")));
        verifier.verifyBundle(proof, anchor, ctx);
    }

    // ── negative: rotation ────────────────────────────────────────────────────

    function test_rejects_rotationOutsideDelayPeriod() public {
        _expectRevert("rotation_not_in_delay", MonadValsetRotation.RotationStateInvalid.selector);
    }

    function test_rejects_staleRotationRestart() public {
        _expectRevert("rotation_restart_stale", MonadValsetRotation.RotationStale.selector);
    }

    function test_rejects_badFinalize() public {
        _expectRevert("finalize_bad_permutation", MonadValsetRotation.RotationAccumulatorMismatch.selector);
        _expectRevert("finalize_unsorted", MonadValsetRotation.ValidatorOrder.selector);
        _expectRevert("finalize_dup_index", MonadValsetRotation.InvalidPermutation.selector);
        _expectRevert("finalize_wrong_stake", MonadValsetRotation.RotationAccumulatorMismatch.selector);
        _expectRevert("finalize_incomplete", MonadValsetRotation.RotationIncomplete.selector);
    }

    function test_rejects_badChunk() public {
        _expectRevert("chunk_tampered_keys", bytes4(keccak256("PageCommitmentMismatch()")));
        _expectRevert("chunk_overflow", MonadValsetRotation.RotationOverflow.selector);
        _expectRevert("rotation_without_pending", MonadVerifier.RotationNotPending.selector);
        _expectRevert("chunk_wrong_ids", MonadValsetRotation.RotationStateInvalid.selector);
        _expectRevert("chunk_wrong_registry", MonadValsetRotation.RotationStateInvalid.selector);
        _expectRevert("chunk_wrong_hint", MonadValsetRotation.InvalidValidatorEntry.selector);
    }

    function test_rejects_malformedAnchor() public {
        (bytes memory proof,) = _case("bundle_ok");
        vm.expectRevert(MonadVerifier.InvalidTrustAnchor.selector);
        verifier.verifyBundle(proof, hex"00", ctx);
    }
}
