// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.28;

import {Test} from "forge-std/Test.sol";
import {RLP} from "@openzeppelin/contracts/utils/RLP.sol";
import {ClprTypes} from "@hiero-ledger/clpr/libraries/ClprTypes.sol";

/// @dev Assembles StellarScpVerifier proofs from the synthetic fixture
///      (test/verifiers/evm/stellar/fixtures/synthetic.json, generated by
///      test/e2e/relay/buildStellarSyntheticFixture.ts with real Ed25519 signatures and real XDR).
abstract contract StellarTestBuilder is Test {
    string internal fx;

    // Fixture constants (see the generator for the chain layout).
    bytes32 internal NETWORK_ID;
    bytes32 internal SERVICE;
    bytes32 internal CHANNEL;
    bytes internal Q1;
    bytes32 internal Q1_HASH;
    bytes internal Q2;
    bytes32 internal Q2_HASH;

    function _loadFixture() internal {
        fx = vm.readFile(string.concat(vm.projectRoot(), "/test/verifiers/evm/stellar/fixtures/synthetic.json"));
        NETWORK_ID = vm.parseJsonBytes32(fx, ".networkId");
        SERVICE = vm.parseJsonBytes32(fx, ".serviceContract");
        CHANNEL = vm.parseJsonBytes32(fx, ".channelId");
        Q1 = vm.parseJsonBytes(fx, ".q1");
        Q1_HASH = vm.parseJsonBytes32(fx, ".q1Hash");
        Q2 = vm.parseJsonBytes(fx, ".q2");
        Q2_HASH = vm.parseJsonBytes32(fx, ".q2Hash");
    }

    // ── Raw fixture pieces ───────────────────────────────────────────────────

    function _header(uint256 seq) internal view returns (bytes memory) {
        return vm.parseJsonBytes(fx, string.concat(".headers.", vm.toString(seq)));
    }

    function _headerHash(uint256 seq) internal view returns (bytes32) {
        return vm.parseJsonBytes32(fx, string.concat(".headerHashes.", vm.toString(seq)));
    }

    function _txSet(uint256 seq) internal view returns (bytes memory) {
        return vm.parseJsonBytes(fx, string.concat(".txSets.", vm.toString(seq)));
    }

    function _envCount(string memory key) internal view returns (uint256) {
        return vm.parseJsonStringArray(fx, string.concat(".slotNodes.", key)).length;
    }

    function _statement(string memory key, uint256 i) internal view returns (bytes memory) {
        return vm.parseJsonBytes(fx, string.concat(".slots.", key, "[", vm.toString(i), "].statement"));
    }

    function _signature(string memory key, uint256 i) internal view returns (bytes memory) {
        return vm.parseJsonBytes(fx, string.concat(".slots.", key, "[", vm.toString(i), "].signature"));
    }

    function _node(string memory key, uint256 i) internal view returns (string memory) {
        return vm.parseJsonStringArray(fx, string.concat(".slotNodes.", key))[i];
    }

    // ── RLP helpers ──────────────────────────────────────────────────────────

    function _list(bytes[] memory items) internal pure returns (bytes memory) {
        return RLP.encode(items);
    }

    function _emptyList() internal pure returns (bytes memory) {
        return RLP.encode(new bytes[](0));
    }

    function _str(bytes memory b) internal pure returns (bytes memory) {
        return RLP.encode(b);
    }

    // ── Proof pieces ─────────────────────────────────────────────────────────

    struct Env {
        bytes statement;
        bytes signature;
    }

    /// @dev All envelopes of a fixture slot, in fixture (node id) order.
    function _envs(string memory key) internal view returns (Env[] memory e) {
        uint256 n = _envCount(key);
        e = new Env[](n);
        for (uint256 i = 0; i < n; ++i) {
            e[i] = Env(_statement(key, i), _signature(key, i));
        }
    }

    /// @dev Envelopes whose fixture node name is in `names` (kept in node-id order).
    function _pick(string memory key, string[] memory names) internal view returns (Env[] memory e) {
        uint256 n = _envCount(key);
        Env[] memory tmp = new Env[](n);
        uint256 k;
        for (uint256 i = 0; i < n; ++i) {
            string memory node = _node(key, i);
            for (uint256 j = 0; j < names.length; ++j) {
                if (keccak256(bytes(node)) == keccak256(bytes(names[j]))) {
                    tmp[k++] = Env(_statement(key, i), _signature(key, i));
                    break;
                }
            }
        }
        e = new Env[](k);
        for (uint256 i = 0; i < k; ++i) {
            e[i] = tmp[i];
        }
    }

    function _names(string memory a, string memory b, string memory c, string memory d)
        internal
        pure
        returns (string[] memory n)
    {
        n = new string[](4);
        (n[0], n[1], n[2], n[3]) = (a, b, c, d);
    }

    function _scp(Env[] memory envs, bytes memory txSet, bytes memory newQset) internal pure returns (bytes memory) {
        bytes[] memory es = new bytes[](envs.length);
        for (uint256 i = 0; i < envs.length; ++i) {
            bytes[] memory pair = new bytes[](2);
            pair[0] = _str(envs[i].statement);
            pair[1] = _str(envs[i].signature);
            es[i] = _list(pair);
        }
        bytes[] memory items = new bytes[](3);
        items[0] = _list(es);
        items[1] = _str(txSet);
        items[2] = _str(newQset);
        return _list(items);
    }

    /// @dev Q1 finality for `slot` with the standard 4 signers (orgs A and B).
    function _scpStd(uint256 slot) internal view returns (bytes memory) {
        return _scp(_pick(vm.toString(slot), _names("A0", "A1", "B0", "B1")), _txSet(slot), "");
    }

    /// @dev Headers `from` down to `to` (inclusive).
    function _headers(uint256 from, uint256 to) internal view returns (bytes memory) {
        bytes[] memory hs = new bytes[](from - to + 1);
        for (uint256 i = 0; i < hs.length; ++i) {
            hs[i] = _str(_header(from - i));
        }
        return _list(hs);
    }

    struct Att {
        bytes txPayload;
        bytes resultSet;
        uint256 offset;
        bytes preimage;
    }

    function _att(string memory name) internal view returns (Att memory a) {
        string memory p = string.concat(".attestations.", name);
        a.txPayload = vm.parseJsonBytes(fx, string.concat(p, ".txPayload"));
        a.resultSet = vm.parseJsonBytes(fx, string.concat(p, ".resultSet"));
        a.offset = vm.parseJsonUint(fx, string.concat(p, ".offset"));
        a.preimage = vm.parseJsonBytes(fx, string.concat(p, ".preimage"));
    }

    function _attItem(Att memory a) internal pure returns (bytes memory) {
        bytes[] memory items = new bytes[](4);
        items[0] = _str(a.txPayload);
        items[1] = _str(a.resultSet);
        items[2] = RLP.encode(a.offset);
        items[3] = _str(a.preimage);
        return _list(items);
    }

    function _bundle(
        bytes memory qset,
        bytes memory scpItem,
        bytes memory headersItem,
        bytes memory attItem,
        bytes memory lastMeta,
        bytes memory content,
        bytes memory manifest
    ) internal pure returns (bytes memory) {
        bytes[] memory items = new bytes[](7);
        items[0] = _str(qset);
        items[1] = scpItem;
        items[2] = headersItem;
        items[3] = attItem;
        items[4] = _str(lastMeta);
        items[5] = _str(content);
        items[6] = _str(manifest);
        return _list(items);
    }

    function _anchor(bytes32 qsetHash, uint64 lastSlot, uint32 cpSeq, bytes32 cpHash, bytes32 lastMetaHash)
        internal
        pure
        returns (bytes memory)
    {
        return abi.encode(qsetHash, lastSlot, cpSeq, cpHash, lastMetaHash);
    }

    function _context(bytes32 channelId, bytes32 service) internal pure returns (bytes memory) {
        return ClprTypes.encodeChannelContext(
            ClprTypes.ChannelContext({channelId: channelId, remoteServiceAddress: abi.encodePacked(service)})
        );
    }

    /// @dev The metadata the fixture's `clpr_queue` events carry (IntegrationTestBase's DATA + REPLY).
    function _fixtureMeta() internal view returns (ClprTypes.QueueMetadata memory m) {
        m.nextMessageId = 3;
        m.sentRunningHash = vm.parseJsonBytes32(fx, ".queueEventData.sentRunningHash");
        m.receivedMessageId = 1;
        m.state = ClprTypes.ChannelStatus.ACTIVE;
    }
}
