// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.28;

import {Test, console} from "forge-std/Test.sol";
import {StarknetVerifier} from "@hiero-ledger/clpr/verifiers/evm/starknet/StarknetVerifier.sol";
import {StarknetStateProver} from "@hiero-ledger/clpr/verifiers/evm/starknet/StarknetStateProver.sol";
import {IStarknetStateProver} from "@hiero-ledger/clpr/verifiers/evm/starknet/lib/IStarknetStateProver.sol";
import {EthL1StateVerifier} from "@hiero-ledger/clpr/verifiers/evm/ethereum/EthL1StateVerifier.sol";
import {IEthL1StateVerifier} from "@hiero-ledger/clpr/verifiers/evm/ethereum/lib/IEthL1StateVerifier.sol";
import {ClprEvmBundleVerifier} from "@hiero-ledger/clpr/verifiers/evm/common/ClprEvmBundleVerifier.sol";
import {StarkPedersenTableA, StarkPedersenTableB} from "@hiero-ledger/clpr/libraries/proof/starknet/StarkTables.sol";
import {StarkPedersen} from "@hiero-ledger/clpr/libraries/proof/starknet/StarkPedersen.sol";
import {StarkPoseidon} from "@hiero-ledger/clpr/libraries/proof/starknet/StarkPoseidon.sol";
import {StarknetPatricia} from "@hiero-ledger/clpr/libraries/proof/starknet/StarknetPatricia.sol";
import {StarknetCoreProof} from "@hiero-ledger/clpr/libraries/proof/starknet/StarknetCoreProof.sol";
import {EthBeaconLightClient} from "@hiero-ledger/clpr/libraries/proof/beacon/EthBeaconLightClient.sol";
import {ClprBeaconSsz} from "@hiero-ledger/clpr/libraries/proof/beacon/ClprBeaconSsz.sol";
import {ClprTypes} from "@hiero-ledger/clpr/libraries/ClprTypes.sol";
import {ClprProtobuf} from "@hiero-ledger/clpr/libraries/codec/ClprProtobuf.sol";
import {RLP} from "@openzeppelin/contracts/utils/RLP.sol";
import {EthCommitteeFixtures} from "@test/verifiers/evm/ethereum/EthCommitteeFixtures.sol";
import {MockEthL1StateVerifier} from "@test/verifiers/evm/opstack/OpStackVerifier.t.sol";

/// @dev Fixture plumbing: test/verifiers/evm/starknet/fixtures/synthetic.json, generated by
///      `test/e2e/relay/buildStarknetSyntheticFixture.ts` (reference Pedersen/Poseidon/Patricia code,
///      anvil eth_getProof for L1, and one real Starknet Sepolia storage proof).
abstract contract StarknetFixture is EthCommitteeFixtures {
    uint256 internal constant P = 0x0800000000000011000000000000000000000000000000000000000000000001;

    string internal json;
    StarknetStateProver internal prover;

    bytes32 internal l1StateRoot;
    address internal core;
    bytes32 internal coreImplCodeHash;
    bytes32[] internal pinnedSlots;
    bytes32[] internal pinnedValues;
    bytes internal coreProof;

    uint256 internal globalRoot;
    uint256 internal service;
    uint256 internal classHash;
    bytes32 internal channelId;
    bytes32 internal otherChannelId;
    bytes internal manifest;

    function setUp() public virtual override {
        super.setUp();
        json = vm.readFile(string.concat(vm.projectRoot(), "/test/verifiers/evm/starknet/fixtures/synthetic.json"));
        prover = new StarknetStateProver(address(new StarkPedersenTableA()), address(new StarkPedersenTableB()));
        l1StateRoot = vm.parseJsonBytes32(json, ".l1.stateRoot");
        core = vm.parseJsonAddress(json, ".l1.core");
        coreImplCodeHash = vm.parseJsonBytes32(json, ".l1.coreImplCodeHash");
        pinnedSlots = vm.parseJsonBytes32Array(json, ".l1.pinnedSlots");
        pinnedValues = vm.parseJsonBytes32Array(json, ".l1.pinnedValues");
        coreProof = vm.parseJsonBytes(json, ".l1.coreProof");
        globalRoot = vm.parseJsonUint(json, ".starknet.globalRoot");
        service = vm.parseJsonUint(json, ".starknet.service");
        classHash = vm.parseJsonUint(json, ".starknet.classHash");
        channelId = vm.parseJsonBytes32(json, ".starknet.channelId");
        otherChannelId = vm.parseJsonBytes32(json, ".starknet.otherChannelId");
        manifest = vm.parseJsonBytes(json, ".starknet.manifest");
    }

    function _proof(string memory name) internal view returns (bytes memory) {
        return vm.parseJsonBytes(json, string.concat(".starknet.proofs.", name));
    }

    function _keys(string memory name) internal view returns (uint256[] memory) {
        return vm.parseJsonUintArray(json, string.concat(".starknet.keys.", name));
    }

    function _profile() internal view returns (StarknetVerifier.Profile memory) {
        return StarknetVerifier.Profile({
            core: core, coreImplCodeHash: coreImplCodeHash, pinnedSlots: pinnedSlots, pinnedValues: pinnedValues
        });
    }

    function _layout() internal view returns (StarknetVerifier.Layout memory) {
        return StarknetVerifier.Layout({
            channelsBase: vm.parseJsonUint(json, ".starknet.layout.channelsBase"),
            statusOffset: 0,
            nextMessageIdOffset: 1,
            receivedMessageIdOffset: 2,
            sentRunningHashOffset: 3,
            receivedRunningHashOffset: 5,
            endpointManifestVersionOffset: 7,
            messagesBase: vm.parseJsonUint(json, ".starknet.layout.messagesBase"),
            messageRunningHashOffset: 0,
            manifestCommitmentAddress: vm.parseJsonUint(json, ".starknet.layout.manifestCommitmentAddress")
        });
    }

    /// 260-byte anchor with `cid` and the pinned class hash (committee fields only matter to the real
    /// light client).
    function _anchor(bytes32 cid, bytes32 pinnedClass, bytes32 committeeRoot, bytes memory aggregate)
        internal
        pure
        returns (bytes memory a)
    {
        a = new bytes(EthBeaconLightClient.TRUST_ANCHOR_LENGTH);
        bytes memory agg = aggregate.length == 128 ? aggregate : new bytes(128);
        assembly {
            let d := add(a, 32)
            mstore(add(d, 36), cid)
            mcopy(add(d, 68), add(agg, 32), 128)
            mstore(add(d, 196), committeeRoot)
            mstore(add(d, 228), pinnedClass)
        }
    }

    function _ctx(bytes32 cid, uint256 svc) internal pure returns (bytes memory) {
        return ClprTypes.encodeChannelContext(
            ClprTypes.ChannelContext({channelId: cid, remoteServiceAddress: abi.encodePacked(svc)})
        );
    }

    /// Bundle RLP: [lightClientProof, coreProof, starknetProof, lastMessageId, bundleContent (, manifest)].
    function _bundle(
        bytes memory lightClientProof,
        bytes memory core_,
        bytes memory starknetProof,
        bool withMessage,
        bool withManifest
    ) internal view returns (bytes memory) {
        bytes[] memory items = new bytes[](withManifest ? 6 : 5);
        items[0] = RLP.encode(lightClientProof);
        items[1] = core_;
        items[2] = RLP.encode(starknetProof);
        items[3] = withMessage
            ? RLP.encode(vm.parseJsonUint(json, ".starknet.expected.lastMessageId"))
            : RLP.encode(bytes(""));
        items[4] = RLP.encode(bytes(""));
        if (withManifest) items[5] = RLP.encode(manifest);
        return RLP.encode(items);
    }

    function _assertExpected(ClprTypes.QueueMetadata memory m) internal view {
        assertEq(uint8(m.state), vm.parseJsonUint(json, ".starknet.expected.status"), "status");
        assertEq(m.nextMessageId, vm.parseJsonUint(json, ".starknet.expected.nextMessageId"), "nextMessageId");
        assertEq(m.receivedMessageId, vm.parseJsonUint(json, ".starknet.expected.receivedMessageId"), "receivedId");
        assertEq(m.sentRunningHash, vm.parseJsonBytes32(json, ".starknet.expected.sentRunningHash"), "sentHash");
        assertEq(m.receivedRunningHash, vm.parseJsonBytes32(json, ".starknet.expected.receivedRunningHash"), "recvHash");
        assertEq(
            m.endpointManifestVersion,
            vm.parseJsonUint(json, ".starknet.expected.endpointManifestVersion"),
            "endpointManifestVersion"
        );
    }
}

/// @notice Pedersen and Poseidon against the reference vectors, and their gas.
contract StarkHashTest is StarknetFixture {
    struct PedersenVector {
        bytes32 a;
        bytes32 b;
        bytes32 h;
    }

    struct PoseidonVector {
        bytes32 h;
        bytes32[] xs;
    }

    function test_pedersen_matchesReferenceVectors() public view {
        PedersenVector[] memory v = abi.decode(vm.parseJson(json, ".vectors.pedersen"), (PedersenVector[]));
        assertGt(v.length, 10);
        for (uint256 i = 0; i < v.length; i++) {
            assertEq(prover.pedersen(uint256(v[i].a), uint256(v[i].b)), uint256(v[i].h));
        }
        // Known values: H(0, 0) is the shift point's x; H(1, 2) from starknet.js / cairo-lang.
        assertEq(prover.pedersen(0, 0), 0x049ee3eba8c1600700ee1b87eb599f16716b0b1022947733551fde4050ca6804);
        assertEq(prover.pedersen(1, 2), 0x05bb9440e27889a364bcb678b1f679ecd1347acdedcbf36e83494f857cc58026);
    }

    function test_poseidon_matchesReferenceVectors() public view {
        PoseidonVector[] memory v = abi.decode(vm.parseJson(json, ".vectors.poseidon"), (PoseidonVector[]));
        for (uint256 i = 0; i < v.length; i++) {
            uint256[] memory xs = new uint256[](v[i].xs.length);
            for (uint256 j = 0; j < xs.length; j++) {
                xs[j] = uint256(v[i].xs[j]);
            }
            assertEq(prover.poseidonHashMany(xs), uint256(v[i].h));
        }
    }

    function test_hashes_rejectNonFelts() public {
        vm.expectRevert(StarkPedersen.FeltOutOfRange.selector);
        prover.pedersen(P, 0);
        vm.expectRevert(StarkPedersen.FeltOutOfRange.selector);
        prover.pedersen(0, type(uint256).max);
        uint256[] memory xs = new uint256[](1);
        xs[0] = P;
        vm.expectRevert(StarkPoseidon.FeltOutOfRange.selector);
        prover.poseidonHashMany(xs);
    }

    function test_prover_rejectsWrongTables() public {
        address a = address(new StarkPedersenTableA());
        vm.expectRevert(StarknetStateProver.InvalidPedersenTables.selector);
        new StarknetStateProver(a, a);
    }

    function test_gas_pedersenAndPoseidon() public view {
        uint256 a = 0x3d937c035c878245caf64531a5756109c53068da139362728feb561405371cb;
        uint256 b = 0x208a0a10250e382e1e4bbe2880906c2791bf6275695e02fbbc6aeff9cd8b31a;
        uint256 g = gasleft();
        prover.pedersen(a, b);
        console.log("Pedersen H(a, b) gas (external call):", g - gasleft());
        uint256[] memory xs = new uint256[](3);
        xs[0] = 0x535441524b4e45545f53544154455f5630;
        xs[1] = a;
        xs[2] = b;
        g = gasleft();
        prover.poseidonHashMany(xs);
        console.log("poseidon_hash_many(3) gas (external call):", g - gasleft());
    }
}

/// @notice {StarknetStateProver} on real Starknet Sepolia data and on the synthetic state.
contract StarknetStateProverTest is StarknetFixture {
    function test_live_sepoliaStorageProof() public view {
        bytes memory proof = vm.parseJsonBytes(json, ".live.proof");
        uint256[] memory keys = vm.parseJsonUintArray(json, ".live.keys");
        uint256 g = gasleft();
        (uint256 ch,, uint256[] memory values) = prover.verifyStorage(
            vm.parseJsonUint(json, ".live.globalRoot"), vm.parseJsonUint(json, ".live.contract"), keys, proof
        );
        uint256 used = g - gasleft();
        assertEq(ch, vm.parseJsonUint(json, ".live.classHash"));
        uint256[] memory expected = vm.parseJsonUintArray(json, ".live.values");
        assertEq(values, expected);
        uint256 present = 0;
        for (uint256 i = 0; i < values.length; i++) {
            if (values[i] != 0) present++;
        }
        assertGt(present, 0, "a present key (STRK total supply)");
        assertLt(present, values.length, "an absent key");
        console.log("live Sepolia: STRK keys", keys.length);
        console.log("  contract nodes", vm.parseJsonUint(json, ".live.contractNodes"));
        console.log("  storage nodes", vm.parseJsonUint(json, ".live.storageNodes"));
        console.log("  verifyStorage gas", used);
        console.log("  proof bytes", proof.length);
    }

    function test_synthetic_readsTheQueue() public view {
        uint256[] memory keys = _keys("channel");
        (uint256 ch,, uint256[] memory v) = prover.verifyStorage(globalRoot, service, keys, _proof("channel"));
        assertEq(ch, classHash);
        assertEq(v[1], vm.parseJsonUint(json, ".starknet.expected.nextMessageId"));
    }

    function test_rejectsWrongGlobalRoot() public {
        uint256[] memory keys = _keys("channel");
        bytes memory proof = _proof("channel");
        vm.expectPartialRevert(StarknetStateProver.GlobalRootMismatch.selector);
        prover.verifyStorage(globalRoot ^ 1, service, keys, proof);
    }

    function test_rejectsStaleStateProof() public {
        // Same contract, same keys, an older Starknet state: its roots don't hash to the proven root.
        uint256[] memory keys = _keys("channel");
        bytes memory proof = _proof("staleChannel");
        vm.expectPartialRevert(StarknetStateProver.GlobalRootMismatch.selector);
        prover.verifyStorage(globalRoot, service, keys, proof);
    }

    function test_rejectsOtherContract() public {
        uint256[] memory keys = _keys("channel");
        bytes memory proof = _proof("channel");
        // A sibling address: its path leaves the proof's node set.
        vm.expectRevert();
        prover.verifyStorage(globalRoot, service ^ 1, keys, proof);
    }

    function test_rejectsForgedLeafData() public {
        uint256[] memory keys = _keys("channel");
        (uint256 cr, uint256 kr, uint256 ch, uint256 sr, uint256 n, uint256[] memory cn, uint256[] memory sn) =
            abi.decode(_proof("channel"), (uint256, uint256, uint256, uint256, uint256, uint256[], uint256[]));
        bytes memory forged = abi.encode(cr, kr, ch ^ 1, sr, n, cn, sn);
        vm.expectPartialRevert(StarknetStateProver.ContractLeafMismatch.selector);
        prover.verifyStorage(globalRoot, service, keys, forged);
        forged = abi.encode(cr, kr, ch, sr, n + 1, cn, sn);
        vm.expectPartialRevert(StarknetStateProver.ContractLeafMismatch.selector);
        prover.verifyStorage(globalRoot, service, keys, forged);
    }

    function test_rejectsTamperedStorageNode() public {
        uint256[] memory keys = _keys("channel");
        (uint256 cr, uint256 kr, uint256 ch, uint256 sr, uint256 n, uint256[] memory cn, uint256[] memory sn) =
            abi.decode(_proof("channel"), (uint256, uint256, uint256, uint256, uint256, uint256[], uint256[]));
        // Change the value under a leaf: the bottom node now hashes to something the trie never held.
        for (uint256 i = 0; i < sn.length; i += 3) {
            sn[i] = (sn[i] + 1) % P;
        }
        vm.expectPartialRevert(StarknetPatricia.MissingTrieNode.selector);
        prover.verifyStorage(globalRoot, service, keys, abi.encode(cr, kr, ch, sr, n, cn, sn));
    }

    function test_rejectsMalformedNodes() public {
        uint256[] memory keys = _keys("channel");
        (uint256 cr, uint256 kr, uint256 ch, uint256 sr, uint256 n, uint256[] memory cn,) =
            abi.decode(_proof("channel"), (uint256, uint256, uint256, uint256, uint256, uint256[], uint256[]));
        uint256[] memory bad = new uint256[](3);
        bad[0] = 1;
        bad[1] = 4; // path 0b100 does not fit length 2
        bad[2] = 2;
        vm.expectPartialRevert(StarknetPatricia.InvalidTrieNode.selector);
        prover.verifyStorage(globalRoot, service, keys, abi.encode(cr, kr, ch, sr, n, cn, bad));
        uint256[] memory ragged = new uint256[](4);
        vm.expectPartialRevert(StarknetPatricia.InvalidTrieNode.selector);
        prover.verifyStorage(globalRoot, service, keys, abi.encode(cr, kr, ch, sr, n, cn, ragged));
    }

    function test_rejectsKeyOutOfRange() public {
        uint256[] memory keys = new uint256[](1);
        keys[0] = 1 << 251;
        bytes memory proof = _proof("channel");
        vm.expectPartialRevert(StarknetPatricia.KeyOutOfRange.selector);
        prover.verifyStorage(globalRoot, service, keys, proof);
    }

    function test_globalRootFormula() public view {
        assertEq(prover.globalStateRoot(0, 0), 0);
        assertEq(
            prover.globalStateRoot(
                vm.parseJsonUint(json, ".starknet.contractsRoot"), vm.parseJsonUint(json, ".starknet.classesRoot")
            ),
            globalRoot
        );
    }
}

/// @notice {StarknetVerifier} on the synthetic state with the L1 light client mocked.
contract StarknetVerifierTest is StarknetFixture {
    MockEthL1StateVerifier internal l1;
    StarknetVerifier internal verifier;
    bytes internal anchor;
    bytes internal ctx;

    function setUp() public override {
        super.setUp();
        l1 = new MockEthL1StateVerifier(l1StateRoot, 1);
        verifier = new StarknetVerifier(l1, prover, _profile(), _layout());
        anchor = _anchor(channelId, bytes32(classHash), bytes32(0), "");
        ctx = _ctx(channelId, service);
    }

    function test_ackOnlyBundle() public view {
        bytes memory proof = _bundle("", coreProof, _proof("channel"), false, false);
        (ClprTypes.QueueMetadata memory m,, bytes memory na,, ClprTypes.ClprEndpointManifest memory em) =
            verifier.verifyBundle(proof, anchor, ctx);
        _assertExpected(m);
        assertEq(na.length, 0);
        assertEq(em.version, 0, "no manifest");
    }

    function test_bundleWithMessageAndManifest() public view {
        bytes memory proof = _bundle("", coreProof, _proof("full"), true, true);
        (ClprTypes.QueueMetadata memory m,,,, ClprTypes.ClprEndpointManifest memory em) =
            verifier.verifyBundle(proof, anchor, ctx);
        _assertExpected(m);
        assertEq(em.version, 2);
        assertEq(em.serviceAddress, abi.encodePacked(service));
    }

    function test_verifyStarknetState() public view {
        bytes[] memory items = new bytes[](2);
        items[0] = RLP.encode(bytes(""));
        items[1] = coreProof;
        (uint256 root, uint256 blockNumber,,) = verifier.verifyStarknetState(RLP.encode(items), anchor);
        assertEq(root, globalRoot);
        assertEq(blockNumber, vm.parseJsonUint(json, ".starknet.blockNumber"));
    }

    function test_rejectsWrongPinnedClassHash() public {
        bytes memory proof = _bundle("", coreProof, _proof("channel"), false, false);
        bytes memory other = _anchor(channelId, bytes32(classHash ^ 1), bytes32(0), "");
        vm.expectPartialRevert(StarknetVerifier.ClassHashMismatch.selector);
        verifier.verifyBundle(proof, other, ctx);
        // An unpinned anchor accepts any class.
        verifier.verifyBundle(proof, _anchor(channelId, bytes32(0), bytes32(0), ""), ctx);
    }

    function test_rejectsStorageProofOfAnotherChannel() public {
        // The keys are derived from ctx.channelId: the proof's nodes do not cover the other channel.
        bytes memory proof = _bundle("", coreProof, _proof("channel"), false, false);
        vm.expectPartialRevert(StarknetPatricia.MissingTrieNode.selector);
        verifier.verifyBundle(proof, anchor, _ctx(otherChannelId, service));
    }

    function test_rejectsStaleStarknetState() public {
        bytes memory proof = _bundle("", coreProof, _proof("staleChannel"), false, false);
        vm.expectPartialRevert(StarknetStateProver.GlobalRootMismatch.selector);
        verifier.verifyBundle(proof, anchor, ctx);
    }

    function test_rejectsWrongLastMessageId() public {
        bytes[] memory items = new bytes[](5);
        items[0] = RLP.encode(bytes(""));
        items[1] = coreProof;
        items[2] = RLP.encode(_proof("full"));
        items[3] = RLP.encode(uint256(3)); // nextMessageId is 5 → must be 4
        items[4] = RLP.encode(bytes(""));
        bytes memory proof = RLP.encode(items);
        vm.expectRevert();
        verifier.verifyBundle(proof, anchor, ctx);
    }

    function test_rejectsManifestPreimageMismatch() public {
        bytes memory proof = _bundle("", coreProof, _proof("full"), true, true);
        // Re-encode with another preimage (version 3).
        bytes[] memory items = new bytes[](6);
        items[0] = RLP.encode(bytes(""));
        items[1] = coreProof;
        items[2] = RLP.encode(_proof("full"));
        items[3] = RLP.encode(vm.parseJsonUint(json, ".starknet.expected.lastMessageId"));
        items[4] = RLP.encode(bytes(""));
        bytes memory m = manifest;
        m[1] = 0x03;
        items[5] = RLP.encode(m);
        proof = RLP.encode(items);
        vm.expectRevert(ClprEvmBundleVerifier.ManifestCommitmentMismatch.selector);
        verifier.verifyBundle(proof, anchor, ctx);
    }

    function test_rejectsUnpinnedCoreImplementation() public {
        StarknetVerifier.Profile memory p = _profile();
        p.coreImplCodeHash = keccak256("another implementation");
        StarknetVerifier v = new StarknetVerifier(l1, prover, p, _layout());
        bytes memory proof = _bundle("", coreProof, _proof("channel"), false, false);
        vm.expectPartialRevert(StarknetCoreProof.CoreImplementationMismatch.selector);
        v.verifyBundle(proof, anchor, ctx);
    }

    function test_rejectsChangedProgramHash() public {
        StarknetVerifier.Profile memory p = _profile();
        p.pinnedValues[0] = bytes32(uint256(p.pinnedValues[0]) ^ 1);
        StarknetVerifier v = new StarknetVerifier(l1, prover, p, _layout());
        bytes memory proof = _bundle("", coreProof, _proof("channel"), false, false);
        vm.expectPartialRevert(StarknetCoreProof.CorePinnedSlotMismatch.selector);
        v.verifyBundle(proof, anchor, ctx);
    }

    function test_rejectsUninitializedCore() public {
        StarknetVerifier.Profile memory p = _profile();
        p.core = vm.parseJsonAddress(json, ".l1.coreUninitialized");
        StarknetVerifier v = new StarknetVerifier(l1, prover, p, _layout());
        bytes memory proof =
            _bundle("", vm.parseJsonBytes(json, ".l1.coreProofUninitialized"), _proof("channel"), false, false);
        vm.expectRevert(StarknetCoreProof.StarknetNotInitialized.selector);
        v.verifyBundle(proof, anchor, ctx);
    }

    function test_rejectsCoreProofOfAnotherContract() public {
        StarknetVerifier.Profile memory p = _profile();
        p.core = address(0xbeef);
        StarknetVerifier v = new StarknetVerifier(l1, prover, p, _layout());
        bytes memory proof = _bundle("", coreProof, _proof("channel"), false, false);
        vm.expectRevert();
        v.verifyBundle(proof, anchor, ctx);
    }

    function test_unpinnedProfile() public {
        StarknetVerifier.Profile memory p;
        p.core = core;
        StarknetVerifier v = new StarknetVerifier(l1, prover, p, _layout());
        bytes memory proof =
            _bundle("", vm.parseJsonBytes(json, ".l1.coreProofNoPins"), _proof("channel"), false, false);
        (ClprTypes.QueueMetadata memory m,,,,) = v.verifyBundle(proof, anchor, ctx);
        _assertExpected(m);
    }

    function test_rejectsBadShapes() public {
        vm.expectRevert(StarknetVerifier.InvalidTrustAnchor.selector);
        verifier.verifyBundle(hex"c0", hex"00", ctx);
        vm.expectRevert(StarknetVerifier.InvalidPayloadShape.selector);
        verifier.verifyBundle(RLP.encode(new bytes[](4)), anchor, ctx);
        bytes memory proof = _bundle("", coreProof, _proof("channel"), false, false);
        vm.expectRevert(StarknetVerifier.InvalidStarknetAddress.selector);
        verifier.verifyBundle(
            proof,
            anchor,
            ClprTypes.encodeChannelContext(
                ClprTypes.ChannelContext({channelId: channelId, remoteServiceAddress: abi.encodePacked(address(1))})
            )
        );
        vm.expectRevert(StarknetVerifier.InvalidStarknetAddress.selector);
        verifier.verifyBundle(proof, anchor, _ctx(channelId, 1 << 251));
    }

    function test_constructor_rejectsIncompleteProfile() public {
        StarknetVerifier.Profile memory p = _profile();
        p.core = address(0);
        vm.expectRevert(StarknetVerifier.InvalidDeployment.selector);
        new StarknetVerifier(l1, prover, p, _layout());
        p = _profile();
        p.pinnedValues = new bytes32[](0);
        vm.expectRevert(StarknetVerifier.InvalidDeployment.selector);
        new StarknetVerifier(l1, prover, p, _layout());
        StarknetVerifier.Layout memory l = _layout();
        l.channelsBase = 1 << 251;
        vm.expectRevert(StarknetVerifier.InvalidDeployment.selector);
        new StarknetVerifier(l1, prover, _profile(), l);
    }

    function test_profileAndLayout_roundTrip() public view {
        StarknetVerifier.Profile memory p = verifier.profile();
        assertEq(p.core, core);
        assertEq(p.coreImplCodeHash, coreImplCodeHash);
        assertEq(p.pinnedSlots[0], StarknetCoreProof.PROGRAM_HASH_SLOT);
        assertEq(p.pinnedSlots[1], StarknetCoreProof.AGGREGATOR_PROGRAM_HASH_SLOT);
        StarknetVerifier.Layout memory l = verifier.layout();
        assertEq(l.channelsBase, uint256(keccak256("clpr_channels")) & ((1 << 250) - 1), "sn_keccak");
        assertEq(l.manifestCommitmentAddress, _layout().manifestCommitmentAddress);
    }
}

/// @notice End to end with the REAL {EthL1StateVerifier}: a generator sync committee (sk = 1) signs a
///         beacon header whose body commits the synthetic L1 state root, so BLS, the SSZ execution
///         branch, the core-contract MPT proofs and the Starknet tries all run for real.
contract StarknetVerifierEndToEndTest is StarknetFixture {
    bytes4 internal constant FORK_VERSION = 0x06000000;
    bytes32 internal constant GVR = bytes32(uint256(0x5e9011a));
    uint64 internal constant L1_SLOT = 8192 * 3 + 5;
    EthL1StateVerifier internal l1;
    StarknetVerifier internal verifier;
    bytes internal anchor;
    bytes internal ctx;

    function setUp() public override {
        super.setUp();
        l1 = new EthL1StateVerifier(
            ClprBeaconSsz.GINDEX_EXECUTION_STATE_ROOT_IN_BODY,
            9,
            ClprBeaconSsz.GINDEX_NEXT_SYNC_COMMITTEE_IN_STATE,
            6,
            8192
        );
        verifier = new StarknetVerifier(l1, prover, _profile(), _layout());
        anchor = EthBeaconLightClient.encodeTrustAnchor(
            _uncompressedKeys(SYNC_COMMITTEE_SIZE),
            _committeeAggregate(),
            GVR,
            abi.encodePacked(FORK_VERSION),
            channelId,
            bytes32(classHash)
        );
        ctx = _ctx(channelId, service);
    }

    function _lightClientProof(bytes memory bits, uint256 signers) internal view returns (bytes memory) {
        return _lightClientProof(bits, signers, false);
    }

    /// With `rotate`, the attested beacon state commits a next sync committee (the same generator
    /// committee) at gindex 87 and the proof carries it: the full rotation path runs.
    function _lightClientProof(bytes memory bits, uint256 signers, bool rotate) internal view returns (bytes memory) {
        bytes32 beaconStateRoot = bytes32(uint256(2));
        bytes[] memory nextCommittee;
        if (rotate) {
            bytes[] memory keys = _uncompressedKeys(SYNC_COMMITTEE_SIZE);
            bytes memory agg = _committeeAggregate();
            beaconStateRoot = ClprBeaconSsz.syncCommitteeRootFromUncompressed(keys, agg);
            uint256 gi = ClprBeaconSsz.GINDEX_NEXT_SYNC_COMMITTEE_IN_STATE;
            for (uint256 i = 0; i < 6; i++) {
                beaconStateRoot = gi & 1 == 1
                    ? sha256(abi.encodePacked(bytes32(0), beaconStateRoot))
                    : sha256(abi.encodePacked(beaconStateRoot, bytes32(0)));
                gi >>= 1;
            }
            nextCommittee = new bytes[](2);
            bytes[] memory enc = new bytes[](keys.length);
            for (uint256 i = 0; i < keys.length; i++) {
                enc[i] = RLP.encode(keys[i]);
            }
            nextCommittee[0] = RLP.encode(enc);
            nextCommittee[1] = RLP.encode(agg);
        }
        bytes32[] memory branch = new bytes32[](9);
        bytes32 bodyRoot = l1StateRoot;
        uint256 idx = ClprBeaconSsz.GINDEX_EXECUTION_STATE_ROOT_IN_BODY;
        for (uint256 i = 0; i < 9; i++) {
            bodyRoot = idx & 1 == 1
                ? sha256(abi.encodePacked(branch[i], bodyRoot))
                : sha256(abi.encodePacked(bodyRoot, branch[i]));
            idx >>= 1;
        }
        bytes32 headerRoot =
            ClprBeaconSsz.beaconBlockHeaderRoot(L1_SLOT, 7, bytes32(uint256(1)), beaconStateRoot, bodyRoot);
        bytes32 signingRoot =
            ClprBeaconSsz.computeSigningRoot(headerRoot, ClprBeaconSsz.computeSyncCommitteeDomain(FORK_VERSION, GVR));
        bytes[] memory header = new bytes[](5);
        header[0] = RLP.encode(uint256(L1_SLOT));
        header[1] = RLP.encode(uint256(7));
        header[2] = RLP.encode(bytes32(uint256(1)));
        header[3] = RLP.encode(beaconStateRoot);
        header[4] = RLP.encode(bodyRoot);
        bytes[] memory agg = new bytes[](2);
        agg[0] = RLP.encode(bits);
        agg[1] = RLP.encode(_aggSig(signingRoot, signers));
        bytes[] memory br = new bytes[](9);
        for (uint256 i = 0; i < 9; i++) {
            br[i] = RLP.encode(branch[i]);
        }
        bytes[] memory lc = new bytes[](7);
        lc[0] = RLP.encode(header);
        lc[1] = RLP.encode(agg);
        lc[2] = RLP.encode(l1StateRoot);
        lc[3] = RLP.encode(br);
        if (rotate) {
            lc[4] = RLP.encode(nextCommittee);
            bytes[] memory nb = new bytes[](6);
            for (uint256 i = 0; i < 6; i++) {
                nb[i] = RLP.encode(bytes32(0));
            }
            lc[5] = RLP.encode(nb);
        } else {
            lc[4] = RLP.encode(bytes(""));
            lc[5] = RLP.encode(new bytes[](0));
        }
        lc[6] = RLP.encode(new bytes[](0));
        return RLP.encode(lc);
    }

    function _bits(uint256 n) internal pure returns (bytes memory b) {
        b = new bytes(64);
        for (uint256 i = 0; i < n; i++) {
            b[i / 8] = bytes1(uint8(b[i / 8]) | uint8(1 << (i % 8)));
        }
    }

    function test_endToEnd_typicalBundle() public view {
        bytes memory proof = _bundle(_lightClientProof(_bits(512), 512), coreProof, _proof("channel"), false, false);
        uint256 g = gasleft();
        (ClprTypes.QueueMetadata memory m,, bytes memory na,,) = verifier.verifyBundle(proof, anchor, ctx);
        uint256 used = g - gasleft();
        _assertExpected(m);
        assertEq(na.length, 0);
        console.log("StarknetVerifier.verifyBundle (ACK-only, 512/512, dense tries) gas:", used);
        console.log("  proofBytes:", proof.length);
    }

    function test_endToEnd_fullBundle() public view {
        bytes memory proof = _bundle(_lightClientProof(_bits(512), 512), coreProof, _proof("full"), true, true);
        uint256 g = gasleft();
        (ClprTypes.QueueMetadata memory m,,,, ClprTypes.ClprEndpointManifest memory em) =
            verifier.verifyBundle(proof, anchor, ctx);
        uint256 used = g - gasleft();
        _assertExpected(m);
        assertEq(em.version, 2);
        console.log("StarknetVerifier.verifyBundle (message + manifest keys, dense tries) gas:", used);
        console.log("  proofBytes:", proof.length);
    }

    function test_endToEnd_rotation_typicalAndFullBundle() public view {
        bytes memory lcp = _lightClientProof(_bits(512), 512, true);
        bytes memory proof = _bundle(lcp, coreProof, _proof("channel"), false, false);
        uint256 g = gasleft();
        (ClprTypes.QueueMetadata memory m,, bytes memory na, bytes memory naId,) =
            verifier.verifyBundle(proof, anchor, ctx);
        uint256 used = g - gasleft();
        _assertExpected(m);
        assertEq(na, anchor, "rotated to the (same) next committee: same anchor bytes");
        assertEq(naId, abi.encodePacked(uint64(L1_SLOT / 8192 + 1)));
        console.log("StarknetVerifier.verifyBundle + committee rotation (ACK-only) gas:", used);
        console.log("  proofBytes:", proof.length);
        proof = _bundle(lcp, coreProof, _proof("full"), true, true);
        g = gasleft();
        verifier.verifyBundle(proof, anchor, ctx);
        used = g - gasleft();
        console.log("StarknetVerifier.verifyBundle + committee rotation (message + manifest) gas:", used);
        console.log("  proofBytes:", proof.length);
        assertLt(used, 15_000_000);
        assertLt(proof.length, 128 * 1024);
    }

    function test_endToEnd_rejectsSignatureUnderOtherForkVersion() public {
        bytes memory proof = _bundle(_lightClientProof(_bits(512), 512), coreProof, _proof("channel"), false, false);
        bytes memory other = anchor;
        other[35] = 0x01; // fork version byte 3
        vm.expectRevert();
        verifier.verifyBundle(proof, other, ctx);
    }

    function test_endToEnd_rejectsBadSignature() public {
        // 511 keys signed but all 512 bits are set: the aggregate does not match.
        bytes memory proof = _bundle(_lightClientProof(_bits(512), 511), coreProof, _proof("channel"), false, false);
        vm.expectRevert();
        verifier.verifyBundle(proof, anchor, ctx);
    }

    function test_endToEnd_rejectsBelowThreshold() public {
        bytes memory proof = _bundle(_lightClientProof(_bits(341), 341), coreProof, _proof("channel"), false, false);
        vm.expectPartialRevert(EthBeaconLightClient.InsufficientParticipation.selector);
        verifier.verifyBundle(proof, anchor, ctx);
    }

    function test_endToEnd_rejectsWrongValidatorSet() public {
        // An anchor for another committee (aggregate 511·G instead of 512·G): the signature does not verify.
        bytes memory proof = _bundle(_lightClientProof(_bits(512), 512), coreProof, _proof("channel"), false, false);
        (bool ok, bytes memory otherAggregate) =
            BLS12_G1MSM.staticcall(abi.encodePacked(genUncompressed, bytes32(uint256(511))));
        assertTrue(ok);
        bytes memory other = EthBeaconLightClient.encodeTrustAnchor(
            _uncompressedKeys(SYNC_COMMITTEE_SIZE),
            otherAggregate,
            GVR,
            abi.encodePacked(FORK_VERSION),
            channelId,
            bytes32(classHash)
        );
        vm.expectRevert();
        verifier.verifyBundle(proof, other, ctx);
    }

    function test_verifyConfig_buildsAnchorAndManifest() public view {
        ClprTypes.LedgerConfiguration memory lc;
        lc.chainId = "starknet:SN_SEPOLIA";
        lc.serviceAddress = abi.encodePacked(service);
        lc.throttles.maxPeerEndpoints = 9;
        bytes[] memory cfg = new bytes[](6);
        cfg[0] = RLP.encode(uint256(L1_SLOT));
        cfg[1] = _encodeCommittee(_uncompressedKeys(SYNC_COMMITTEE_SIZE), _committeeAggregate());
        cfg[2] = RLP.encode(GVR);
        cfg[3] = RLP.encode(abi.encodePacked(FORK_VERSION));
        cfg[4] = RLP.encode(ClprProtobuf.encodeControlMessage(lc));
        cfg[5] = RLP.encode(bytes32(classHash));
        bytes[] memory mp = new bytes[](4);
        mp[0] = RLP.encode(_lightClientProof(_bits(512), 512));
        mp[1] = coreProof;
        mp[2] = RLP.encode(_proof("manifestOnly"));
        mp[3] = RLP.encode(manifest);
        (
            bytes memory channelContext,
            string memory chainId,
            bytes memory serviceAddress,,
            ClprTypes.Throttles memory throttles,
            bytes memory initialAnchor,
            bytes memory anchorId,
            ClprTypes.ClprEndpointManifest memory em
        ) = verifier.verifyConfig(RLP.encode(cfg), channelId, RLP.encode(mp));
        assertEq(initialAnchor, anchor, "same anchor as the bundle path");
        assertEq(anchorId, abi.encodePacked(uint64(3)));
        assertEq(chainId, "starknet:SN_SEPOLIA");
        assertEq(serviceAddress, abi.encodePacked(service));
        assertEq(throttles.maxPeerEndpoints, 9);
        assertEq(channelContext, ctx);
        assertEq(em.version, 2);
    }
}
